### ISSUE TITLE
0002330:
Can't Update Task from 3.0 to 3.1

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#1246]
**Reported by Peterchen on 24 Feb 2010 15:45**

I have this Error Log when im using the console!
The webinterface does not work too

**Additional information:** 2010-02-24T15:32:34+00:00 INFO (6): Setup_Controller::updateApplication::316 Executing updates for Tasks (starting at 3.0)
2010-02-24T15:32:34+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::84  startTransaction request
2010-02-24T15:32:34+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::86  new transactionable. Starting transaction on this resource
2010-02-24T15:32:34+00:00 DEBUG (7): Tinebase_TransactionManager::startTransaction::99  queued transaction with id a2a392ab55627a9a0031e1dc5fb58c45cd5d26f4
2010-02-24T15:32:34+00:00 INFO (6): Setup_Controller::updateApplication::337 Updating Tasks - update_0
2010-02-24T15:32:34+00:00 DEBUG (7): Tinebase_TransactionManager::rollBack::141  rollBack request, rollBack all transactionables
2010-02-24T15:32:34+00:00 ERR (3): Setup_Controller::updateApplication::347 SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./tatest/tine20_tasks&#039; to &#039;./tatest/#sql2-c59-dbef&#039; (errno: 152)
2010-02-24T15:32:34+00:00 ERR (3): Setup_Controller::updateApplication::348 #0 /var/www/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /var/www/Setup/Backend/Abstract.php(190): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/www/Setup/Backend/Abstract.php(331): Setup_Backend_Abstract-&gt;execQueryVoid(&#039;ALTER TABLE `ti...&#039;)
#5 /var/www/Tasks/Setup/Update/Release3.php(19): Setup_Backend_Abstract-&gt;dropForeignKey(&#039;tasks&#039;, &#039;tasks::class_id...&#039;)
#6 /var/www/Setup/Controller.php(341): Tasks_Setup_Update_Release3-&gt;update_0()
#7 /var/www/Setup/Controller.php(246): Setup_Controller-&gt;updateApplication(Object(Tinebase_Model_Application), &#039;3&#039;)
#8 /var/www/Setup/Frontend/Cli.php(198): Setup_Controller-&gt;updateApplications(Object(Tinebase_Record_RecordSet))
#9 /var/www/Setup/Frontend/Cli.php(53): Setup_Frontend_Cli-&gt;_update(Object(Zend_Console_Getopt))
#10 /var/www/Setup/Server/Cli.php(69): Setup_Frontend_Cli-&gt;handle(Object(Zend_Console_Getopt))
#11 /var/www/Setup/Core.php(69): Setup_Server_Cli-&gt;handle()
#12 /var/www/setup.php(48): Setup_Core::dispatchRequest()
#13 {main}
PHP Fatal error:  Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./tatest/tine20_tasks&#039; to &#039;./tatest/#sql2-c59-dbef&#039; (errno: 152)&#039; in /var/www/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /var/www/Setup/Backend/Abstract.php(190): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/www/Setup/Backend/Abstract.php(331): Setup_Backend_Abst in /var/www/library/Zend/Db/Statement/Pdo.php on line 238

Fatal error: Uncaught exception &#039;Zend_Db_Statement_Exception&#039; with message &#039;SQLSTATE[HY000]: General error: 1025 Error on rename of &#039;./tatest/tine20_tasks&#039; to &#039;./tatest/#sql2-c59-dbef&#039; (errno: 152)&#039; in /var/www/library/Zend/Db/Statement/Pdo.php:238
Stack trace:
#0 /var/www/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /var/www/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /var/www/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#3 /var/www/Setup/Backend/Abstract.php(190): Zend_Db_Adapter_Pdo_Abstract-&gt;query(&#039;ALTER TABLE `ti...&#039;, Array)
#4 /var/www/Setup/Backend/Abstract.php(331): Setup_Backend_Abst in /var/www/library/Zend/Db/Statement/Pdo.php on line 238

**Comment by Gloirin** [comment]
**Comment posted by Peterchen on 26 Feb 2010 10:04**

Just delete dropForeignKey and put $this-&gt;_backend-&gt;dropCol(&#039;tasks&#039;, &#039;class_id&#039;); to the top.
