### ISSUE TITLE
0003672:
EMail Sync mit IPhone funktioniert nicht

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#1912]
**Reported by kobusch on 7 Jan 2011 09:11**

**Version:** git master

Beim Mail-Sync mit einem IPhone 3 und 4 erhalte ich folgende Fehlermeldung im Log: 
ActiveSync_Command_FolderSync::getResponse::132 failed to get folders for class Email. SQLSTATE[HY093]: Invalid parameter number: no parameters were bound

**Steps to reproduce:** Einrichten des Exchange Konto auf dem IPhone entsprechend des EIntrags im Forum
Auf neues Konto gehen und Mails aktualisieren

Fehler auf dem IPhone: 
EMails konnten nicht empfangen werden

**Additional information:** f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): ActiveSync_Server_Http::handle::95 REQUEST Array
(
    [protocolVersion] =&gt; 2.5
    [command] =&gt; FolderSync
    [deviceId] =&gt; Appl83042TD3A4T
    [deviceType] =&gt; iPhone
)

f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): ActiveSync_Frontend_Http::handlePost::104 Agent: Apple-iPhone3C1/803.148  PolicyKey: 0 ASVersion: 2.5 Command: FolderSync
f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): ActiveSync_Frontend_Http::handlePost::116 class name: ActiveSync_Command_FolderSync
f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): ActiveSync_Command_Wbxml::__construct::95 decoded wbxml content: &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;FolderSync xmlns=&quot;uri:FolderHierarchy&quot;&gt;&lt;SyncKey&gt;0&lt;/SyncKey&gt;&lt;/FolderSync&gt;

f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): ActiveSync_Command_Wbxml::__construct::101 sync timestamp: 2011-01-07 11:07:56
f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): ActiveSync_Command_FolderSync::handle::101 synckey is 0
f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): Tinebase_Config::getConfig::103 Config setting &quot;mapPanel&quot; not found, using default (1).
f40c8 Wurst, Hans - 2011-01-07T11:07:56+00:00 DEBUG (7): Tinebase_Config::getConfig::114 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 TRACE (8): Felamimail_Backend_ImapFactory::factory::35 Getting IMAP backend for account id
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 DEBUG (7): Felamimail_Backend_ImapFactory::factory::43 Connecting to server : (none) with username Hans
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 INFO (6): Felamimail_Controller_Cache_Folder::update::102 Get subfolders of root for backend Array
(
    [id] =&gt;
    [user] =&gt; Hans
)

f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 DEBUG (7): Felamimail_Controller_Account::updateCapabilities::491 Setting personal namespace: &quot;INBOX.&quot;
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 DEBUG (7): Felamimail_Controller_Account::updateCapabilities::496 Updated sent/trash folder names: INBOX. / INBOX.
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 INFO (6): Felamimail_Controller_Account::updateCapabilities::511 Updating capabilities for account:
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 WARN (4): ActiveSync_Command_FolderSync::getResponse::132 failed to get folders for class Email. SQLSTATE[HY093]: Invalid parameter number: no parameters were bound
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 DEBUG (7): ActiveSync_Command_FolderSync::getResponse::185 Contacts =&gt; 3
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 DEBUG (7): ActiveSync_Command_FolderSync::getResponse::185 Tasks =&gt; tasks-root
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 DEBUG (7): ActiveSync_Command_FolderSync::getResponse::185 Calendar =&gt; 4
f40c8 Wurst, Hans - 2011-01-07T11:07:57+00:00 DEBUG (7): ActiveSync_Controller::updateSyncKey::276 update synckey to 1

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 7 Jan 2011 15:29**

Aktualisiere doch bitte vom SVN und versuche noch mal synchronisieren.

Es wird immer noch nicht funktionieren, aber die Fehlermeldung wird detaillierter sein.

**Comment by Gloirin** [comment]
**Comment posted by cweiss on 7 Jan 2011 16:39**

Aktualisiere doch bitte vom SVN und versuche noch mal synchronisieren.

Es wird immer noch nicht funktionieren, aber die Fehlermeldung wird detaillierter sein.

**Comment by Gloirin** [comment]
**Comment posted by kobusch on 7 Jan 2011 18:24**

Hier die Ausgabe nach SVN Aktualisierung, hoffe es hilft:

701b8 -- none -- - 2011-01-07T18:20:38+00:00 DEBUG (7): Tinebase_Config::getConfig::103 Config setting &quot;sessionIpValidation&quot; not found, using default (1).
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::startTransaction::82  startTransaction request
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::startTransaction::84  new transactionable. Starting transaction on this resource
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::startTransaction::97  queued transaction with id 43b3fb1ce95c891f48c9a26b78aa1b46f8e3d11c
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::commitTransaction::110  commitTransaction request for 43b3fb1ce95c891f48c9a26b78aa1b46f8e3d11c
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::commitTransaction::118  no more open transactions in queue commiting all transactionables
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Server_Http::handle::95 REQUEST Array
(
    [protocolVersion] =&gt; 2.5
    [command] =&gt; FolderSync
    [deviceId] =&gt; Appl83042TD3A4T
    [deviceType] =&gt; iPhone
)

701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Frontend_Http::handlePost::104 Agent: Apple-iPhone3C1/803.148  PolicyKey: 0 ASVersion: 2.5 Command: FolderSync
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Frontend_Http::handlePost::116 class name: ActiveSync_Command_FolderSync
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Command_Wbxml::__construct::95 decoded wbxml content: &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;FolderSync xmlns=&quot;uri:FolderHierarchy&quot;&gt;&lt;SyncKey&gt;1&lt;/SyncKey&gt;&lt;/FolderSync&gt;

701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Command_Wbxml::__construct::101 sync timestamp: 2011-01-07 18:20:38
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Command_FolderSync::handle::101 synckey is 1
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): Tinebase_Config::getConfig::103 Config setting &quot;mapPanel&quot; not found, using default (1).
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): Tinebase_Config::getConfig::114 Overwriting config setting &quot;mapPanel&quot; with value from config.inc.php.
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Felamimail_Backend_ImapFactory::factory::35 Getting IMAP backend for account id
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): Felamimail_Backend_ImapFactory::factory::43 Connecting to server : (none) with username Hans
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 INFO (6): Felamimail_Controller_Cache_Folder::update::102 Get subfolders of root for backend Array
(
    [id] =&gt;
    [user] =&gt; Hans
)

701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): Felamimail_Controller_Account::updateCapabilities::491 Setting personal namespace: &quot;INBOX.&quot;
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): Felamimail_Controller_Account::updateCapabilities::496 Updated sent/trash folder names: INBOX. / INBOX.
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 INFO (6): Felamimail_Controller_Account::updateCapabilities::511 Updating capabilities for account:
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 CRIT (2): ActiveSync_Command_FolderSync::getResponse::132 failed to get folders for class Email. #0 /mnt/daten/system/www/htdocs/tine20/library/Zend/Db/Statement.php(284): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 /mnt/daten/system/www/htdocs/tine20/library/Zend/Db/Adapter/Abstract.php(468): Zend_Db_Statement-&gt;execute(Array)
#2 /mnt/daten/system/www/htdocs/tine20/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Select), Array)
#3 /mnt/daten/system/www/htdocs/tine20/Tinebase/Backend/Sql/Abstract.php(174): Zend_Db_Adapter_Pdo_Abstract-&gt;query(Object(Zend_Db_Select))
#4 /mnt/daten/system/www/htdocs/tine20/Tinebase/Backend/Sql/Abstract.php(154): Tinebase_Backend_Sql_Abstract-&gt;getByProperty(NULL, &#039;id&#039;, true)
#5 /mnt/daten/system/www/htdocs/tine20/Tinebase/Backend/Sql/Abstract.php(454): Tinebase_Backend_Sql_Abstract-&gt;get(NULL, true)
#6 /mnt/daten/system/www/htdocs/tine20/Felamimail/Controller/Account.php(517): Tinebase_Backend_Sql_Abstract-&gt;update(Object(Felamimail_Model_Account))
#7 /mnt/daten/system/www/htdocs/tine20/Felamimail/Controller/Cache/Folder.php(111): Felamimail_Controller_Account-&gt;updateCapabilities(Object(Felamimail_Model_Account), Object(Felamimail_Backend_ImapProxy), NULL)
#8 /mnt/daten/system/www/htdocs/tine20/ActiveSync/Controller/Email.php(527): Felamimail_Controller_Cache_Folder-&gt;update(Object(Felamimail_Model_Account))
#9 /mnt/daten/system/www/htdocs/tine20/ActiveSync/Command/FolderSync.php(130): ActiveSync_Controller_Email-&gt;getSupportedFolders()
#10 /mnt/daten/system/www/htdocs/tine20/ActiveSync/Frontend/Http.php(123): ActiveSync_Command_FolderSync-&gt;getResponse()
#11 /mnt/daten/system/www/htdocs/tine20/ActiveSync/Server/Http.php(97): ActiveSync_Frontend_Http-&gt;handlePost(&#039;best-mixer.no-i...&#039;, &#039;Appl83042TD3A4T&#039;, &#039;iPhone&#039;, &#039;FolderSync&#039;, &#039;2.5&#039;)
#12 /mnt/daten/system/www/htdocs/tine20/Tinebase/Core.php(219): ActiveSync_Server_Http-&gt;handle()
#13 /mnt/daten/system/www/htdocs/tine20/index.php(57): Tinebase_Core::dispatchRequest()
#14 {main}
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Controller::updateSyncKey::276 update synckey to 1
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::startTransaction::82  startTransaction request
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::startTransaction::84  new transactionable. Starting transaction on this resource
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::startTransaction::97  queued transaction with id 7f1dd68adc3fd32176db95c1584741d83df9e83b
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::commitTransaction::110  commitTransaction request for 7f1dd68adc3fd32176db95c1584741d83df9e83b
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 TRACE (8): Tinebase_TransactionManager::commitTransaction::118  no more open transactions in queue commiting all transactionables
701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 DEBUG (7): ActiveSync_Command_Wbxml::getResponse::129 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;!DOCTYPE AirSync PUBLIC &quot;-//AIRSYNC//DTD AirSync//EN&quot; &quot;http://www.microsoft.com/&quot;&gt;
&lt;FolderSync xmlns=&quot;uri:FolderHierarchy&quot;&gt;&lt;Status&gt;1&lt;/Status&gt;&lt;SyncKey&gt;1&lt;/SyncKey&gt;&lt;Changes&gt;&lt;Count&gt;0&lt;/Count&gt;&lt;/Changes&gt;&lt;/FolderSync&gt;

701b8 Wurst, Hans - 2011-01-07T18:20:38+00:00 INFO (6): index.php (75) TIME: 0.531626939774 seconds  MEMORY6.25 MBytes  REALPATHCACHESIZE unknown

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 8 Jan 2011 08:36**

Aktualisiere bitte noch einmal vom SVN.

Das Problem ist, das an dieser Stelle

Tinebase_Backend_Sql_Abstract-&gt;get(NULL, true)

der erste Parameter nicht NULL sein darf.

Daher habe ich noch mehr Debug Statements eingebaut.

Du kannst mir die Logdatei auch am meine persönliche EMailadresse(l.kneschke@metaways.de) schicken. Wenn ich das richtige sehe überarbeitest Du die Logdatei immer.
