### ISSUE TITLE
0005666:
Tinebase_CustomField::resolveMultipleCustomfields uses too much RAM (in calendar)

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#2888]
**Reported by pschuele on 13 Feb 2012 14:29**

**Version:** Milan (2012-03) Beta 3

Tinebase_CustomField::resolveMultipleCustomfields uses too much RAM

-&gt; if you add some customfields to the addressbook and searchEvents with lots of attenders you get a memory exception

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Feb 2012 16:00**

problematic has been this call:

Stack trace:
#0 /usr/local/workspace/tine20/tine20/Tinebase/Controller/Record/Abstract.php(348): Tinebase_CustomField-&gt;resolveMultipleCustomfields(Object(Tinebase_Record_RecordSet))
#1 /usr/local/workspace/tine20/tine20/Calendar/Model/Attender.php(590): Tinebase_Controller_Record_Abstract-&gt;getMultiple(Array, true)
#2 /usr/local/workspace/tine20/tine20/Calendar/Frontend/Json.php(301): Calendar_Model_Attender::resolveAttendee(Array)

-&gt; do not resolve cfs when resolving attendee!
