### ISSUE TITLE
0006642:
passwords stored in trace log

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3370]
**Reported by McAldo on 19 Jun 2012 09:37**

**Version:** Milan (2012-03-3)

Is the logging put to trace in Tine 2.0 the password of the initial admin-user and ldap bind user will be written in the log, too. Passwords should generally not be written in logs. That is critical with view to safety aspects.

**Comment by Gloirin** [comment]
**Comment posted by lkneschke on 19 Jun 2012 10:13**

Can you post the full stack trace from the log?

I already implemented filtering the credentials some weeks ago. I need to know where the password is still logged.

**Comment by Gloirin** [comment]
**Comment posted by McAldo on 20 Jun 2012 07:18**

A full trace log I posted here: http://nopaste.debianforum.de/36525

I changed all readable passwords to &quot;secret&quot; or &quot;supersecret&quot;. :)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Jun 2013 16:33**

89e85 login - 2013-06-12T10:59:33+00:00 INFO (6): exception &#039;Tinebase_Exception_Backend_Database_LockTimeout&#039; with message &#039;SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction&#039; in /opt/local/tine/2012.10.4pl44/htdocs/Tinebase/Controller/Record/Abstract.php:497
Stack trace:
#0 /opt/local/tine/2012.10.4pl44/htdocs/Tinebase/Controller/Record/Abstract.php(475): Tinebase_Controller_Record_Abstract-&gt;_handleRecordCreateOrUpdateException(Object(Zend_Db_Statement_Exception))
#1 /opt/local/tine/2012.10.4pl44/htdocs/Tinebase/Controller.php(104): Tinebase_Controller_Record_Abstract-&gt;create(Object(Tinebase_Model_AccessLog))
#2 /opt/local/tine/2012.10.4pl44/htdocs/Tinebase/Frontend/Http.php(328): Tinebase_Controller-&gt;login(&#039;login-...&#039;, &#039;secret&#039;, &#039;someip&#039;, &#039;TineHttpPost&#039;)
#3 [internal function]: Tinebase_Frontend_Http-&gt;loginFromPost(&#039;login-...&#039;, &#039;secret&#039;)
#4 [internal function]: ReflectionMethod-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#5 /opt/local/tine/2012.10.4pl44/htdocs/library/Zend/Server/Reflection/Function/Abstract.php(368): call_user_func_array(Array, Array)
#6 /opt/local/tine/2012.10.4pl44/htdocs/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Function_Abstract-&gt;__call(&#039;invokeArgs&#039;, Array)
#7 /opt/local/tine/2012.10.4pl44/htdocs/Tinebase/Http/Server.php(147): Zend_Server_Reflection_Method-&gt;invokeArgs(Object(Tinebase_Frontend_Http), Array)
#8 /opt/local/tine/2012.10.4pl44/htdocs/Tinebase/Server/Http.php(80): Tinebase_Http_Server-&gt;handle(Array)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Jun 2013 09:01**

i removed all confidential TRACE logs and the exception traces in Tinebase_Server_Http are now filtered, too.

https://gerrit.tine20.org/tine20/2120
