### ISSUE TITLE
0006644:
"At least one mail header line is too long"

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#3371]
**Reported by Gurney on 19 Jun 2012 12:04**

**Version:** Milan (2012.03.5)

For some emails (can&#039;t really figure out the root cause) I get the following error when clicking on &quot;Send&quot;:

&quot;At least one mail header line is too long&quot;

Please see the attached log.

**Additional information:** #0 .../library/Zend/Mail/Transport/Smtp.php(237): Zend_Mail_Transport_Abstract-&gt;_prepareHeaders(Array)
#1 .../library/Zend/Mail/Transport/Abstract.php(337): Zend_Mail_Transport_Smtp-&gt;_prepareHeaders(Array)
#2 .../library/Zend/Mail.php(973): Zend_Mail_Transport_Abstract-&gt;send(Object(Tinebase_Mail))
#3 .../Tinebase/Smtp.php(138): Zend_Mail-&gt;send(Object(Felamimail_Transport))
#4 .../Felamimail/Controller/Message/Send.php(183): Tinebase_Smtp-&gt;sendMessage(Object(Tinebase_Mail), Object(Felamimail_Transport))
#5 .../Felamimail/Controller/Message/Send.php(78): Felamimail_Controller_Message_Send-&gt;_sendMailViaTransport(Object(Tinebase_Mail), Object(Felamimail_Model_Account), Object(Felamimail_Model_Message), true, Array)
#6 .../Felamimail/Frontend/Json.php(242): Felamimail_Controller_Message_Send-&gt;sendMessage(Object(Felamimail_Model_Message))
#7 [internal function]: Felamimail_Frontend_Json-&gt;saveMessage(Array)
#8 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#9 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#10 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#11 .../Tinebase/Server/Json.php(199): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#12 .../Tinebase/Server/Json.php(78): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#13 .../Tinebase/Core.php(227): Tinebase_Server_Json-&gt;handle()
#14 .../index.php(57): Tinebase_Core::dispatchRequest()
#15 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Jun 2012 12:11**

Zend Framework only accepts headers that are shorter than 999 chars.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 26 Jun 2012 12:33**

Integrated in tine20:1,849  ( See http://ci.tine20.org/job/tine20/1849/ ).

Revision/Changeset: 8405e157b47445bdf4de0c102a71653f8f37ffc4 
Author: Philipp Schüle
Log: 
#6644: &quot;At least one mail header line is too long&quot;
Changed paths:
 tine20/Felamimail/Controller/Message/Send.php
 tests/tine20/Felamimail/JsonTest.php

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 2 Jul 2012 08:36**

I again got the same message with latest GIT.

But I noticed the following:

When I get the error, I can save it as a draft. Then open the draft and send it and it works.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Jul 2012 14:37**

could you please try again with the current master?

if it still does not work, please set the logging to TRACE and send me the logfile.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 16 Jul 2012 14:58**

Integrated in tine20:1,882  ( See http://ci.tine20.org/job/tine20/1882/ ).

Revision/Changeset: 8c0cbcf15435e6717413ad4990c9dd9e4552c07c 
Author: Philipp Schüle
Log: 
#6644: &quot;At least one mail header line is too long&quot;
Changed paths:
 tine20/Felamimail/Controller/Message/Send.php

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 20 Jul 2012 04:47**

ok

so far, so good, didn&#039;t get the error since a while.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 20 Jul 2012 08:16**

ok, please reopen if the error occurs again. thanks for testing.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 4 Dec 2012 10:14**

The bug is back, with this message :

https://arrakeen.net/fb57dfd33df133d79f4c5ee2b0f610ec5c54cf65.eml

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Dec 2012 12:15**

ahh, not again ;)

I&#039;ll have a look.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 7 Jan 2013 15:55**

hi gurney,

i&#039;m sorry, i did not fetch the message yet. could you please upload it once again?

thanks.

**Comment by Gloirin** [comment]
**Comment posted by Gurney on 7 Jan 2013 22:01**

Unfortunately, I&#039;ve lost it when my RAID 5 array failed.

Maybe we can close this bug for now, I&#039;ll reopen it if it happens again (as soon as I can reinstall it with the LDAP backend #7616 ;))

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 8 Jan 2013 12:16**

ok, i&#039;ll close it for the moment ;)
