### ISSUE TITLE
0008398:
Shared folder are not available in WebDav

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#4224]
**Reported by Mattz on 18 May 2013 14:33**

**Version:** Kristina (2013.03.3)

When you connect to the filemanager using webdav the shared folder is empty.

- When a user adds a shared folder it&#039;s still empty
- When you add rights to a user for a shared folder it&#039;s still empty

**Steps to reproduce:** Mount webdav and go to: Filemanager/shared

**Additional information:** Personal folders are filled.

http://www.tine20.org/forum/viewtopic.php?f=10&amp;t=12272
http://www.tine20.org/forum/viewtopic.php?f=12&amp;t=14228

**Comment by Gloirin** [comment]
**Comment posted by Mattz on 28 May 2013 06:51**

Is there already any update on this or any thoughts about how to resolve this issue ?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 28 May 2013 08:29**

i&#039;ll try to reproduce that bug in the next days.

**Comment by Gloirin** [comment]
**Comment posted by Mattz on 28 May 2013 09:55**

Thanks!

**Comment by Gloirin** [comment]
**Comment posted by Mattz on 1 Jun 2013 10:44**

Here is some extra information that might be usefull:

e9dab UserName - 2013-06-01T10:40:26+00:00 INFO (6): Tinebase_Server_WebDAV::handle::83 requestUri:/webdav/Filemanager/personal/UserName/._naamloze%20map%203
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::92 &lt;&lt;&lt; *DAV request
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;D:propfind xmlns:D=&quot;DAV:&quot;&gt;
&lt;D:prop&gt;
&lt;D:getlastmodified/&gt;
&lt;D:getcontentlength/&gt;
&lt;D:creationdate/&gt;
&lt;D:resourcetype/&gt;
&lt;/D:prop&gt;
&lt;/D:propfind&gt;

e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_WebDav_Collection_Abstract::getChild::126 path: Filemanager name: personal
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_WebDav_Collection_Abstract::getChild::126 path: Filemanager/personal name: UserName
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_WebDav_Collection_Abstract::getChild::126 path: Filemanager/personal/UserName name: ._naamloze map 3
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_WebDav_Collection_Abstract::getChild::126 path: Filemanager name: personal
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_WebDav_Collection_Abstract::getChild::126 path: Filemanager/personal name: UserName
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_WebDav_Collection_Abstract::getChild::126 path: Filemanager/personal/UserName name: ._naamloze map 3
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Sabre_DAV_Server::exec::205 webdav exception Directory not found
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Sabre_DAV_Server::exec::207 webdav exception stacktrace #0 /var/www/crm/library/Sabre/DAV/ObjectTree.php(67): Tinebase_WebDav_Collection_Abstract-&gt;getChild(&#039;._naamloze map ...&#039;)
#1 /var/www/crm/library/Sabre/DAV/Server.php(1286): Sabre_DAV_ObjectTree-&gt;getNodeForPath(&#039;webdav/Filemana...&#039;)
#2 /var/www/crm/library/Sabre/DAV/Server.php(689): Sabre_DAV_Server-&gt;getPropertiesForPath(&#039;webdav/Filemana...&#039;, Array, 0)
#3 [internal function]: Sabre_DAV_Server-&gt;httpPropfind(&#039;webdav/Filemana...&#039;)
#4 /var/www/crm/library/Sabre/DAV/Server.php(454): call_user_func(Array, &#039;webdav/Filemana...&#039;)
#5 /var/www/crm/library/Sabre/DAV/Server.php(201): Sabre_DAV_Server-&gt;invokeMethod(&#039;PROPFIND&#039;, &#039;webdav/Filemana...&#039;)
#6 /var/www/crm/Tinebase/Server/WebDAV.php(126): Sabre_DAV_Server-&gt;exec()
#7 /var/www/crm/Tinebase/Core.php(230): Tinebase_Server_WebDAV-&gt;handle()
#8 /var/www/crm/index.php(17): Tinebase_Core::dispatchRequest()
#9 {main}
e9dab UserName - 2013-06-01T10:40:26+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::129 &gt;&gt;&gt; *DAV response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;
  &lt;s:exception&gt;Sabre_DAV_Exception_FileNotFound&lt;/s:exception&gt;
  &lt;s:message&gt;Directory not found&lt;/s:message&gt;
  &lt;s:sabredav-version&gt;1.5.4&lt;/s:sabredav-version&gt;
&lt;/d:error&gt;

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 4 Jun 2013 13:48**

hi Mattz,

i just checked this and could see all folders in /webdav/Filemanager/shared/

the logfile that you posted in https://forge.tine20.org/mantisbt/view.php?id=8398#c11210 shows the result for requestUri:/webdav/Filemanager/personal/UserName/._naamloze%20map%203 which is a personal folder.

could you please post the logfile when requesting  /webdav/Filemanager/shared/ ?

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 9 Aug 2013 12:19**

closing this (no feedback). please reopen if the error still occurs.
