### ISSUE TITLE
0008416:
json_encode(): Invalid UTF-8 sequence in argument

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#4233]
**Reported by weberho on 24 May 2013 13:02**

**Version:** Kristina (2013.03.4)

Occasionally I see the following message in the logs; I can&#039;t provide you with better information;

 9425b hph - 2013-05-24T11:57:53+00:00 WARN (4): Tinebase_Core::errorHandler::438 json_encode(): Invalid UTF-8 sequence in argument in /usr/share/tine20/library/Zen
d/Json.php::122 (2)
 9425b hph - 2013-05-24T11:57:53+00:00 WARN (4): Tinebase_Core::errorHandler::439 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;json_encode(): ...&#039;, &#039;/usr
/share/tine...&#039;, 122, Array)
#1 /usr/share/tine20/library/Zend/Json.php(122): json_encode(Array)
#2 /usr/share/tine20/Felamimail/Backend/Cache/Sql/Message.php(333): Zend_Json::encode(Array)
#3 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(814): Felamimail_Backend_Cache_Sql_Message-&gt;_recordToRawData(Object(Felamimail_Model_Message))
#4 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(890): Tinebase_Backend_Sql_Abstract-&gt;create(Object(Felamimail_Model_Message))
#5 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(833): Felamimail_Controller_Cache_Message-&gt;_addMessageToCache(Object(Felamimail_Model_Message))
#6 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(735): Felamimail_Controller_Cache_Message-&gt;addMessage(Array, Object(Felamimail_Model_Folder), false)
#7 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(709): Felamimail_Controller_Cache_Message-&gt;_addMessagesToCacheAndIncreaseCounters(Array, Object(Felamim
ail_Model_Folder))
#8 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(665): Felamimail_Controller_Cache_Message-&gt;_fetchAndAddMessages(Object(Felamimail_Model_Folder), Object
(Felamimail_Backend_ImapProxy))
#9 /usr/share/tine20/Felamimail/Controller/Cache/Message.php(270): Felamimail_Controller_Cache_Message-&gt;_addMessagesToCache(Object(Felamimail_Model_Folder), Object(
Felamimail_Backend_ImapProxy))
#10 /usr/share/tine20/Felamimail/Frontend/Json.php(175): Felamimail_Controller_Cache_Message-&gt;updateCache(&#039;e7e9f0db55e0dd9...&#039;, 120)
#11 [internal function]: Felamimail_Frontend_Json-&gt;updateMessageCache(&#039;e7e9f0db55e0dd9...&#039;, 120)
#12 /usr/share/tine20/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#13 /usr/share/tine20/Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#14 /usr/share/tine20/Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#15 /usr/share/tine20/Tinebase/Server/Json.php(231): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#16 /usr/share/tine20/Tinebase/Server/Json.php(101): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#17 /usr/share/tine20/Tinebase/Core.php(230): Tinebase_Server_Json-&gt;handle()
#18 /usr/share/tine20/index.php(17): Tinebase_Core::dispatchRequest()
#19 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Jun 2013 09:58**

add try/catch -&gt; log text with invalid charset
