### ISSUE TITLE
0008418:
Tinebase_Server_Json::_handleException::253 Tinebase_Exception_NotFound -> Folder FOLDERNAME not found.

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#4234]
**Reported by weberho on 24 May 2013 13:05**

**Version:** Kristina (2013.03.4)

Occasionally I see the following message in the logs; I can&#039;t provide better information;

 ee179 hph - 2013-05-24T12:04:55+00:00 WARN (4): Tinebase_Server_Json::_handleException::253 Tinebase_Exception_NotFound -&gt; Folder INBOX.Org.EDV.Passwort not found.
 ee179 hph - 2013-05-24T12:04:55+00:00 NOTICE (5): Tinebase_Server_Json::_logExceptionTrace::320 #0 .../Felamimail/Controller/Cache/Folder.php(186): Felamimail_Controller_Folder-&gt;getByBackendAndGlobalName(&#039;f837da599268443...&#039;, &#039;INBOX.Org.E...&#039;)
#1 .../Felamimail/Controller/Cache/Folder.php(95): Felamimail_Controller_Cache_Folder-&gt;_updateHasChildren(&#039;f837da599268443...&#039;, &#039;INBOX.Org.E...&#039;, 0)
#2 .../Felamimail/Controller/Folder.php(130): Felamimail_Controller_Cache_Folder-&gt;update(&#039;f837da599268443...&#039;, &#039;INBOX.Org.E...&#039;)
#3 .../Tinebase/Frontend/Json/Abstract.php(230): Felamimail_Controller_Folder-&gt;search(Object(Felamimail_Model_FolderFilter), Object(Tinebase_Model_Pagination), false)
#4 .../Felamimail/Frontend/Json.php(36): Tinebase_Frontend_Json_Abstract-&gt;_search(Array, &#039;&#039;, Object(Felamimail_Controller_Folder), &#039;Felamimail_Mode...&#039;)
#5 [internal function]: Felamimail_Frontend_Json-&gt;searchFolders(Array)
#6 .../library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#7 .../Zend/Json/Server.php(558): Zend_Server_Abstract-&gt;_dispatch(Object(Zend_Server_Method_Definition), Array)
#8 .../Zend/Json/Server.php(197): Zend_Json_Server-&gt;_handle()
#9 .../Tinebase/Server/Json.php(231): Zend_Json_Server-&gt;handle(Object(Zend_Json_Server_Request))
#10 .../Tinebase/Server/Json.php(101): Tinebase_Server_Json-&gt;_handle(Object(Zend_Json_Server_Request))
#11 .../Tinebase/Core.php(230): Tinebase_Server_Json-&gt;handle()
#12 .../index.php(17): Tinebase_Core::dispatchRequest()
#13 {main}

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 Jun 2013 10:30**

i think, we can put this into &quot;known bugs&quot;. this should not cause any problems.

but if you can get more information about how to reproduce the error, please post them here.

**Comment by Gloirin** [comment]
**Comment posted by weberho on 5 Sep 2014 15:15**

I do not longer see this issue (using version 2013-10-08). Might be closed.
