### ISSUE TITLE
0010221:
Updating fails due to conversion problem

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5102]
**Reported by kaystrobach on 10 Sep 2014 06:26**

**Version:** Collin (2013.10.8crowdfunding2)

I had a 2013.03.x version of tine20 and upgraded via the commandline, the update fails at this point:

php setup.php --update
Updated 13 application(s).
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_UnexpectedValue&#039; with message &#039;array is not a known rrule part&#039; in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php:165
Stack trace:
#0 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php(137): Calendar_Model_Rrule-&gt;setFromString(&#039;Array&#039;)
#1 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(599): Calendar_Model_Rrule-&gt;__construct(&#039;Array&#039;, true, true)
#2 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Record/Abstract.php(246): Calendar_Model_Event-&gt;setFromArray(Array)
#3 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(222): Tinebase_Record_Abstract-&gt;__construct(Array, true, true)
#4 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Backend/Sql/Abstract.php(303): Calendar_Model_Event-&gt;__construct(Array, true)
#5 /is/htdocs/w in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php on line 165

Fatal error: Uncaught exception &#039;Tinebase_Exception_UnexpectedValue&#039; with message &#039;array is not a known rrule part&#039; in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php:165
Stack trace:
#0 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php(137): Calendar_Model_Rrule-&gt;setFromString(&#039;Array&#039;)
#1 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(599): Calendar_Model_Rrule-&gt;__construct(&#039;Array&#039;, true, true)
#2 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Record/Abstract.php(246): Calendar_Model_Event-&gt;setFromArray(Array)
#3 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(222): Tinebase_Record_Abstract-&gt;__construct(Array, true, true)
#4 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Backend/Sql/Abstract.php(303): Calendar_Model_Event-&gt;__construct(Array, true)
#5 /is/htdocs/w in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php on line 165
ftp1049038@vwp1507:~/http/de.drk-dresden./intern-apps-tine20$ php setup.php --update
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_UnexpectedValue&#039; with message &#039;array is not a known rrule part&#039; in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php:165
Stack trace:
#0 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php(137): Calendar_Model_Rrule-&gt;setFromString(&#039;Array&#039;)
#1 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(599): Calendar_Model_Rrule-&gt;__construct(&#039;Array&#039;, true, true)
#2 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Record/Abstract.php(246): Calendar_Model_Event-&gt;setFromArray(Array)
#3 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(222): Tinebase_Record_Abstract-&gt;__construct(Array, true, true)
#4 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Backend/Sql/Abstract.php(303): Calendar_Model_Event-&gt;__construct(Array, true)
#5 /is/htdocs/w in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php on line 165

Fatal error: Uncaught exception &#039;Tinebase_Exception_UnexpectedValue&#039; with message &#039;array is not a known rrule part&#039; in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php:165
Stack trace:
#0 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php(137): Calendar_Model_Rrule-&gt;setFromString(&#039;Array&#039;)
#1 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(599): Calendar_Model_Rrule-&gt;__construct(&#039;Array&#039;, true, true)
#2 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Record/Abstract.php(246): Calendar_Model_Event-&gt;setFromArray(Array)
#3 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(222): Tinebase_Record_Abstract-&gt;__construct(Array, true, true)
#4 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Backend/Sql/Abstract.php(303): Calendar_Model_Event-&gt;__construct(Array, true)
#5 /is/htdocs/w in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php on line 165
ftp1049038@vwp1507:~/http/de.drk-dresden./intern-apps-tine20$ php setup.php --update
PHP Fatal error:  Uncaught exception &#039;Tinebase_Exception_UnexpectedValue&#039; with message &#039;array is not a known rrule part&#039; in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php:165
Stack trace:
#0 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php(137): Calendar_Model_Rrule-&gt;setFromString(&#039;Array&#039;)
#1 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(599): Calendar_Model_Rrule-&gt;__construct(&#039;Array&#039;, true, true)
#2 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Record/Abstract.php(246): Calendar_Model_Event-&gt;setFromArray(Array)
#3 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(222): Tinebase_Record_Abstract-&gt;__construct(Array, true, true)
#4 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Backend/Sql/Abstract.php(303): Calendar_Model_Event-&gt;__construct(Array, true)
#5 /is/htdocs/w in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php on line 165

Fatal error: Uncaught exception &#039;Tinebase_Exception_UnexpectedValue&#039; with message &#039;array is not a known rrule part&#039; in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php:165
Stack trace:
#0 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php(137): Calendar_Model_Rrule-&gt;setFromString(&#039;Array&#039;)
#1 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(599): Calendar_Model_Rrule-&gt;__construct(&#039;Array&#039;, true, true)
#2 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Record/Abstract.php(246): Calendar_Model_Event-&gt;setFromArray(Array)
#3 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Event.php(222): Tinebase_Record_Abstract-&gt;__construct(Array, true, true)
#4 /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Tinebase/Backend/Sql/Abstract.php(303): Calendar_Model_Event-&gt;__construct(Array, true)
#5 /is/htdocs/w in /is/htdocs/wp1049038_AA3JTHW1F3/http/de.drk-dresden./intern-apps-tine20/Calendar/Model/Rrule.php on line 165

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 10 Sep 2014 14:24**

hi Kay,

thanks for reporting, I&#039;ll have a look at this asap.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 11 Sep 2014 11:43**

hi Kay, seems to be a strange event / rrule. could you please give us the event / full debug log of the update process?

as a workaround, you could skip the update step by increasing the calendar app version by one in the database (tine20_applications).

**Comment by Gloirin** [comment]
**Comment posted by kaystrobach on 12 Sep 2014 15:23**

i will try to do so, i rolled back the update to keep my environment running, by reimporting the backup database ... ;)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 13 Oct 2014 15:38**

we just created a fix for this problem.

I&#039;ll add an updated Calendar/Setup/Update/Release8.php file.
