### ISSUE TITLE
0011834:
What value required for Country in VCard

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5855]
**Reported by nothere on 5 May 2016 11:10**

**Version:** Egon Community Edition (2016.03.2)

I&#039;m sure it is just something missing in my Evolution&lt;-&gt;Tine20 converter

But when i do set the country field in the VCARD and assing that in the converter to adr_one_countryname and adr_two_countryname i do get a zend locale ERROR that it doesn&#039;T find the locale. 

What line do i have to add to the Evolution.php converter to get the proper country name avoiding the error:

3a212 christoph - 2016-05-05T10:11:18+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::653 #0 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Locale.php(1539): Zend_Locale::findLocale(&#039;UNITED KINGDOM&#039;)
#1 /usr/share/tine20/Addressbook/Controller/Contact.php(389): Zend_Locale::getTranslation(&#039;UNITED KINGDOM&#039;, &#039;Country&#039;, &#039;UNITED KINGDOM&#039;)
#2 /usr/share/tine20/Addressbook/Controller/Contact.php(509): Addressbook_Controller_Contact-&gt;_setGeoDataForAddress(&#039;adr_one_&#039;, Object(Addressbook_Model_Contact))
#3 /usr/share/tine20/Addressbook/Controller/Contact.php(303): Addressbook_Controller_Contact-&gt;_setGeoData(Object(Addressbook_Model_Contact))
#4 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(613): Addressbook_Controller_Contact-&gt;_inspectBeforeCreate(Object(Addressbook_Model_Contact))
#5 /usr/share/tine20/Addressbook/Frontend/WebDAV/Contact.php(84): Tinebase_Controller_Record_Abstract-&gt;create(Object(Addressbook_Model_Contact), false)
#6 /usr/share/tine20/Tinebase/WebDav/Container/Abstract.php(66): Addressbook_Frontend_WebDAV_Contact::create(Object(Tinebase_Model_Container), &#039;46F7751D-4D56DA...&#039;, &#039;BEGIN:VCARD??VE...&#039;)
#7 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1647): Tinebase_WebDav_Container_Abstract-&gt;createFile(&#039;46F7751D-4D56DA...&#039;, &#039;BEGIN:VCARD??VE...&#039;)
#8 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(900): Sabre\DAV\Server-&gt;createFile(&#039;addressbooks/9c...&#039;, Resource id #37, NULL)
#9 [internal function]: Sabre\DAV\Server-&gt;httpPut(&#039;addressbooks/9c...&#039;)
#10 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;addressbooks/9c...&#039;)
#11 /usr/share/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;PUT&#039;, &#039;addressbooks/9c...&#039;)
#12 /usr/share/tine20/Tinebase/Server/WebDAV.php(146): Sabre\DAV\Server-&gt;exec()
#13 /usr/share/tine20/Tinebase/Core.php(229): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#14 /usr/share/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#15 {main}
275e5 -- none -- - 2016-05-05T10:12:01+00:00 INFO (6): Tinebase_Core::setupLogger::660 Logger initialized

I also tried with uk and GB and Great Britain

The same error. The examples i found on google about ZendLocale were not conclusive to me.

Can you help

**Comment by Gloirin** [comment]
**Comment posted by nothere on 5 May 2016 12:29**

As i assumed it is not a bug. Aggr

It is an evolution annoyance and ignorance. It allows to enter any string to Country field. It neither provides the option to switch between country name and code nor does it parse the content and complain when it does not fit the name known in the user locale on the client. It just sends what i entered in the country field. 

The questions is now should i add a normalize function which tries to translate the country code e.g. GB for great britain to the appropriate code and throws an error in case it neither can verify the code nor translate it.
