### ISSUE TITLE
0011850:
Error in timezone CET

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5863]
**Reported by ingoratsdorf on 12 May 2016 09:04**

**Version:** git master

I seem to be having an event in CET that fails to convert:
TimeZoneConvert.php(69): TimeZoneConvert_VTimeZone-&gt;getVTimezone(&#039;CET&#039;, NULL, NULL)
array_shift() expects parameter 1 to be array, boolean given in /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/Transition.php

**Steps to reproduce:** Sunc to calDAV client

**Additional information:** 7ee6b user - 2016-05-12T06:51:06+00:00 WARN (4): Tinebase_Core::errorHandler::544 array_shift() expects parameter 1 to be array, boolean given in /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/Transition.php::127 (2)
7ee6b user - 2016-05-12T06:51:06+00:00 WARN (4): Tinebase_Core::errorHandler::545 #0 [internal function]: Tinebase_Core::errorHandler(2, &#039;array_shift() e...&#039;, &#039;/var/wwwroot/ti...&#039;, 127, Array)
#1 /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/Transition.php(127): array_shift(false)
#2 /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/VTimeZone.php(67): TimeZoneConvert_Transition::getTransitions(Object(DateTimeZone), Object(DateTime), NULL)
#3 /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert.php(69): TimeZoneConvert_VTimeZone-&gt;getVTimezone(&#039;CET&#039;, NULL, NULL)
#4 /var/wwwroot/tine20/library/Sabre/VObject/Component/VTimezone.php(56): TimeZoneConvert::toVTimeZone(Object(DateTimeZone))
#5 /var/wwwroot/tine20/vendor/sabre/vobject/lib/Sabre/VObject/Component.php(284): Sabre_VObject_Component_VTimezone-&gt;serialize()
#6 /var/wwwroot/tine20/Calendar/Frontend/WebDAV/Event.php(629): Sabre\VObject\Component-&gt;serialize()
#7 /var/wwwroot/tine20/Calendar/Frontend/WebDAV/Event.php(290): Calendar_Frontend_WebDAV_Event-&gt;_getVEvent()
#8 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/CalDAV/Plugin.php(437): Calendar_Frontend_WebDAV_Event-&gt;get()
#9 [internal function]: Sabre\CalDAV\Plugin-&gt;beforeGetProperties(&#039;calendars/c2134...&#039;, Object(Calendar_Frontend_WebDAV_Event), Array, Array)
#10 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#11 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1519): Sabre\DAV\Server-&gt;broadcastEvent(&#039;beforeGetProper...&#039;, Array)
#12 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/CalDAV/Plugin.php(492): Sabre\DAV\Server-&gt;getPropertiesForPath(&#039;calendars/c2134...&#039;, Array)
#13 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/CalDAV/Plugin.php(262): Sabre\CalDAV\Plugin-&gt;calendarMultiGetReport(Object(DOMDocument))
#14 [internal function]: Sabre\CalDAV\Plugin-&gt;report(&#039;{urn:ietf:param...&#039;, Object(DOMDocument), &#039;calendars/c2134...&#039;)
#15 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#16 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1066): Sabre\DAV\Server-&gt;broadcastEvent(&#039;report&#039;, Array)
#17 [internal function]: Sabre\DAV\Server-&gt;httpReport(&#039;calendars/c2134...&#039;)
#18 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;calendars/c2134...&#039;)
#19 /var/wwwroot/tine20/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;REPORT&#039;, &#039;calendars/c2134...&#039;)
#20 /var/wwwroot/tine20/Tinebase/Server/WebDAV.php(146): Sabre\DAV\Server-&gt;exec()
#21 /var/wwwroot/tine20/Tinebase/Core.php(229): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#22 /var/wwwroot/tine20/index.php(18): Tinebase_Core::dispatchRequest()
#23 {main}

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Jun 2016 10:45**

I am having the same issue plus I am getting the same errors for a timezone called &quot;ANAT&quot; (http://www.timeanddate.com/time/zones/anat) which some Android Exchange client seem to be using for &quot;Pacific/Auckland&quot;, same TZ offset UTC+12.
Can those be added to the mapping tables? And if so, where? Maybe at &quot;vendor\metaways\timezoneconvert\lib\TimeZoneConvert\KnownNamesMap.php&quot; ?

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 13 Jun 2016 11:13**

Some observation here:

#4 /var/wwwroot/tine20/library/Sabre/VObject/Component/VTimezone.php(56): TimeZoneConvert::toVTimeZone(Object(DateTimeZone))
Gets tzId of DateTimeZone =&gt; CET
Creates converter and calls it: $converter-&gt;getVTimezone($tzid[&#039;CET&#039;], $from[null], $until[null]);

#3 /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert.php(69): TimeZoneConvert_VTimeZone-&gt;getVTimezone(&#039;CET&#039;, NULL, NULL)
        $VTimeZone  = &#039;BEGIN:VTIMEZONE&#039; . self::EOL;
        $VTimeZone .= &#039;TZID:&#039; . $tzid . self::EOL;
// starts the VTIMEZONE with TZID-CET??????        

        $from = $from ?: date_create(&#039;now&#039;, new DateTimeZone(&#039;UTC&#039;));
//creates a proper FROM as this was NULL
        
        $timezone = new DateTimeZone($tzid);
        $transitions = TimeZoneConvert_Transition::getTransitions($timezone, $from, $until);
// calls getTransitions with ($timezone, $from, NULL)
// we still have not set the $until parameter

#2 /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/VTimeZone.php(67): TimeZoneConvert_Transition::getTransitions(Object(DateTimeZone), Object(DateTime), NULL)

        $timezone = $tzid instanceof DateTimeZone ? $tzid : new DateTimeZone($tzid);
        $beginTS = $from instanceof DateTime ? $from-&gt;getTimestamp() : $from;
        $endTS = $until instanceof DateTime ? $until-&gt;getTimestamp() : $until;
//$timezone is correct, so we assume, despite of the use of &#039;CET&#039;
//$beginTS has been set by previous function to NOW in UTC
//$endTS is still NULL

        $transitions = $endTS ? $timezone-&gt;getTransitions(--$beginTS, $endTS) : $timezone-&gt;getTransitions(--$beginTS);

// now we call $timezone-&gt;getTransitions(--$beginTS) as $endTS is NULL
//however this seem to be returning FALSE for $transitions

because the next call fails

        array_shift($transitions);

#1 /var/wwwroot/tine20/vendor/metaways/timezoneconvert/lib/TimeZoneConvert/Transition.php(127): array_shift(false)

**Comment by Gloirin** [comment]
**Comment posted by ingoratsdorf on 14 Jun 2016 08:51**

If you run this in PHP, you&#039;ll find out that timezones such as &quot;CET&quot; and &quot;ANAT&quot; return a valid DateTimeZone object, however the type will be 2, not 3.

Example:

DateTimeZone Object
(
    [timezone_type] =&gt; 3
    [timezone] =&gt; Pacific/Auckland
)

DateTimeZone Object
(
    [timezone_type] =&gt; 2
    [timezone] =&gt; ANAT
)

DateTimeZone Object
(
    [timezone_type] =&gt; 2
    [timezone] =&gt; CET
)

For all type 2 DateTimeZone, a call of getTransitions returns FALSE, ie no transitions are available.
A subsequent call of array_shift generates an error.

Also note the remarks for http://php.net/manual/en/class.datetimezone.php:

&quot;It seems like as of PHP 5.5, creating a new DateTimeZone with a string like &#039;EDT&#039; will cause DateTimeZone::getName() to return &#039;EDT&#039; whereas prior to 5.5 it would convert it would have returned &#039;America/New_York&#039;
This is of particular note when using a DateTimeZone object to change the timezone on a DateTime object.  Using a DateTimeZone object when set as shown above will cause the conversion to be wrong without throwing any errors.&quot;

So DateTimeZone is _NOT_ converting those type 2 timezones any more.

Also I found this:

Timezones can be one of three different types in DateTime objects:

Type 1; A UTC offset, such as in new DateTime(&quot;17 July 2013 -0300&quot;);
Type 2; A timezone abbreviation, such as in new DateTime(&quot;17 July 2013 GMT&quot;);
Type 3: A timezone identifier, such as in new DateTime( &quot;17 July 2013&quot;, new DateTimeZone(&quot;Europe/London&quot;));

Only DateTime objects with type 3 timezones attached will allow for DST correctly.

The following will catch all timezone abbreviations if know to PHP and convert them to correct timezone names:

$tzid = &#039;Pacific/Auckland&#039;;
$from = null;
$until = null;

$beginTS = $from instanceof DateTime ? $from-&gt;getTimestamp() : $from;
$endTS = $until instanceof DateTime ? $until-&gt;getTimestamp() : $until;

try {
        $timezone = null;
        if ($tzid) {
                if (!strpos($tzid, &quot;/&quot;)) {
                        $timezone = new DateTimeZone(timezone_name_from_abbr($tzid));
                } else {
                        $timezone = $tzid instanceof DateTimeZone ? $tzid : new DateTimeZone($tzid);
                }
        }
} catch(Exception $e) {
        echo &quot;Error creating timezone!&quot;;
}

$transitions = $endTS ? $timezone-&gt;getTransitions($beginTS, $endTS) : $timezone-&gt;getTransitions($beginTS);
