### ISSUE TITLE
0011858:
renamed fields might break concurrent update

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5867]
**Reported by pschuele on 12 May 2016 16:05**

**Version:** Elena Business Edition (2015.11.7)

renamed fields might break concurrent update

for example:

the field price in Sales Products has been renamed to salesprice. if there is a modlog record with price that is to be merged, this breaks.

**Additional information:** xxx - 2016-05-11T17:41:16+00:00 INFO (6): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::645 price is no property of $this-&gt;_properties
xxx - 2016-05-11T17:41:16+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_handleRecordCreateOrUpdateException::646 #0 Tinebase/Record/Abstract.php(863): Tinebase_Record_Abstract-&gt;__set(&#039;price&#039;, &#039;46900&#039;)
#1 Tinebase/Timemachine/ModificationLog.php(491): Tinebase_Record_Abstract-&gt;offsetSet(&#039;price&#039;, &#039;46900&#039;)
#2 Tinebase/Timemachine/ModificationLog.php(456): Tinebase_Timemachine_ModificationLog-&gt;_resolveScalarMergeUpdate(Object(Sales_Model_Product), Object(Tinebase_Model_ModificationLog))
#3 Tinebase/Timemachine/ModificationLog.php(431): Tinebase_Timemachine_ModificationLog-&gt;_resolveDiffs(Object(Tinebase_Record_RecordSet), Object(Tinebase_Record_RecordSet), Object(Sales_Model_Product))
#4 Tinebase/Controller/Record/Abstract.php(985): Tinebase_Timemachine_ModificationLog-&gt;manageConcurrentUpdates(&#039;192f4cb1d6a8ba2...&#039;, Object(Sales_Model_Product), Object(Sales_Model_Product))
#5 Tinebase/Controller/Record/Abstract.php(899): Tinebase_Controller_Record_Abstract-&gt;_concurrencyManagement(Object(Sales_Model_Product), Object(Sales_Model_Product))
#6 Tinebase/Relations.php(499): Tinebase_Controller_Record_Abstract-&gt;update(Object(Sales_Model_Product), false)

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 12 May 2016 16:07**

http://gerrit.tine20.com/customers/3154
