### ISSUE TITLE
0011970:
webpack problem

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#5923]
**Reported by fvisic on 26 Jun 2016 11:36**

**Version:** git master

Reading on this link https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack 
I have same error on windows and linux using on step for &quot;webpack-dev-server --inline&quot;

**Steps to reproduce:** 
c:\Users\fvisic\git\tine20\tine20&gt;webpack-dev-server --inline
C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\NormalModuleFactory.js:72
                        var elements = request.replace(/^-?!+/, &quot;&quot;).replace(/!!+/g, &quot;!&quot;).split(&quot;!&quot;);
                                              ^

TypeError: Cannot read property &#039;replace&#039; of undefined
    at C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\NormalModuleFactory.js:72:26
    at C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\NormalModuleFactory.js:28:4
    at C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\tapable\lib\Tapable.js:75:69)
    at NormalModuleFactory.create (C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\NormalModuleFactory.js:144:8)
    at C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:214:11
    at C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\node_modules\async\lib\async.js:209:22)
    at Compilation.addModuleDependencies (C:\Users\fvisic\AppData\Roaming\npm\node_modules\webpack-dev-server\node_modules\webpack\lib\Compilation.js:185:8)

fvisic@ubuntu:/var/www/html/tine20/tine20/Tinebase$ sudo webpack-dev-server --inline
/usr/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModuleFactory.js:72
                        var elements = request.replace(/^-?!+/, &quot;&quot;).replace(/!!+/g, &quot;!&quot;).split(&quot;!&quot;);
                                              ^

TypeError: Cannot read property &#039;replace&#039; of undefined
    at /usr/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModuleFactory.js:72:26
    at /usr/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModuleFactory.js:28:4
    at /usr/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/usr/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (/usr/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/NormalModuleFactory.js:144:8)
    at /usr/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:214:11
    at /usr/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/usr/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/usr/lib/node_modules/webpack-dev-server/node_modules/webpack/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/usr/lib/node_modules/webpack-dev-server/node_modules/webpack/lib/Compilation.js:185:8)

**Comment by Gloirin** [comment]
**Comment posted by lab-at-nohl on 26 Jun 2016 16:15**

I&#039;m not sure if it is relevant to your error but you have to change directory before starting your server. 

From wiki: cd Tinebase/js

Regards 
Johannes

**Comment by Gloirin** [comment]
**Comment posted by fvisic on 27 Jun 2016 07:39**

After this
sudo npm install -g webpack
sudo npm install -g webpack-dev-server
i got this error

fvisic@ubuntu:/var/www/html/tine20/tine20/Tinebase/js$ sudo webpack-dev-server --inline
module.js:327
    throw err;
    ^

Error: Cannot find module &#039;unminified-webpack-plugin&#039;
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.&lt;anonymous&gt; (/var/www/html/tine20/tine20/Tinebase/js/webpack.config.js:2:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
fvisic@ubuntu:/var/www/html/tine20/tine20/Tinebase/js$ npm install unminified-webpack-plugin
unminified-webpack-plugin@1.1.0 node_modules/unminified-webpack-plugin
fvisic@ubuntu:/var/www/html/tine20/tine20/Tinebase/js$ sudo webpack-dev-server --inline
http://localhost:10443/
webpack result is served from /
content is served from /var/www/html/tine20/tine20/Tinebase/js
Hash: 0be3822fac35d367fe63
Version: webpack 1.13.1
Time: 2587ms

so I added this
sudo npm install unminified-webpack-plugin

but after all I still get 6 error
.....
   [46] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/version.js 26 bytes {0} [built]
   [47] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/utils/iframe.js 5.06 kB {0} [built]
   [48] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
   [49] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
   [50] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
   [51] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
   [52] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
   [53] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
   [54] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
   [55] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
   [56] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/main.js 11.9 kB {0} [built]
   [57] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/shims.js 18.2 kB {0} [built]
   [58] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/utils/escape.js 2.31 kB {0} [built]
   [59] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
   [60] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
   [61] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/event/event.js 477 bytes {0} [built]
   [62] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/location.js 177 bytes {0} [built]
   [63] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/event/close.js 295 bytes {0} [built]
   [64] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
   [65] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
   [66] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
   [67] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
   [68] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
   [69] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
   [70] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
   [71] /usr/lib/~/webpack-dev-server/~/sockjs-client/lib/facade.js 723 bytes {0} [built]
   [72] /usr/lib/~/webpack-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
   [73] /usr/lib/~/webpack-dev-server/~/strip-ansi/~/ansi-regex/index.js 135 bytes {0} [built]
   [74] ./Tinebase.js 593 bytes {0} [built] [6 errors]

ERROR in ./Tinebase.js
Module not found: Error: Cannot resolve module &#039;lodash&#039; in /var/www/html/tine20/tine20/Tinebase/js
 @ ./Tinebase.js 14:13-30

ERROR in ./Tinebase.js
Module not found: Error: Cannot resolve module &#039;postal&#039; in /var/www/html/tine20/tine20/Tinebase/js
 @ ./Tinebase.js 15:13-30

ERROR in ./Tinebase.js
Module not found: Error: Cannot resolve module &#039;postal.federation&#039; in /var/www/html/tine20/tine20/Tinebase/js
 @ ./Tinebase.js 16:0-28

ERROR in ./Tinebase.js
Module not found: Error: Cannot resolve module &#039;postal.xwindow&#039; in /var/www/html/tine20/tine20/Tinebase/js
 @ ./Tinebase.js 17:0-25

ERROR in ./Tinebase.js
Module not found: Error: Cannot resolve module &#039;postal.request-response&#039; in /var/www/html/tine20/tine20/Tinebase/js
 @ ./Tinebase.js 18:0-34

ERROR in ./Tinebase.js
Module not found: Error: Cannot resolve module &#039;html2canvas&#039; in /var/www/html/tine20/tine20/Tinebase/js
 @ ./Tinebase.js 19:18-40
webpack: bundle is now VALID.

**Comment by Gloirin** [comment]
**Comment posted by fvisic on 27 Jun 2016 07:45**

Please add this in wiki

sudo npm install unminified-webpack-plugin
sudo npm install lodash
sudo npm install postal
sudo npm install postal.federation
sudo npm install postal.xwindow
sudo npm install postal.request-response 
sudo npm install html2canvas

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 27 Jun 2016 08:14**

it is only required to run

$ npm install

once (in Tinebase/js). that installs all (npm managed) tine20 requirements that are defined in packages.json. I added this to the wiki as well.

**Comment by tvannahl** [comment]
I included `npm install` in the [Development Wiki](https://github.com/tine20/tine20/wiki/EN%3ADevelopment-Setup). Now I am reading:

```
root@crash-test-dummy:/var/www/html/Tinebase/js [HEAD] # ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --progress --watch --inline -d --host 0.0.0.0 --public `hostname` webpack-dev-includes.js 
 10% building modules 1/1 modules 0 active                                         
Project is running at http://crash-test-dummy.erk.sowiwas.de/
webpack output is served from /
Hash: 4e59c182a8fa2ab6ee8a                                                           
Version: webpack 3.10.0
Time: 516ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  857 kB       0  [emitted]  [big]  main
   [2] multi (webpack)-dev-server/client?http://crash-test-dummy.erk.sowiwas.de ./webpack-dev-includes.js 40 bytes {0} [built]
   [3] (webpack)-dev-server/client?http://crash-test-dummy.erk.sowiwas.de 7.95 kB {0} [built]
   [4] ./node_modules/url/url.js 23.3 kB {0} [built]
   [7] ./node_modules/url/util.js 314 bytes {0} [built]
   [8] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
  [11] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [12] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
  [13] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
  [14] (webpack)-dev-server/client/socket.js 1.05 kB {0} [built]
  [15] ./node_modules/sockjs-client/dist/sockjs.js 181 kB {0} [built]
  [16] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
  [18] ./node_modules/html-entities/index.js 231 bytes {0} [built]
  [21] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [23] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [25] ./webpack-dev-includes.js 737 bytes {0} [built]
    + 11 hidden modules

ERROR in ./webpack-dev-includes.js
Module not found: Error: Can't resolve './webpack.config.js' in '/opt/tine20/tine20/Tinebase/js'
 @ ./webpack-dev-includes.js 18:13-43
 @ multi (webpack)-dev-server/client?http://crash-test-dummy.erk.sowiwas.de ./webpack-dev-includes.js
webpack: Failed to compile.
```

Please not that I appended `webpack-dev-includes.js` because I thought that this is maybe the required file for webpack. I was unable to find a file *webpack.config.js* that is directly related to the tine using commit bb40100ee5d6bed3fb2813b88bdb54468c00ecd0 (2018.08.1 tag point).

**Comment by pschuele** [comment]
ah, i think the dev wiki page might be outdated.
we use this command to start webpack (from Tinebase/js):
```
npm start
```
see https://github.com/tine20/tine20/blob/12b0c8d2524a56210fceff7c196df9e06b76ab12/tine20/Tinebase/js/package.json#L6

**Comment by DanielRuf** [comment]
Is this still relevant?

In general `sudo` should never be used and the packages should be installed locally.

**Comment by pschuele** [comment]
i think, this can be closed.
