### ISSUE TITLE
0013708:
Hidden groups break webdav due to missing

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6780]
**Reported by lab-at-nohl on 21 Jan 2018 02:11**

**Version:** 2017.08.11 Community Edition

If user is member of a group which has set visibility to &quot;do not show in address book&quot; calDAV folder detection breaks (curiosity: you would rather expect cardDAV to be affected, but it isn&#039;t). 

**Steps to reproduce:** Try to add new account with davdroid on Android. Switch visibility on or off. 

**Additional information:** 4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1165 given localeString &#039;auto&#039;
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1192 Try to detect the locale of the user (browser, environment, default)
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString &#039;auto&#039;
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Translation::getLocale::211 &#039;de_DE&#039; is not supported, checking fallback
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Translation::getLocale::237 selected locale: &#039;de&#039;
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1206 Saving locale: de
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Preference_Abstract::setValueForUser::481 Updated: locale for user 3173a20e-6c19-1034-948b-17a0cca20f00 -&gt; de
4e91b testuser - 2018-01-21T01:59:13+00:00 INFO (6): Tinebase_Core::setupUserLocale::1216 Setting user locale: de
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Preference_Abstract::getValueForUser::287 Get value for timezone of account id 3173a20e-6c19-1034-948b-17a0cca20f00 / user
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Core::setupUserTimezone::1265 User timezone: Europe/Berlin
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::117 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
4e91b testuser - 2018-01-21T01:59:13+00:00 INFO (6): Tinebase_Server_WebDAV::handle::97 Starting to handle WebDAV request (requestUri:/principals/users/74/ PID: 11654)
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::108 headers: Array
(
    [accept-language] =&gt; de-DE, de;q=0.7, *;q=0.5
    [user-agent] =&gt; DAVdroid/1.9.7-ose (2017/12/24; dav4android; okhttp3) Android/7.1.1
    [accept-encoding] =&gt; gzip
    [connection] =&gt; Keep-Alive
    [host] =&gt; testtine.de
    [content-length] =&gt; 360
    [content-type] =&gt; application/xml; charset=utf-8
    [depth] =&gt; 0
)

4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::111 requestContentType: application/xml; charset=utf-8 requestMethod: PROPFIND
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::120 &lt;&lt;&lt; *DAV request
&lt;?xml version=&#039;1.0&#039; encoding=&#039;UTF-8&#039; ?&gt;&lt;propfind xmlns=&quot;DAV:&quot; xmlns:CAL=&quot;urn:ietf:params:xml:ns:caldav&quot; xmlns:CARD=&quot;urn:ietf:params:xml:ns:carddav&quot;&gt;&lt;prop&gt;&lt;CAL:calendar-home-set /&gt;&lt;n0:calendar-proxy-read-for xmlns:n0=&quot;http://calendarserver.org/ns/&quot; /&gt;&lt;n1:calendar-proxy-write-for xmlns:n1=&quot;http://calendarserver.org/ns/&quot; /&gt;&lt;group-membership /&gt;&lt;/prop&gt;&lt;/propfind&gt;
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::178 SyncTokenSupport enabled
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::2086 Force a standard containerFilter (specialNode = all) as ACL filter.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::400 Using application name is deprecated. Please use the classname of the model or the class itself.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::getContainerByACL::459 app: Addressbook / account: testuser / grant:readGrant/adminGrant
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Addressbook_Model_ContactHiddenFilter::appendFilterSql::41 Query account contacts (hide if status = disabled)
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::245 Got 1 search results of Addressbook_Model_Contact
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::2086 Force a standard containerFilter (specialNode = all) as ACL filter.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::400 Using application name is deprecated. Please use the classname of the model or the class itself.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::getContainerByACL::459 app: Addressbook / account: testuser / grant:readGrant/adminGrant
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::245 Got 1 search results of Addressbook_Model_List
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::2086 Force a standard containerFilter (specialNode = all) as ACL filter.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::400 Using application name is deprecated. Please use the classname of the model or the class itself.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::getContainerByACL::459 app: Addressbook / account: testuser / grant:readGrant/adminGrant
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Addressbook_Model_ContactHiddenFilter::appendFilterSql::41 Query account contacts (hide if status = disabled)
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::245 Got 18 search results of Addressbook_Model_Contact
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Addressbook_Controller_List::_removeHiddenListMembers::135 Found 6 hidden members, removing them
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::2086 Force a standard containerFilter (specialNode = all) as ACL filter.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::400 Using application name is deprecated. Please use the classname of the model or the class itself.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::getContainerByACL::459 app: Addressbook / account: testuser / grant:readGrant/adminGrant
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::245 Got 0 search results of Addressbook_Model_List
4e91b testuser - 2018-01-21T01:59:13+00:00 NOTICE (5): Tinebase_WebDav_PrincipalBackend::getPrincipalByPath::176 Group/list principal does not exist: e3524b6e4842f4cd764076d058bdbedea66caa19
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::checkFilterACL::2086 Force a standard containerFilter (specialNode = all) as ACL filter.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::_resolveRecordClassArgument::400 Using application name is deprecated. Please use the classname of the model or the class itself.
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Container::getContainerByACL::459 app: Addressbook / account: testuser / grant:readGrant/adminGrant
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::245 Got 0 search results of Addressbook_Model_List
4e91b testuser - 2018-01-21T01:59:13+00:00 NOTICE (5): Tinebase_WebDav_PrincipalBackend::getPrincipalByPath::176 Group/list principal does not exist: e3524b6e4842f4cd764076d058bdbedea66caa19
4e91b testuser - 2018-01-21T01:59:13+00:00 DEBUG (7): Tinebase_Server_WebDAV::handle::199 &gt;&gt;&gt; *DAV response:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
&lt;d:error xmlns:d=&quot;DAV:&quot; xmlns:s=&quot;http://sabredav.org/ns&quot;&gt;
  &lt;s:exception&gt;Sabre\DAV\Exception\NotFound&lt;/s:exception&gt;
  &lt;s:message&gt;Principal with name e3524b6e4842f4cd764076d058bdbedea66caa19 not found&lt;/s:message&gt;
  &lt;s:file&gt;/srv/vendor/sabre/dav/lib/Sabre/DAVACL/AbstractPrincipalCollection.php&lt;/s:file&gt;
  &lt;s:line&gt;116&lt;/s:line&gt;
  &lt;s:code&gt;0&lt;/s:code&gt;
  &lt;s:stacktrace&gt;#0 /srv/vendor/sabre/dav/lib/Sabre/DAV/ObjectTree.php(72): Sabre\DAVACL\AbstractPrincipalCollection-&gt;getChild(&#039;e3524b6e4842f4c...&#039;)
#1 /srv/vendor/sabre/dav/lib/Sabre/CalDAV/Plugin.php(380): Sabre\DAV\ObjectTree-&gt;getNodeForPath(&#039;principals/grou...&#039;)
#2 [internal function]: Sabre\CalDAV\Plugin-&gt;beforeGetProperties(&#039;principals/user...&#039;, Object(Tinebase_WebDav_Principal), Array, Array)
#3 /srv/vendor/sabre/dav/lib/Sabre/DAV/Server.php(433): call_user_func_array(Array, Array)
#4 /srv/vendor/sabre/dav/lib/Sabre/DAV/Server.php(1519): Sabre\DAV\Server-&gt;broadcastEvent(&#039;beforeGetProper...&#039;, Array)
#5 /srv/vendor/sabre/dav/lib/Sabre/DAV/Server.php(723): Sabre\DAV\Server-&gt;getPropertiesForPath(&#039;principals/user...&#039;, Array, 0)
#6 [internal function]: Sabre\DAV\Server-&gt;httpPropfind(&#039;principals/user...&#039;)
#7 /srv/vendor/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, &#039;principals/user...&#039;)
#8 /srv/vendor/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\DAV\Server-&gt;invokeMethod(&#039;PROPFIND&#039;, &#039;principals/user...&#039;)
#9 /srv/Tinebase/Server/WebDAV.php(196): Sabre\DAV\Server-&gt;exec()
#10 /srv/Tinebase/Core.php(260): Tinebase_Server_WebDAV-&gt;handle(Object(Zend\Http\PhpEnvironment\Request))
#11 /srv/index.php(24): Tinebase_Core::dispatchRequest()
#12 {main}&lt;/s:stacktrace&gt;
&lt;/d:error&gt;

4e91b testuser - 2018-01-21T01:59:13+00:00 INFO (6): index.php (31) METHOD: Tinebase_Server_WebDAV::PROPFIND / TIME: 589ms /  Memory usage: 2 MB /  Real patch cache size: 144114 / PID: 11654

**Comment by Gloirin** [comment]
Related to #6819

**Comment by Gloirin** [comment]
**Comment posted by shochdoerfer on 23 Mar 2018 08:11**

Maybe some logic was changed to read the attendee and all it&#039;s related data which might be a primary group that is marked as hidden. Just a random guess.

**Comment by Gloirin** [comment]
**Comment posted by pschuele on 23 Mar 2018 09:17**

should be fixed with #13788.

please reopen if it does not work with 2018.02.3

**Comment by msphn** [comment]
I got that with 2019.02.4. This happens for users using apple calendar and caldav which are member of a hidden admin group.

```
2019-05-02T12:15:48+00:00 NOTICE (5): Tinebase_WebDav_PrincipalBackend::getPrincipalByPath::176 Group/list principal does not exist: 26f645a1f1c79f8ef55fdbc392400dd62b61455b
```

**Comment by pschuele** [comment]
is this still happening in current releases?
I'll write a test for this when I find some time. imho this should work (for personal calendars) for a user, even if he is in a hidden group.

**Comment by lab-at-nohl** [comment]
5 years later, I came back to this. In **2022.12.1** the NOTICE - although harmless, I guess - is still there and the log is filled on each WebDAV request once for each hidden goup the user belongs to. 

`NOTICE (5): Tinebase_WebDav_PrincipalBackend::getPrincipalByPath::176 Group/list principal does not exist: <Id of a address list of a hidden group>`

@pschuele You asked for reopening long time ago. As far as I can see, everything works fine. However, **Addressbook_Model_List** that belong to a ***hidden* group** are not found. Is it dangerous/security issue if also the hidden groups are found? 

See line 158 ff. in file **Tinebase/WebDav/PrincipalBackend.php** and my addition in line 170, where I added hidden groups/lists to the filter.  
```php
                    $filter = new Addressbook_Model_ListFilter(array(
                        array(
                            'field' => 'type',
                            'operator' => 'equals',
                            'value' => Addressbook_Model_List::LISTTYPE_GROUP
                        ),
                        array(
                            'field' => 'id',
                            'operator' => 'equals',
                            'value' => $id
                        ),
                    ));
                    $filter->addFilter($filter->createFilter('showHidden', 'equals', true));

                    $list = Addressbook_Controller_List::getInstance()->search($filter)->getFirstRecord();

                    if (!$list) {
                        if (Tinebase_Core::isLogLevel(Zend_Log::NOTICE)) {
                            Tinebase_Core::getLogger()->notice(
                                __METHOD__ . '::' . __LINE__ . ' Group/list principal does not exist: ' . $id );
                        }
                        return null;
                    }

                    $principal = $this->_listToPrincipal($list, $prefix);
```

Can I do this - and I will submit a PR. Or are there any side effects? From my point of view it does not matter. But I do not see in general why such groups should be accessible by WebDAV (it may be better to turn off the NOTICE).
