### ISSUE TITLE
install with LDAP not possible

### ISSUE THREAD

**Issue by pschuele** [tine20/tine20#6873]
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine20test.tine20_addressbook' doesn't exist in /usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228\nStack trace:\n#0 /usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)\n#1 /usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)\n#2 /usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)\n#3 /usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `tine20_...', Array)\n#4 /usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Select.php(711): Zend_Db_Adapter_Pdo_Abstract->query(Obje in /usr/local/share/tine20.git/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235\n\n

**Comment by pschuele** [comment]
caused by this change: https://github.com/tine20/tine20/commit/c79a89269e1386c3789c606e1e775c10f678f99d

**Comment by pschuele** [comment]
reverted that - https://github.com/tine20/tine20/commit/9db9bc787d4f4ffa4f80b0161a739c665210cae1
