### ISSUE TITLE
Crash in admin/users view

### ISSUE THREAD

**Issue by tvannahl** [tine20/tine20#6908]
On our production environment it seems that an old and deactivated user causes the whole view to crash.

If I open the view I get the following error:
```
 2d987 tvannahl - 2018-08-23T11:04:15+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Mail_Protocol_Exception -> cannot enable TLS
 3fb9d hkunze - 2018-08-23T11:04:17+00:00 WARN (4): Tinebase_Core::errorHandler::677 stream_socket_enable_crypto(): Peer certificate CN=`mail.erk.sowiwas.de' did not match expected CN=`mail' in /opt/tine/2018.08.2/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Imap.php::145 (2)
 3fb9d hkunze - 2018-08-23T11:04:17+00:00 WARN (4): Tinebase_Core::errorHandler::678 #0 [internal function]: Tinebase_Core::errorHandler(2, 'stream_socket_e...', '/opt/tine/2018....', 145, Array)
#1 /opt/tine/2018.08.2/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Imap.php(145): stream_socket_enable_crypto(Resource id #354, true, 9)
#2 /opt/tine/2018.08.2/tine20/vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Imap.php(73): Zend_Mail_Protocol_Imap->connect('mail', 143, 'TLS')
#3 /opt/tine/2018.08.2/tine20/Tinebase/EmailUser/Imap/Cyrus.php(225): Zend_Mail_Protocol_Imap->__construct('mail', 143, 'TLS')
#4 /opt/tine/2018.08.2/tine20/Tinebase/EmailUser/Imap/Cyrus.php(119): Tinebase_EmailUser_Imap_Cyrus->_getImapConnection()
#5 /opt/tine/2018.08.2/tine20/Admin/Controller/User.php(99): Tinebase_EmailUser_Imap_Cyrus->inspectGetUserByProperty(Object(Tinebase_Model_FullUser))
#6 /opt/tine/2018.08.2/tine20/Admin/Frontend/Json.php(276): Admin_Controller_User->searchFullUsers('', 'accountLoginNam...', 'ASC', 0, 50)
#7 /opt/tine/2018.08.2/tine20/Admin/Frontend/Json.php(318): Admin_Frontend_Json->getUsers('', 'accountLoginNam...', 'ASC', 0, 50)
#8 /opt/tine/2018.08.2/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Admin_Frontend_Json->searchUsers(Array, Array)
#9 /opt/tine/2018.08.2/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#10 /opt/tine/2018.08.2/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#11 /opt/tine/2018.08.2/tine20/Tinebase/Server/Json.php(379): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#12 /opt/tine/2018.08.2/tine20/Tinebase/Server/Json.php(163): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#13 /opt/tine/2018.08.2/tine20/Tinebase/Core.php(260): Tinebase_Server_Json->handle(Object(Zend_Json_Server_Request))
#14 /opt/tine/2018.08.2/tine20/index.php(24): Tinebase_Core::dispatchRequest()
#15 {main}
```

I know, there is an error in the users configuration, but without code interaction this error is not correctable. The user is deactivated for good reason, and I it was required of me to modify the source code to actually find out which user is causing the problem.

I was able to work around that problem using the following patch:

```diff

diff --git a/tine20/Admin/Controller/User.php b/tine20/Admin/Controller/User.php
index a86d793..04420e4 100644
--- a/tine20/Admin/Controller/User.php
+++ b/tine20/Admin/Controller/User.php
@@ -88,9 +88,9 @@ class Admin_Controller_User extends Tinebase_Controller_Abstract
         $result = $this->_userBackend->getUsers($_filter, $_sort, $_dir, $_start, $_limit, 'Tinebase_Model_FullUser');
 
         $emailUser = null;
-        try {
-            $emailUser = Tinebase_EmailUser::getInstance();
-        } catch (Tinebase_Exception_NotFound $tenf) {}
+        //try {
+        //    $emailUser = Tinebase_EmailUser::getInstance();
+        //} catch (Tinebase_Exception_NotFound $tenf) {}
 
         // FIXME if you want quota info: in Tinebase_User_Plugin_LdapInterface, inspectGetUserByProperty has a second param!
         if (null !== $emailUser && ! $emailUser instanceof Tinebase_User_Plugin_LdapInterface ) {
```

**Comment by pschuele** [comment]
you could also deactivate the certificate validation (verifyPeer = false) to prevent this error. but this error should be catched to make sure the user list is still available. I'll have a look at that.
