### ISSUE TITLE
PDO::MYSQL_ATTR_USE_BUFFERED_QUERY is not defined

### ISSUE THREAD

**Issue by TomBraun** [tine20/tine20#6910]
https://server.domain/tine20/setup.php

Fatal error: Uncaught Tinebase_Exception_Backend_Database: PDO::MYSQL_ATTR_USE_BUFFERED_QUERY is not defined. Please check PDO extension. in /srv/http/tine20/Tinebase/Core.php:1051 Stack trace: #0 /srv/http/tine20/Tinebase/Core.php(1006): Tinebase_Core::createAndConfigureDbAdapter(Array) #1 /srv/http/tine20/Setup/Core.php(209): Tinebase_Core::setupDatabaseConnection() #2 /srv/http/tine20/Setup/Core.php(39): Setup_Core::setupDatabaseConnection() #3 /srv/http/tine20/Setup/Server/Http.php(33): Setup_Core::initFramework() #4 /srv/http/tine20/Setup/Core.php(115): Setup_Server_Http->handle() #5 /srv/http/tine20/setup.php(14): Setup_Core::dispatchRequest() #6 {main} thrown in /srv/http/tine20/Tinebase/Core.php on line 1051

```
// minimal configuration
return array(
    // set 'count' equal zero to disable captcha, or set to number of invalid logins before request captcha.
    'captcha' => array('count'=>0), 
    'database' => array(
        'host'          => '127.0.0.1',
        'dbname'        => 'none',
        'username'      => 'tine20user',
        'password'      => 'none',
        'adapter'       => 'pdo_mysql',
        'tableprefix'   => 'tine20_',
    ),
    'setupuser' => array(
        'username'      => 'none',
        'password'      => 'none' 
    ),

    // optional cache (recommended)
    'caching' => array (
        'active' => true,
        'path' => '/srv/tine20/cache/',
        'lifetime' => 3600,
    ),
   

    // optional logger
    'logger' => array (
        'active' => true,
        'filename' => '/srv/tine20/log/tine20.log',
        'priority' => '7',
    ),

);

```

**Comment by TomBraun** [comment]
pdo_mysql was not aktive

/etc/php/php.ini:;extension=pdo_mysql
