### ISSUE TITLE
no event notifications with active redis-queue 

### ISSUE THREAD

**Issue by mgoppold** [tine20/tine20#6929]
tine2.0 (2018.08.4) does not send event notifications when redis is active. 

```
# redis-cli keys '*'
1) "TinebaseQueueData:3d2ccb8582efac66162c4449b7b6be877c6573be"
2) "TinebaseQueueQueue"
3) "TinebaseQueueData:05e4def4b6f32756e60636b1eaa14a430ee56b06"
4) "TinebaseQueueData:97777c024530599a6b2f34ca05438b2efe8a3b1b"
5) "TinebaseQueueData:8b58f32998e11766ef7ac1e026cc422eab74e4bd"
```

```
# grep 3d2ccb8582efac66162c4449b7b6be877c6573be tine20.log_TestNr12 
9140e 955e7 mgoppold - 2018-09-25T06:04:55+00:00 DEBUG (7): Tinebase_ActionQueue_Backend_Redis::send::219 queued job 3d2ccb8582efac66162c4449b7b6be877c6573be on queue TinebaseQueueQueue (datastructname: TinebaseQueueData)
```

```
# redis-cli dump 'TinebaseQueueQueue'
"\x0e\x01@\xb3\xb3\x00\x00\x00\x88\x00\x00\x00\x04\x00\x00(3d2ccb8582efac66162c4449b7b6be877c6573be*(05e4def4b6f32756e60636b1eaa14a430ee56b06*(97777c024530599a6b2f34ca05438b2efe8a3b1b*(8b58f32998e11766ef7ac1e026cc422eab74e4bd\xff\b\x00\xfb\xbf\x9e\x98A0\x04\xfb"
```

```
 # redis-cli dump 'TinebaseQueueData:3d2ccb8582efac66162c4449b7b6be877c6573be'
"\x04\x05\x05retry\xc0\x00\x04time\x132018-09-25 06:04:55\x04data\xc3[\xbe\x80\x00\x00h\xce\x1fa:3:{s:6:\"action\";s:31:\"Calendar\x01.s \x06\x0cEventNotifica ... 
```

When redis is disabled event notifications will be sent.

**Comment by pschuele** [comment]
you need to run the tine20-worker for the execution of the queue jobs, if you activate the queue config.
the easiest way to do this, is to install the tine20-worker deb package, which comes with systemd configuration.

we'll write a short howto on this in the near future.

**Comment by mgoppold** [comment]
My Tine2.0 Service runs on openSUSE and so I could not use the dep out of the box, but:

```
wget https://packages.tine20.org/ubuntu/pool/stable/t/tine20/tine20-worker_2018.08.4-1.1804_all.deb
mkdir /tmp/tine20-worker
cd /tmp/tine20-worker
ar -xv ~/Downloads/tine20-worker_2018.08.4-1.1804_all.deb
tar xvJf data.tar.xz
scp -r ./etc/tine20/* root@tine20server:/srv/www/vhosts/etc/tine20
scp -r ./usr root@tine20server:/srv/www/vhosts/
scp ./lib/systemd/system/tine20-worker.service root@tine20server:/etc/systemd/system/
```

at tine20server:

```
chown -R wwwrun: /srv/www/vhosts/usr/
chmod -R a+r /srv/www/vhosts/etc/tine20/
```

Modifiy **/etc/systemd/system/tine20-worker.service**

```
WorkingDirectory=/srv/www/vhosts/tine20/tine20adm/
ExecStart=/usr/bin/php -d include_path=/srv/www/vhosts/tine20/ /srv/www/vhosts/usr/share/tine20/worker.php --config /srv/www/vhosts/etc/tine20/actionQueue.ini
User=wwwrun
Group=wwwrun
```

Modify **/srv/www/vhosts/etc/tine20/actionQueue.ini**

```
logfile = /srv/www/vhosts/tine20/tine20adm/worker.log
```


Start the service:

```
systemctl daemon-reload
systemctl start tine20-worker.service
```

But the service wont start. The running cmdline is:

`/usr/bin/php -d include_path=/srv/www/vhosts/tine20/ /srv/www/vhosts/usr/share/tine20/worker.php --config /srv/www/vhosts/etc/tine20/actionQueue.ini `

and the error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_signal() in /srv/www/vhosts/tine20/library/Console/Daemon.php:67
Stack trace:
#0 /srv/www/vhosts/tine20/Tinebase/ActionQueue/Worker.php(70): Console_Daemon->__construct(NULL)
#1 /srv/www/vhosts/usr/share/tine20/worker.php(19): Tinebase_ActionQueue_Worker->__construct()
#2 {main}
  thrown in /srv/www/vhosts/tine20/library/Console/Daemon.php on line 67

Fatal error: Uncaught Error: Call to undefined function pcntl_signal() in /srv/www/vhosts/tine20/library/Console/Daemon.php:67
Stack trace:
#0 /srv/www/vhosts/tine20/Tinebase/ActionQueue/Worker.php(70): Console_Daemon->__construct(NULL)
#1 /srv/www/vhosts/usr/share/tine20/worker.php(19): Tinebase_ActionQueue_Worker->__construct()
#2 {main}
  thrown in /srv/www/vhosts/tine20/library/Console/Daemon.php on line 67
```

**Comment by pschuele** [comment]
nice, thanks for the howto!

> PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_signal()

maybe you are missing the "pcntl" php module. we should add this as a requirement for the worker service.

> Does the service completely replace the earlier "Asynchronous jobs" from cron.d?

no, this is still needed! the worker just checks the redis queue and runs the jobs that are out into it.

**Comment by mgoppold** [comment]
Ok I have got it working :-)

After 'zypper install php7-pcntl` and a few adjustments (group wwwrun->www, chown Config-Files) the service is running and notifications where send.

Thank you for pointing me in the right direction.

**Comment by mgoppold** [comment]
> nice, thanks for the howto!
> 
> > PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_signal()
> 
> maybe you are missing the "pcntl" php module. we should add this as a requirement for the worker service.
> 
> > Does the service completely replace the earlier "Asynchronous jobs" from cron.d?
> 
> no, this is still needed! the worker just checks the redis queue and runs the jobs that are out into it.

In order not to have cron and systemd services here is a systemd.timer for the async jobs:


[tine20-async.service.txt](https://github.com/tine20/tine20/files/2414926/tine20-async.service.txt)
[tine20-async.timer.txt](https://github.com/tine20/tine20/files/2414927/tine20-async.timer.txt)

```
scp tine20-async.*.txt root@tine20server:/etc/systemd/system/

systemctl daemon-reload
systemctl enable tine20-async.timer
systemctl start tine20-async.timer
systemctl list-timers 
NEXT                         LEFT         LAST                         PASSED       UNIT                         ACTIVATES
Di 2018-09-25 13:10:00 CEST  3min 18s ago Di 2018-09-25 13:10:01 CEST  3min 17s ago tine20-async.timer           tine20-async.service

```

**Comment by pschuele** [comment]
> Ok I have got it working :-)

great :)

> In order not to have cron and systemd services here is a systemd.timer for the async jobs:

thanks for sharing that. I'll link to that from the wiki.

**Comment by lab-at-nohl** [comment]
I wonder, if we can have the _systemd’s_ **service** and **timer** in a single rpm? Or at least a script for automatization. 

Probably for a standards compliant rpm their is no need for distinction between openSUSE and RH-based flavors. Of course a general rpm should use global paths; to make worker.php known (which has a random location) you may use a symbolic link in /etc/tine20.

**Comment by mgoppold** [comment]
Sure, there is no reason not to put both in one rpm:

```
%install
...
install -c -m 644 tine20-async.timer  ${RPM_BUILD_ROOT}/%{_unitdir}
install -c -m 644 tine20-async.service  ${RPM_BUILD_ROOT}/%{_unitdir}
...
%post
test -x /bin/systemctl && /bin/systemctl daemon-reload || :
test -x /bin/systemctl && /bin/systemctl enable  tine20-async.timer &&  /bin/systemctl start tine20-async.timer

%postun
test -x /bin/systemctl && /bin/systemctl stop tine20-async.timer && /bin/systemctl disbale tine20-async.timer
test -x /bin/systemctl && /bin/systemctl daemon-reload || :


%files
...
%{_unitdir}/tine20-async.*
```

this install the timer and activates them.

**Comment by mgoppold** [comment]
> Probably for a standards compliant rpm their is no need for distinction between openSUSE and RH-based flavors. Of course a general rpm should use global paths; to make worker.php known (which has a random location) you may use a symbolic link in /etc/tine20.

sure, what I want to show is to activate the service for users they don't install tine20 with rpm. 

by now, you only provide dep's or not?

**Comment by pschuele** [comment]
> by now, you only provide dep's or not?

yep (for the community edition). there are (centos) rpms for the business edition (-> https://packages.tine20.com/maintenance/centos/).

we are thinking about moving our build infrastructure to https://openbuildservice.org/. does anybody here have experience with that and/or is willing to help us with this task?

**Comment by pschuele** [comment]
> thanks for sharing that. I'll link to that from the wiki.

-> https://github.com/tine20/tine20/wiki/EN:Queue

**Comment by mgoppold** [comment]
> > by now, you only provide dep's or not?
> 
> yep (for the community edition). there are (centos) rpms for the business edition (-> https://packages.tine20.com/maintenance/centos/).
> 
> we are thinking about moving our build infrastructure to https://openbuildservice.org/. does anybody here have experience with that and/or is willing to help us with this task?

Yes, I have. With stand alone packages and branching existing packages, CLI and WebIF. It should not be a big thing.

**Comment by pschuele** [comment]
> Yes, I have. With stand alone packages and branching existing packages, CLI and WebIF. It should not be a big thing.

ok, great. then I'll use this issue as a reminder to tackle this task soon.

@mgoppold do you have an example, maybe of a similar project, of the build configuration for openbuildservice?

**Comment by mgoppold** [comment]
> > Yes, I have. With stand alone packages and branching existing packages, CLI and WebIF. It should not be a big thing.
> 
> ok, great. then I'll use this issue as a reminder to tackle this task soon.
> 
> @mgoppold do you have an example, maybe of a similar project, of the build configuration for openbuildservice?

I start with your src.rpm from centos:

```
osc meta prj -e home:mgoppold:tine20
osc meta prj -e home:mgoppold:tine20:2017.11.5
osc meta pkg -e home:mgoppold:tine20:2017.11.5 tine20
osc co home:mgoppold:tine20:2017.11.5
cd home:mgoppold:tine20:2017.11.5:tine20
unpack centos.src.rpm
osc add tine20-allinone_2017.11.15.tar.bz2 ... tine20.spec ... tine20.te
osc commit -m "initial release"
```

Try to fix some SUSE-things but with no luck until now but get RPMs for 

- CentOS_6/7 
- Debian_8.0/9.0 
- Fedora_27/28 
- RHEL_6/7

You can find it on [https://build.opensuse.org/package/show/home:mgoppold:tine20:2017.11.5/tine20](url)

I disabled the publish Flag because I do not know if you like it when the packages are there for public (in this state).

**Comment by pschuele** [comment]
great! thanks for your efforts :)

> I disabled the publish Flag because I do not know if you like it when the packages are there for public (in this state).

i would prefer to put the community edition (i.e. 2018.08.*) there. instead of using the tine20-allinone_2017.11.15.tar.bz2, you could add the tarballs from https://packages.tine20.org/source/.
is it possible to trigger a build if a new release is added to https://packages.tine20.org ?

publishing the (community-)rpms is no problem.

**Comment by mgoppold** [comment]
sorry for the delay.

there is already a tine20 build here: https://build.opensuse.org/package/show/network:groupware:tine20/tine20

Should I still raise my repo to the current version?

**Comment by pschuele** [comment]
hi,

> Should I still raise my repo to the current version?

yes, that would be great. I'll add the link to the release notes. thanks for the effort!

**Comment by pschuele** [comment]
ah, sorry - I thought, that was your repo, too. so we currently have 2 (or more?) tine20 builds on https://build.opensuse.org/. maybe the queue stuff could be added to https://build.opensuse.org/package/show/network:groupware:tine20/tine20 as well? if I find the time, I'll  have a deeper look at the rpm packaging.
