### ISSUE TITLE
Update 2018.08.03->2018.08.04 fails: Unknown database type enum requested

### ISSUE THREAD

**Issue by CB79** [tine20/tine20#6942]
When updating from version 2018.02.03 to 2018.08.04 an error is thrown and the update cannot be completed. The issue is reproducible.

Command: php setup.php --update all
Error message:
```
PHP Fatal error:  Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.' in /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:423
Stack trace:
#0 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php(126): Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping('enum')
#1 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\MySqlSchemaManager->_getPortableTableColumnDefinition(Array)
#2 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(175): Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList('tine20_timetrac...', 'tine_db', Array)
#3 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(281): Doctrine\DBAL\Schema\AbstractSchemaM in /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php on line 423

Fatal error: Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.' in /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:423
Stack trace:
#0 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php(126): Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping('enum')
#1 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\MySqlSchemaManager->_getPortableTableColumnDefinition(Array)
#2 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(175): Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList('tine20_timetrac...', 'tine_db', Array)
#3 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(281): Doctrine\DBAL\Schema\AbstractSchemaM in /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php on line 423
```

The message on the command line implies the error is in Timetracker (_getPortableTableColumnList('tine20_timetrac...). But exactly the same message appears when updating only a single other app (tried with Felamimail, Tasks and Addressbook)

Excerpt from tine20.log
```
76ed3 setupuser - 2018-10-21T14:01:27+00:00 ERR (3): Setup_Controller::updateApplication::628 Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
76ed3 setupuser - 2018-10-21T14:01:27+00:00 ERR (3): Setup_Controller::updateApplication::629 #0 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php(126): Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping('enum')
#1 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(820): Doctrine\DBAL\Schema\MySqlSchemaManager->_getPortableTableColumnDefinition(Array)
#2 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(175): Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList('tine20_timetrac...', 'tine_db', Array)
#3 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(281): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns('tine20_timetrac...')
#4 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(268): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails('tine20_timetrac...')
#5 /home/www/subpath/tine/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(1040): Doctrine\DBAL\Schema\AbstractSchemaManager->listTables()
#6 /home/www/subpath/tine/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(862): Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema()
#7 /home/www/subpath/tine/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(839): Doctrine\ORM\Tools\SchemaTool->getUpdateSchemaSql(Array, true)
#8 /home/www/subpath/tine/Setup/SchemaTool.php(140): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#9 /home/www/subpath/tine/Setup/Update/Abstract.php(532): Setup_SchemaTool::updateSchema('Timetracker', Array)
#10 /home/www/subpath/tine/Timetracker/Setup/Update/Release12.php(46): Setup_Update_Abstract->updateSchema('Timetracker', Array)
#11 /home/www/subpath/tine/Setup/Controller.php(622): Timetracker_Setup_Update_Release12->update_1()
#12 /home/www/subpath/tine/Setup/Controller.php(493): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#13 /home/www/subpath/tine/Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
#14 [internal function]: Setup_Frontend_Json->updateApplications(Array)
#15 /home/www/subpath/tine/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): call_user_func_array(Array, Array)
#16 /home/www/subpath/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#17 /home/www/subpath/tine/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#18 /home/www/subpath/tine/Setup/Server/Json.php(90): Zend_Json_Server->handle(Object(Zend_Json_Server_Request_Http))
#19 /home/www/subpath/tine/Setup/Core.php(115): Setup_Server_Json->handle()
#20 /home/www/subpath/tine/setup.php(14): Setup_Core::dispatchRequest()
#21 {main}

```

Versions:
MySQL: 5.7.23
PHP: 5.6.38

**Comment by koelschejung74** [comment]
can you try first update to 2018.08.1?

**Comment by paulmhh** [comment]
you should update to the latest version of your current release before updating to a new release always!
2018.02.3 -> 2018.02.7 and only after that you can update
2018.02.7 to 2018.08.4

**Comment by CB79** [comment]
@koelschejung74: I already tried that but no success.
@paulmhh: I tried that as well. Unfortunately no success either.

After some other unsuccessful attempts I did the following in order:
Restoring the old version from Backup.
Update to 2018.02.7 --> works fine
Update to 2018.08.1 --> works fine
Update to 2018.08.2 --> works fine
Update to 2018.08.3 --> works fine
Update to 2018.08.4 --> broken

**Comment by lab-at-nohl** [comment]
Ok, paulmhh is 100% right. As you can see, the major update worked. 

For the last minor, we have to narrow it down. In my mind I always use `php setup.php --update` (without `all`). Can you try?

Besides, you are using MySQL 5.7.23 not MariaDB, right? The following error can be found: 
```
Fatal error: Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.'
```
Look to this discussion at [stackoverflow](https://stackoverflow.com/questions/33140860/laravel-5-1-unknown-database-type-enum-requested). Seems like an upstream failure to me. If you have some programming knowledge you can try to fix it manually.

**Comment by CB79** [comment]
I think it doesn't matter if you use "all" or not. It seems to be the default if not used. I tried both versions but it didn't change the behaviour.

At least PHPMyAdmin says it's MySQL and the status command as well (5.7.23-log MySQL Community Server (GPL)).
My PHP skills are a bit too outdated to fix it myself. There's another Github defect in doctrine/dbal which describes the problem: https://github.com/doctrine/dbal/issues/3161 and this again points to 
--> Stackoverflow (https://stackoverflow.com/questions/8750724/what-do-you-use-instead-of-enum-in-doctrine2/9057352) and
--> some Doctrine documentation (https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/mysql-enums.html)

**Comment by CB79** [comment]
Changed the title to "... 2018.08.03->2018.08.04 ..." as it better reflects the problematic step.

**Comment by paulmhh** [comment]
it seems you have a very old installation. There once was an update removing all enum fields:

commit df0b02e91890426d22e853652ed0842fe4b9ba7f

it also seems your installation skipped some updates and your db schema was not adjusted properly. You will have to fix this by hand and exchange all enum fields with varchar. Something like this:

ALTER TABLE `tine20_timetracker_timeaccount` CHANGE `status` `status` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'not yet billed';

Probably you want to use utf8 instead of utf8mb4 if you have an old db.

This is not a bug, but a maintenance issue of the installation
