### ISSUE TITLE
Applikationsupdate nach Upgrade auf Tine20 2018.08.5 geht schief

### ISSUE THREAD

**Issue by cvantum** [tine20/tine20#6949]
Hallo,

heute morgen habe ich auf unserem Server ( Debian Stretch ) über euer Repository ein Upgrade der Pakete erhalten auf die Version 2018.08.5. Für dieses Update war ein Update der Applikationen erforderlich. Beim Update der Applikation *Calendar* steigt die CLI aus, mit folgender Fehlermeldung:

```
PHP Fatal error:  Uncaught Tinebase_Exception_NotFound: Tinebase_Model_Container record with id = 6799226346c421597f7bb62f2b60d6ead02f857e not found! in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('6799226346c4215...', 'id', false)
#1 /usr/share/tine20/Tinebase/Container.php(2043): Tinebase_Backend_Sql_Abstract->get('6799226346c4215...', false)
#2 /usr/share/tine20/Calendar/Setup/Update/Release11.php(297): Tinebase_Container->update(Object(Tinebase_Model_Container))
#3 /usr/share/tine20/Calendar/Setup/Update/Release12.php(66): Calendar_Setup_Update_Release11->update_11()
#4 /usr/share/tine20/Setup/Controller.php(631): Calendar_Setup_Update_Release12->update_4()
#5 /usr/share/tine20/Setup/Controller.php(507): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#6 /usr/share/tine20/Setup/Frontend/Cli.php(546): Setup_Controller->updateApplications(Object(Tinebase_Record_Recor in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php on line 282

Fatal error: Uncaught Tinebase_Exception_NotFound: Tinebase_Model_Container record with id = 6799226346c421597f7bb62f2b60d6ead02f857e not found! in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('6799226346c4215...', 'id', false)
#1 /usr/share/tine20/Tinebase/Container.php(2043): Tinebase_Backend_Sql_Abstract->get('6799226346c4215...', false)
#2 /usr/share/tine20/Calendar/Setup/Update/Release11.php(297): Tinebase_Container->update(Object(Tinebase_Model_Container))
#3 /usr/share/tine20/Calendar/Setup/Update/Release12.php(66): Calendar_Setup_Update_Release11->update_11()
#4 /usr/share/tine20/Setup/Controller.php(631): Calendar_Setup_Update_Release12->update_4()
#5 /usr/share/tine20/Setup/Controller.php(507): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#6 /usr/share/tine20/Setup/Frontend/Cli.php(546): Setup_Controller->updateApplications(Object(Tinebase_Record_Recor in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php on line 282
```

Beim Blick in die Datenbank finde ich den entsprechenden Container mit:

`select * from tine20_container WHERE id="6799226346c421597f7bb62f2b60d6ead02f857e"`

Die Zeile ist markiert als `is_deleted = 1`

Gibt es einen Workaround hierfür?

Mit freundlichen Grüßen

**Comment by pschuele** [comment]
hallo,
danke für den bugreport, wir schauen uns das an.

**Comment by pschuele** [comment]
das sollte das problem beheben:

```patch
diff --git a/tine20/Calendar/Setup/Update/Release11.php b/tine20/Calendar/Setup/Update/Release11.php
index 106cdd6756..e50d34c87d 100644
--- a/tine20/Calendar/Setup/Update/Release11.php
+++ b/tine20/Calendar/Setup/Update/Release11.php
@@ -277,11 +277,12 @@ class Calendar_Setup_Update_Release11 extends Setup_Update_Abstract
             ));
 
             foreach ($containerBackend->search(new Tinebase_Model_ContainerFilter([
-                        ['field' => 'application_id', 'operator' => 'equals', 'value' =>
-                            Tinebase_Application::getInstance()->getApplicationByName('Calendar')->getId()],
-                        ['field' => 'type', 'operator' => 'equals', 'value' => Tinebase_Model_Container::TYPE_SHARED],
-                        ['field' => 'name', 'operator' => 'contains', 'value' => '@']
-                    ])) as $container) {
+                    ['field' => 'application_id', 'operator' => 'equals', 'value' =>
+                        Tinebase_Application::getInstance()->getApplicationByName('Calendar')->getId()],
+                    ['field' => 'type', 'operator' => 'equals', 'value' => Tinebase_Model_Container::TYPE_SHARED],
+                    ['field' => 'name', 'operator' => 'contains', 'value' => '@'],
+                    ['field' => 'is_deleted', 'operator' => 'equals', 'value' => 0],
+            ])) as $container) {
 
                 if (isset($container->xprops()[Calendar_Controller::XPROP_EXTERNAL_INVITATION_CALENDAR]) ||
                         !preg_match(Tinebase_Mail::EMAIL_ADDRESS_REGEXP, $container->name)) {

**Comment by pschuele** [comment]
this is also needed for the patch above to work:

```patch
diff --git a/tine20/Tinebase/Model/ContainerFilter.php b/tine20/Tinebase/Model/ContainerFilter.php
index c094bc2376..84c97d4622 100644
--- a/tine20/Tinebase/Model/ContainerFilter.php
+++ b/tine20/Tinebase/Model/ContainerFilter.php
@@ -40,5 +40,6 @@ class Tinebase_Model_ContainerFilter extends Tinebase_Model_Filter_FilterGroup
         'owner_id'          => array('filter' => 'Tinebase_Model_Filter_Id'),
         'model'             => array('filter' => 'Tinebase_Model_Filter_Text'),
         'uuid'              => array('filter' => 'Tinebase_Model_Filter_Text'),
+        'is_deleted'        => array('filter' => 'Tinebase_Model_Filter_Bool'),
     );
 }
