### ISSUE TITLE
Error on update from 2018.08.4 to 2018.08.5

### ISSUE THREAD

**Issue by tvannahl** [tine20/tine20#6959]
On `php setup.php --update` I get the following error:

```
PHP Fatal error:  Uncaught Tinebase_Exception_NotFound: Tinebase_Model_Container record with id = 430 not found! in /opt/tine20/tine20/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /opt/tine20/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('430', 'id', false)
#1 /opt/tine20/tine20/Tinebase/Container.php(2043): Tinebase_Backend_Sql_Abstract->get('430', false)
#2 /opt/tine20/tine20/Calendar/Setup/Update/Release11.php(297): Tinebase_Container->update(Object(Tinebase_Model_Container))
#3 /opt/tine20/tine20/Calendar/Setup/Update/Release12.php(66): Calendar_Setup_Update_Release11->update_11()
#4 /opt/tine20/tine20/Setup/Controller.php(631): Calendar_Setup_Update_Release12->update_4()
#5 /opt/tine20/tine20/Setup/Controller.php(507): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#6 /opt/tine20/tine20/Setup/Frontend/Cli.php(546): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSetFast))
#7 /opt/tine20/tine20/Setup/Frontend/Cli.php(502 in /opt/tine20/tine20/Tinebase/Backend/Sql/Abstract.php on line 282

Fatal error: Uncaught Tinebase_Exception_NotFound: Tinebase_Model_Container record with id = 430 not found! in /opt/tine20/tine20/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /opt/tine20/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('430', 'id', false)
#1 /opt/tine20/tine20/Tinebase/Container.php(2043): Tinebase_Backend_Sql_Abstract->get('430', false)
#2 /opt/tine20/tine20/Calendar/Setup/Update/Release11.php(297): Tinebase_Container->update(Object(Tinebase_Model_Container))
#3 /opt/tine20/tine20/Calendar/Setup/Update/Release12.php(66): Calendar_Setup_Update_Release11->update_11()
#4 /opt/tine20/tine20/Setup/Controller.php(631): Calendar_Setup_Update_Release12->update_4()
#5 /opt/tine20/tine20/Setup/Controller.php(507): Setup_Controller->updateApplication(Object(Tinebase_Model_Application), '12')
#6 /opt/tine20/tine20/Setup/Frontend/Cli.php(546): Setup_Controller->updateApplications(Object(Tinebase_Record_RecordSetFast))
#7 /opt/tine20/tine20/Setup/Frontend/Cli.php(502 in /opt/tine20/tine20/Tinebase/Backend/Sql/Abstract.php on line 282
```

**Comment by tvannahl** [comment]
You sure that the patch did land in 2018.08.5? I cannot find it in the git log: https://github.com/tine20/tine20/compare/2018.08.4...2018.08.5 nor did I find a `2018.08.5.1` or `2018.08.6`

**Comment by pschuele** [comment]
the patch (https://github.com/tine20/tine20/commit/83e50957fe83836f67029686163eeb98a59c92fc) is coming with 2018.08.6 which will be released on Thursday.
