### ISSUE TITLE
Update von 8.4 auf 8.6 schlägt fehl

### ISSUE THREAD

**Issue by Matze0811** [tine20/tine20#6966]
Beim heutigen Versuch meine tine20 Installation auf die 8.6 zu heben, kam es bei der Verwendung von "php setup.php --update" zu folgendem Fehler:

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`tine20_tree_nodes`, CONSTRAINT `tine20_tree_nodes::parent_id--tree_nodes::id` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`) ON UPDATE CASCADE) in /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)

Das Aufrufen des updates per Web-Oberfläche führte dazu:

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`tine20_tree_nodes`, CONSTRAINT `tine20_tree_nodes::parent_id--tree_nodes::id` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`) ON UPDATE CASCADE), query was: UPDATE `tine20_tree_nodes` SET `deleted_time` = ? WHERE (deleted_time IS NULL)

.../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(323): Zend_Db_Statement_Pdo->_execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
.../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Zend_Db_Adapter_Pdo_Abstract->query()
.../Tinebase/Setup/Update/Release10.php(2563): Zend_Db_Adapter_Abstract->update()
.../Tinebase/Setup/Update/Release12.php(101): Tinebase_Setup_Update_Release10->update_57()
.../Setup/Controller.php(633): Tinebase_Setup_Update_Release12->update_6()
.../Setup/Controller.php(502): Setup_Controller->updateApplication()
.../Setup/Frontend/Json.php(118): Setup_Controller->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Setup_Frontend_Json->updateApplications()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch()
.../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
.../Setup/Server/Json.php(90): Zend_Json_Server->handle()
.../Setup/Core.php(115): Setup_Server_Json->handle()
.../setup.php(14): Setup_Core::dispatchRequest()

Was läuft den da schief?

**Comment by pschuele** [comment]
@paulmhh could you have a look at this? how can we prevent the constraint violation?
