### ISSUE TITLE
Frage zu einem Logeintrag

### ISSUE THREAD

**Issue by koelschejung74** [tine20/tine20#6982]
Ich habe bei meiner 2. Domain (2018088) das Loglevel auf 5 gestellt und bekomme folgende Meldung bei Login im Browser:

[[0m 5a437 ^[[1m^[[32mulrich^[[0m - ^[[1m^[[33m2019-01-08T19:59:58+01:00 WARN (4): Tinebase_Frontend_Json_Abstract::getTemplates::540 Could not get template files: Tinebase_Exception_NotFound: Tinebase_Model_Tree_Node record with id = 2 not found! in /srv/www/skippersnet/2018088/Tinebase/Backend/Sql/Abstract.php:282
Stack trace:
#0 /srv/www/skippersnet/2018088/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('2', 'id', false)
#1 /srv/www/skippersnet/2018088/Tinebase/FileSystem.php(259): Tinebase_Backend_Sql_Abstract->get('2', false)
#2 /srv/www/skippersnet/2018088/Tinebase/Frontend/Json/Abstract.php(534): Tinebase_FileSystem->get('2')
#3 /srv/www/skippersnet/2018088/Felamimail/Frontend/Json.php(554): Tinebase_Frontend_Json_Abstract->getTemplates('2')
#4 /srv/www/skippersnet/2018088/Felamimail/Frontend/Json.php(609): Felamimail_Frontend_Json->getVacationMessageTemplates()
#5 /srv/www/skippersnet/2018088/Tinebase/Frontend/Json.php(1069): Felamimail_Frontend_Json->getRegistryData()
#6 /srv/www/skippersnet/2018088/Tinebase/Frontend/Json.php(997): Tinebase_Frontend_Json->_getCustomAppRegistry(Object(Tinebase_Model_Application))
#7 /srv/www/skippersnet/2018088/Tinebase/Frontend/Json.php(947): Tinebase_Frontend_Json->_getAppRegistry(Object(Tinebase_Model_Application), Object(Tinebase_Config_Struct), Object(Tinebase_Record_RecordSetFast))
#8 /srv/www/skippersnet/2018088/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Tinebase_Frontend_Json->getAllRegistryData()
#9 /srv/www/skippersnet/2018088/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#10 /srv/www/skippersnet/2018088/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#11 /srv/www/skippersnet/2018088/Tinebase/Server/Json.php(383): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#12 /srv/www/skippersnet/2018088/Tinebase/Server/Json.php(161): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#13 /srv/www/skippersnet/2018088/Tinebase/Core.php(261): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#14 /srv/www/skippersnet/2018088/index.php(24): Tinebase_Core::dispatchRequest()
#15 {main}

Was besagt diese?
Ich hoffe, ich poste hier nicht zu viel, bin etwas nervös, weil es bei meiner 1. Domain nicht rund läuft.

Aber ich hoffe, ich kann etwas beitragen.

Viele Grüße
Uli

**Comment by Matze0811** [comment]
Ich kann Dir zwar nicht helfen, habe aber exakt das selbe Problem. By the Way, meine Tine20 Installation ist Stand 2018.08.4

Hier mein Log-Eintrag:

` 1316a ******.***** - 2019-01-08T19:53:28+00:00 WARN (4): Tinebase_Frontend_Json_Abstract::getTemplates::540 Could not get template f$
102 Stack trace:
103 #0 /var/www/elektrohd/tine20/Tinebase/Backend/Sql/Abstract.php(234): Tinebase_Backend_Sql_Abstract->getByProperty('2', 'id', false)
104 #1 /var/www/elektrohd/tine20/Tinebase/FileSystem.php(259): Tinebase_Backend_Sql_Abstract->get('2', false)
105 #2 /var/www/elektrohd/tine20/Tinebase/Frontend/Json/Abstract.php(534): Tinebase_FileSystem->get('2')
106 #3 /var/www/elektrohd/tine20/Felamimail/Frontend/Json.php(556): Tinebase_Frontend_Json_Abstract->getTemplates('2')
107 #4 /var/www/elektrohd/tine20/Felamimail/Frontend/Json.php(611): Felamimail_Frontend_Json->getVacationMessageTemplates()
108 #5 /var/www/elektrohd/tine20/Tinebase/Frontend/Json.php(1069): Felamimail_Frontend_Json->getRegistryData()
109 #6 /var/www/elektrohd/tine20/Tinebase/Frontend/Json.php(997): Tinebase_Frontend_Json->_getCustomAppRegistry(Object(Tinebase_Model_Appli$
110 #7 /var/www/elektrohd/tine20/Tinebase/Frontend/Json.php(947): Tinebase_Frontend_Json->_getAppRegistry(Object(Tinebase_Model_Application$
111 #8 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Tinebase_Frontend_Json->getAllR$
112 #9 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Obj$
113 #10 /var/www/elektrohd/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
114 #11 /var/www/elektrohd/tine20/Tinebase/Server/Json.php(383): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
115 #12 /var/www/elektrohd/tine20/Tinebase/Server/Json.php(161): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
116 #13 /var/www/elektrohd/tine20/Tinebase/Core.php(261): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
117 #14 /var/www/elektrohd/tine20/index.php(24): Tinebase_Core::dispatchRequest()
118 #15 {main}`
