### ISSUE TITLE
Upgrade and loading screen

### ISSUE THREAD

**Issue by crosenbe** [tine20/tine20#6991]
I tried to upgrade to the latest release and i get an endless loading screen. I followed the upgrade recommendation ...

-> 2017-02-1 -> 2017-08-1 -> 2017-08-11 -> 2018-02-7 -> 2018-08-1 -> 2018-08-9

I found two issues.

1. 2017-08-01 -> 2017-08-11 did not work, i used 2017-08-1 -> 2017-08-8 -> 2017-08-11 instead
2. Until 2018-08-2 every upgrade is working and i'm able to use tine, beginning with 2018-08-3 the upgrade works, but i get the endless loading screen

**Comment by crosenbe** [comment]
It's probably more related to a GUI/Frontend issue, switching back to 2018-08-2 with the already migrated database shows the login screen, 2018-08-3 still not. 

I have not seen any interesting line in the debug log.

```
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 INFO (6): Tinebase_Core::setupLogger::797 Logger initialized.
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 DEBUG (7): Tinebase_Core::setupCache::849 Cache logging disabled
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 INFO (6): Tinebase_Core::setupCache::918 cache of backend type 'File' enabled
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1039 Creating Pdo_Mysql DB adapter (db name: tinedb)
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1057 Using MySQL charset: utf8mb4
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1075 Falling back to utf-8 charset
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 INFO (6): Tinebase_Core::setupCache::926 Cache disabled
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1200 given localeString 'auto'
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1227 Try to detect the locale of the user (browser, environment, default)
c1f1a -- none -- - 2019-02-03T07:25:38+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 INFO (6): Tinebase_Core::setupUserLocale::1251 Setting user locale: de
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1258 Setting CTYPE locale from "C" to "en_US.UTF8".
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Setup_Server_Http::handle::35 is http request. method:
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::607 Loading all configs for app Tinebase
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::625 Found 22 configs.
c1f1a -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::528 Looking for defaults config.inc.php at /opt/tine/2018-08-3/Tinebase/config.inc.php
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 INFO (6): Tinebase_Core::setupLogger::797 Logger initialized.
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::setupCache::849 Cache logging disabled
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 INFO (6): Tinebase_Core::setupCache::918 cache of backend type 'File' enabled
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1039 Creating Pdo_Mysql DB adapter (db name: tine_db)
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1057 Using MySQL charset: utf8mb4
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1075 Falling back to utf-8 charset
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 INFO (6): Tinebase_Core::setupCache::926 Cache disabled
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1200 given localeString 'auto'
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1227 Try to detect the locale of the user (browser, environment, default)
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 INFO (6): Tinebase_Core::setupUserLocale::1251 Setting user locale: de
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1258 Setting CTYPE locale from "C" to "en_US.UTF8".
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Setup_Server_Http::handle::35 is http request. method:
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::607 Loading all configs for app Tinebase
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::625 Found 22 configs.
b76d0 -- none -- - 2019-02-03T07:25:39+00:00 DEBUG (7): Tinebase_Config_Abstract::_getAppDefaultsConfigFileData::528 Looking for defaults config.inc.php at /opt/tine/2018-08-3/Tinebase/config.inc.php
```

**Comment by crosenbe** [comment]
I restarted from scratch, my first issue disappeared, don't know why. I followed your recommendation, but with the same result. I'm always upgrading on the command line.

```
Upgrade to 2017-02-1

root@app:/opt/tine/2017-02-1# php setup.php --update
Updated 10 application(s).
Updated 4 application(s).
root@app:/opt/tine/2017-02-1#

Upgrade to 2018-08-1

root@app:/opt/tine/2017-08-1# php setup.php --update
Updated 9 application(s).
root@app:/opt/tine/2017-08-1#

Upgrade to 2018-08-11

root@app:/opt/tine/2017-08-11# php setup.php --update
Updated 3 application(s).
root@app:/opt/tine/2017-08-11#

Upgrade to 2018-02-7

root@app:/opt/tine/2018-02-7# php setup.php --update
Updated 9 application(s).
Updated 3 application(s).
root@app:/opt/tine/2018-02-7#

Upgrade to 2018-08-9

root@app:/opt/tine/2018-08-9# php setup.php --update
Updated 7 application(s).
root@app:/opt/tine/2018-08-9#
```

**Comment by crosenbe** [comment]
Running the GUI shows following entries in the logs. I also cleared cache, tmp and session directories.

```
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::setupLogger::821 Logger initialized.
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): index.php (20) Start processing request (PID: 20288)
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupCache::873 Cache logging disabled
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::setupCache::942 cache of backend type 'File' enabled
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1353 setting execution life time to: 0
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1063 Creating Pdo_Mysql DB adapter (db name: tinedb)
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1082 Using MySQL charset: utf8mb4
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1101 Falling back to utf-8 charset
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1146  connection id: 833
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::407 Session options: Array
(
    [name] => TINE20SESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] =>
)

9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::617 Loading all configs for app Tinebase
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::635 Found 22 configs.
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::initFramework::456 initializing framework (PID: 20288)
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1235 given localeString 'auto'
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1262 Try to detect the locale of the user (browser, environment, default)
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::setupUserLocale::1286 Setting user locale: de
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1293 Setting CTYPE locale from "C" to "en_US.UTF8".
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method:
9a9a9 -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::246 FILE: index.php METHOD: Tinebase_Server_Http::Tinebase.login / TIME: 17ms /  Memory usage: 4 MB /  Real patch cache size: 139615 / PID: 20288
b618b -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::setupLogger::821 Logger initialized.
b618b -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): index.php (20) Start processing request (PID: 20295)
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupCache::873 Cache logging disabled
b618b -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::setupCache::942 cache of backend type 'File' enabled
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Session_Abstract::setSessionOptions::407 Session options: Array
(
    [name] => TINE20SESSID
    [cookie_httponly] => 1
    [hash_function] => 1
    [cookie_path] =>
)

b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::617 Loading all configs for app Tinebase
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1063 Creating Pdo_Mysql DB adapter (db name: tinedb)
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1082 Using MySQL charset: utf8
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1146  connection id: 834
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Config_Abstract::_loadAllAppConfigsInCache::635 Found 22 configs.
b618b -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::initFramework::456 initializing framework (PID: 20295)
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1235 given localeString 'auto'
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1262 Try to detect the locale of the user (browser, environment, default)
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Translation::getLocale::199 given localeString 'auto'
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Translation::getLocale::212 'de' is not supported, checking fallback
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Translation::getLocale::238 selected locale: 'de'
b618b -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Core::setupUserLocale::1286 Setting user locale: de
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1293 Setting CTYPE locale from "C" to "en_US.UTF8".
b618b -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method:
b618b -- none -- - 2019-02-04T11:40:17+00:00 DEBUG (7): Tinebase_Core::setExecutionLifeTime::1353 setting execution life time to: 0
b618b -- none -- - 2019-02-04T11:40:17+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::246 FILE: index.php METHOD: Tinebase_Server_Http::Tinebase.login / TIME: 13ms /  Memory usage: 4 MB /  Real patch cache size: 114390 / PID: 20295

```

**Comment by crosenbe** [comment]
As stated in the upgrade documentation it should be done as followed.

```
2013.03, 2013.10, 2014.09, 2014.11, 2015.07, 2015.11, 2016.03, 2016.11, 2016.09 -> 2017.02 Community Edition

2017.02 -> 2017.08 Community Edition

2017.08 -> 2018.02 Community Edition

2018.02 -> 2018.08 Community Edition
```

I start with 2016.03, results in this upgrade path, between 2017.02.1 and 2017.08.11 i got an exception.

2016.03 -> 2017.02.1 -> 2017.08.11 -> 2018.02.7 -> 2018.08.9

```
root@app:/opt/tine/2017-08-11# php setup.php --update
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rocnet_de.tine20_scheduler_task' doesn't exist in /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `schedul...', Array)
#4 /opt/tine/2017-08-11/Tinebase/Backend/Scheduler.php(42): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /opt/tine/2017-08-11/Tinebase/Scheduler.php(164): Tinebase_Backend_Scheduler->hasTask('Tineb in /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tinedb.tine20_scheduler_task' doesn't exist in /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#2 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `schedul...', Array)
#4 /opt/tine/2017-08-11/Tinebase/Backend/Scheduler.php(42): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select))
#5 /opt/tine/2017-08-11/Tinebase/Scheduler.php(164): Tinebase_Backend_Scheduler->hasTask('Tineb in /opt/tine/2017-08-11/vendor/zendframework/zendframework1/library/Zend/Db/Statement/Pdo.php on line 235
root@app:/opt/tine/2017-08-11#
```

**Comment by crosenbe** [comment]
I didn't find this versions to download, but until 2018.08.2 it worked anyway. Beginning with 2018.08.3 it stopped working.

**Comment by lab-at-nohl** [comment]
Now I am totally lost. You wrote

> I start with 2016.03, results in this upgrade path, between 2017.02.1 and 2017.08.11 i got an exception.

Did you skip this part to avoid the exception?

Where are you now? Did 2018.02.7 --> 2018.08.9 work for you?

**Comment by crosenbe** [comment]
The upgrade works, but i have a endless loading screen.

```
Upgrade to 2018-02-7

root@app:/opt/tine/2018-02-7# php setup.php --update
Updated 9 application(s).
Updated 3 application(s).
root@app:/opt/tine/2018-02-7#

Upgrade to 2018-08-9

root@app:/opt/tine/2018-08-9# php setup.php --update
Updated 7 application(s).
root@app:/opt/tine/2018-08-9#
```

If i do an upgrade from 2018.02.7 to 2018.08.2 instead i get a loading screen.

**Comment by lab-at-nohl** [comment]
If the "endless loop" is the problem, you should offer a more complete log-File at DEBUG level. The first column always mark one request. It would be helpful to see at least one full thread.

**Comment by crosenbe** [comment]
i added several log files, with debug level. Unfortunately nothing interesting in.

**Comment by crosenbe** [comment]
I identified the issue, i use a reverse proxy in front of tine, the proxy provides HTTPS, the backend provides HTTP to the reverse proxy. This worked until 2018-08-2, starting with 2018-08-3 the generated page links to HTTP js files. Before 2018-08-3 is was a relative path. The translation from HTTPS to HTTP on the reverse proxy does not work anymore.

Why the link to the JS files is absolute now?

```
<script type="text/javascript" src="http://tine.myserver.de/Setup/js/fatClient.js-c79fcf9f7cddb7b5e69e-FAT.js"></script>
<script type="text/javascript" src="http://tine.myserver.de/index.php?method=Tinebase.getJsTranslations&locale=de&app=all&version=ce92dfccacd6bf202116c419e856ffea17b37604"></script>
```

**Comment by crosenbe** [comment]
```
--- 2018-08-9/Tinebase/Frontend/Http/SinglePageApplication.php.orig     2019-02-13 09:12:54.090982748 +0100
+++ 2018-08-9/Tinebase/Frontend/Http/SinglePageApplication.php  2019-02-13 09:13:02.762982748 +0100
@@ -35,7 +35,7 @@
                 $file = preg_replace('/\.js$/', '.debug.js', $file);
             }

-            return '<script type="text/javascript" src="' . $baseUrl . '/' . $file .'"></script>';
+            return '<script type="text/javascript" src="' . '/' . $file .'"></script>';
         }, ['is_safe' => ['all']]));

         $textTemplate = $twig->load($template);

```

**Comment by paulmhh** [comment]
thank you very much for pointing this out. I think the best approach is to leave out the protocol only
<script type="text/javascript" src="http://tine.myserver.de/Set
=>
<script type="text/javascript" src="//tine.myserver.de/Set

will prepare a change to fix this

**Comment by paulmhh** [comment]
btw. you can configure the tine url, which would resolve your issue (if you configure it with https, which you definitely should, otherwise you will get more of those http links, in notification emails, etc. whereever a link is generated)

**Comment by crosenbe** [comment]
In myurl/setup.php or in config.inc.php?

**Comment by paulmhh** [comment]
config.inc.php for sure, other options (setup/admin) I dont know

**Comment by crosenbe** [comment]
Don't know if i missed it, but https://github.com/tine20/tine20/blob/master/tine20/docs/config.inc.php.dist tells nothing how to configure the BaseUrl.

**Comment by paulmhh** [comment]
https://github.com/tine20/tine20/blob/master/tine20/Tinebase/Config.php
does, TINE20_URL = 'tine20Url'; (so you use 'tine20URL' => 'https://mydomain.tld/tine20/orOtherBasePaths'; ... I guess at least, didn't look into the details)

**Comment by paulmhh** [comment]
self::TINE20_URL  => array(
            //_('Tine20 URL')
            'label' => 'Tine20 URL',
            //_('The full URL including scheme, hostname, optional port and optional uri part under which tine20 is reachable.')
            'description' => 'The full URL including scheme, hostname, optional port and optional uri part under which tine20 is reachable.',
