### ISSUE TITLE
Felamimail fails to preview mails with *.ics attachment

### ISSUE THREAD

**Issue by msphn** [tine20/tine20#7024]
I received some calendar exports from apple calendar attached in mails. When I click on those mails Tine 2.0 tries to evaluate those files and cope with them expecting it to be an external invitation using iMIP.

Not sure how to distinguish between an actual iMIP invitation and an ics file send via mail. If there is any chance it would be best to just show the mail with the ics attachment and not trying to parse it.

```
f12d5 michaels - 2019-05-02T10:26:36+00:00 ERR (3): Tinebase_Server_Json::_handleException::414 Sabre\VObject\ParseException -> Invalid Mimedir file. Line starting at 30589 did not follow iCalendar/vCard conventions
 f12d5 michaels - 2019-05-02T10:26:36+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Sabre\VObject\ParseException -> Invalid Mimedir file. Line starting at 30589 did not follow iCalendar/vCard conventions
 f12d5 michaels - 2019-05-02T10:26:36+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/sabre/vobject/lib/Parser/MimeDir.php(189): Sabre\VObject\Parser\MimeDir->readProperty('TAT=ACCEPTED;X-...')
#1 .../vendor/sabre/vobject/lib/Parser/MimeDir.php(172): Sabre\VObject\Parser\MimeDir->parseLine('TAT=ACCEPTED;X-...')
#2 .../vendor/sabre/vobject/lib/Parser/MimeDir.php(137): Sabre\VObject\Parser\MimeDir->parseLine('TAT=ACCEPTED;X-...')
#3 .../vendor/sabre/vobject/lib/Parser/MimeDir.php(63): Sabre\VObject\Parser\MimeDir->parseDocument()
#4 .../vendor/sabre/vobject/lib/Reader.php(44): Sabre\VObject\Parser\MimeDir->parse('BEGIN:VCALENDAR...', 0)
#5 .../Tinebase/Convert/VCalendar/Abstract.php(93): Sabre\VObject\Reader::read('BEGIN:VCALENDAR...')
#6 .../Tinebase/Convert/VCalendar/Abstract.php(64): Tinebase_Convert_VCalendar_Abstract::readVCalBlob('BEGIN:VCALENDAR...')
#7 .../Calendar/Convert/Event/VCalendar/Abstract.php(418): Tinebase_Convert_VCalendar_Abstract::getVObject('BEGIN:VCALENDAR...')
#8 .../Calendar/Model/iMIP.php(194): Calendar_Convert_Event_VCalendar_Abstract->toTine20Model('BEGIN:VCALENDAR...')
#9 .../Calendar/Model/iMIP.php(171): Calendar_Model_iMIP->getEvent()
#10 .../Calendar/Frontend/iMIP.php(119): Calendar_Model_iMIP->__get('method')
#11 .../Calendar/Frontend/iMIP.php(89): Calendar_Frontend_iMIP->_checkPreconditions(Object(Calendar_Model_iMIP), false)
#12 .../Felamimail/Frontend/Json.php(372): Calendar_Frontend_iMIP->prepareComponent(Object(Calendar_Model_iMIP), false)
#13 .../Felamimail/Frontend/Json.php(205): Felamimail_Frontend_Json->_recordToJson(Object(Felamimail_Model_Message))
#14 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json->getMessage('8a8e5f25d8fcab1...', 'text/html')
#15 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#16 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#17 .../Tinebase/Server/Json.php(388): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#18 .../Tinebase/Server/Json.php(162): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#19 .../Tinebase/Core.php(261): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#20 .../index.php(24): Tinebase_Core::dispatchRequest()
#21 {main}
```

**Comment by pschuele** [comment]
incoming fix ...

**Comment by msphn** [comment]
Uhhh nice! Im currently unable to update so I won't be able to verify :/ Sorry

**Comment by pschuele** [comment]
no probs, just check it when you can. the fix is straight forward (just catch the exception in Felamimail_Frontend_Json->_recordToJson) ;)

**Comment by msphn** [comment]
@Felamimail_Frontend_Json->_recordToJson 🤣
