### ISSUE TITLE
Upgrade to 2019.08.02-1.10nnn fails

### ISSUE THREAD

**Issue by pij** [tine20/tine20#7099]
Running Setup after upgrade of the Debian package to the latest Release (2019.08.02-1.10nnn) fails. Output of 
$PHP -d include_path=/etc/tine20:/usr/share/tine20 /usr/share/tine20/setup.php --list
$PHP -d include_path=/etc/tine20:/usr/share/tine20 /usr/share/tine20/setup.php --update

Currently installed applications:
* Projects (Version: 12.0)
* Admin (Version: 12.0)
* Felamimail (Version: 12.8)
* Tinebase (Version: 12.26)
* Filemanager (Version: 12.1)
* Tasks (Version: 12.4)
* ActiveSync (Version: 12.1)
* Calendar (Version: 12.10)
* Addressbook (Version: 12.7)
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /usr/share/tine20/Addressbook/Controller/Contact.php:1114
Stack trace:
#0 /usr/share/tine20/Calendar/Controller/MSEventFacade.php(117): Addressbook_Controller_Contact::inspectAddUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#1 /usr/share/tine20/Calendar/Controller/Event.php(111): Calendar_Controller_MSEventFacade::getCurrentUserContactId()
#2 /usr/share/tine20/Calendar/Controller/Event.php(131): Calendar_Controller_Event->__construct()
#3 /usr/share/tine20/Tinebase/Core.php(443): Calendar_Controller_Event::getInstance()
#4 /usr/share/tine20/Tinebase/Container.php(1244): Tinebase_Core::getApplicationInstance('Calendar_Model_...', '', true)#5 /usr/share/tine20/Tinebase/Container.php(1191): Tinebase_Container->deleteContainerContents(Object(Tinebase_Model_Container), true)
#6 /usr/share/tine20/Tinebase/Container.php(2301): Tinebase_Container->deleteContainer('610798413de61ec...', true)
#7 /usr/share/tine20/Calendar/Setup/Update/1 in /usr/share/tine20/Addressbook/Controller/Contact.php on line 1114

Fatal error: Uncaught Error: Using $this when not in object context in /usr/share/tine20/Addressbook/Controller/Contact.php:1114
Stack trace:
#0 /usr/share/tine20/Calendar/Controller/MSEventFacade.php(117): Addressbook_Controller_Contact::inspectAddUser(Object(Tinebase_Model_FullUser), Object(Tinebase_Model_FullUser))
#1 /usr/share/tine20/Calendar/Controller/Event.php(111): Calendar_Controller_MSEventFacade::getCurrentUserContactId()
#2 /usr/share/tine20/Calendar/Controller/Event.php(131): Calendar_Controller_Event->__construct()
#3 /usr/share/tine20/Tinebase/Core.php(443): Calendar_Controller_Event::getInstance()
#4 /usr/share/tine20/Tinebase/Container.php(1244): Tinebase_Core::getApplicationInstance('Calendar_Model_...', '', true)#5 /usr/share/tine20/Tinebase/Container.php(1191): Tinebase_Container->deleteContainerContents(Object(Tinebase_Model_Container), true)
#6 /usr/share/tine20/Tinebase/Container.php(2301): Tinebase_Container->deleteContainer('610798413de61ec...', true)
#7 /usr/share/tine20/Calendar/Setup/Update/1 in /usr/share/tine20/Addressbook/Controller/Contact.php on line 1114

(Sory for line wrapping)
It seems Addressbook_Controller_Contact::inspectAddUser is indeed called as a static function, leading to the problem.

**Comment by pij** [comment]
Adding a "getInstance()->" before "inspectAddUser" fixes the problem.

**Comment by gerryfrancis** [comment]
See https://github.com/tine20/tine20/issues/7090 for solution.
