### ISSUE TITLE
HTTP 500 after upgrade from 2019.08.4 to 2019.12.2 from previous version

### ISSUE THREAD

**Issue by ravermeister** [tine20/tine20#7118]
Hi, after doing the Upgrade from 2019.08.4 to 2019.12.2 (from github release zip) I get following error:
What am I doing wrong?
```
01c6f - -- none -- - 2019-12-20T01:15:36+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Http/Client.php(1073): Zend_Http_Client_Adapter_Socket->connect('tcp://localhost', '10443', false)
#1 .../Tinebase/Helper.php(438): Zend_Http_Client->request()
#2 .../Tinebase/Frontend/Http/SinglePageApplication.php(111): Tinebase_Helper::getFileOrUriContents('http://localhos...')
#3 .../Tinebase/Frontend/Http/SinglePageApplication.php(132): Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap()
#4 .../Tinebase/Frontend/Http/SinglePageApplication.php(44): Tinebase_Frontend_Http_SinglePageApplication::getAssetHash()
#5 .../Tinebase/Frontend/Http.php(335): Tinebase_Frontend_Http_SinglePageApplication::getClientHTML(Array, 'Tinebase/views/...')
#6 .../Tinebase/Frontend/Http.php(214): Tinebase_Frontend_Http->mainScreen()
#7 [internal function]: Tinebase_Frontend_Http->login()
#8 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs(Object(Tinebase_Frontend_Http), Array)
#9 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call('invokeArgs', Array)
#10 .../Tinebase/Server/Http.php(103): Tinebase_Http_Server->handle(Array)
#11 .../Tinebase/Core.php(267): Tinebase_Server_Http->handle(Object(Tinebase_Http_Request))
#12 .../index.php(24): Tinebase_Core::dispatchRequest()
#13 {main}
01c6f - -- none -- - 2019-12-20T01:15:36+00:00 ERR (3): Tinebase_Frontend_Http_SinglePageApplication::Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap (113) Could not get json file: Tinebase/js/webpack-assets-FAT.json
01c6f - -- none -- - 2019-12-20T01:15:36+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Exception -> You need to run webpack-dev-server in dev mode! See https://wiki.tine20.org/Developers/Getting_Started/Working_with_GIT#Install_webpack
01c6f - -- none -- - 2019-12-20T01:15:36+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../Tinebase/Frontend/Http/SinglePageApplication.php(132): Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap()
#1 .../Tinebase/Frontend/Http/SinglePageApplication.php(44): Tinebase_Frontend_Http_SinglePageApplication::getAssetHash()
#2 .../Tinebase/Frontend/Http.php(335): Tinebase_Frontend_Http_SinglePageApplication::getClientHTML(Array, 'Tinebase/views/...')
#3 .../Tinebase/Frontend/Http.php(214): Tinebase_Frontend_Http->mainScreen()
#4 [internal function]: Tinebase_Frontend_Http->login()
#5 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs(Object(Tinebase_Frontend_Http), Array)
#6 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call('invokeArgs', Array)
#7 .../Tinebase/Server/Http.php(103): Tinebase_Http_Server->handle(Array)
#8 .../Tinebase/Core.php(267): Tinebase_Server_Http->handle(Object(Tinebase_Http_Request))
#9 .../index.php(24): Tinebase_Core::dispatchRequest()
#10 {main}
```

**Comment by johnassel** [comment]
Hi!
I had the same problem and could solve it by adding
`'buildtype' => 'RELEASE',`
into config.inc.php.
The switch is documented [here](https://github.com/tine20/tine20/wiki/EN:build-from-git) but it doesn't appear in the sample config or installation manuals.

I think it is caused by
`        // allow to overwrite buildtype via Tinebase/config.inc.php
        $buildType = $config->get(Tinebase_Config::BUILD_TYPE);
        if (! $buildType) {
            $buildType = 'DEVELOPMENT';
        }`
found in Tinebase/Core.php in lines 653-657 but I can't confirm that.
"You need to run webpack-dev-server in dev mode!" got me somehow there.

**Comment by pschuele** [comment]
hi, thanks for the bugreport.
we are investigating the issue.
the hotfix suggested by @johnassel should work. but the setting should not be necessary and 'RELEASE' the default ...

**Comment by pschuele** [comment]
... found the problem.
we'll build version 2019.12.3 now ...

**Comment by ravermeister** [comment]
Hi, 
I can Confirm that the Workaround **and** the new Version `2019.12.3` 
are solving the issue. 

Thanks for the fast help, wish you all merry Christmas and a Happy new Year

**Comment by pschuele** [comment]
> I can Confirm that the Workaround and the new Version 2019.12.3
are solving the issue.
Thanks for the fast help, wish you all merry Christmas and a Happy new Year

thanks for reporting & testing :)

merry Christmas!
