### ISSUE TITLE
Error when forwarding mail with attachment (2019.12.2)

### ISSUE THREAD

**Issue by j-a-n** [tine20/tine20#7119]
With version 2019.12.2 it is not possible to forward mails:
```
2019-12-20T09:24:17+01:00 WARN (4): Felamimail_Controller_Message_Send::sendMessage::107 Could not send message: Tinebase_Exception_NotFound: Tinebase_Model_Tree_Node record with id = 4873790b73906306eec46359befff52349e736e3 not found! in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:314
Stack trace:
#0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(282): Tinebase_Backend_Sql_Abstract->getRawDataByProperty('4873790b7390630...', 'id', false)
#1 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(251): Tinebase_Backend_Sql_Abstract->getByProperty('4873790b7390630...', 'id', false)
#2 /usr/share/tine20/Tinebase/FileSystem.php(274): Tinebase_Backend_Sql_Abstract->get('4873790b7390630...', false)
#3 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(525): Tinebase_FileSystem->get('4873790b7390630...', false)
#4 /usr/share/tine20/Filemanager/Controller/Node.php(341): Tinebase_Controller_Record_Abstract->get('4873790b7390630...', NULL, true, false)
#5 /usr/share/tine20/Felamimail/Controller/Message/Send.php(964): Filemanager_Controller_Node->get('4873790b7390630...')
#6 /usr/share/tine20/Felamimail/Controller/Message/Send.php(794): Felamimail_Controller_Message_Send->_getFileNodeAttachment(Array)
#7 /usr/share/tine20/Felamimail/Controller/Message/Send.php(725): Felamimail_Controller_Message_Send->_getAttachmentPartByType(Array, Object(Felamimail_Model_Message))
#8 /usr/share/tine20/Felamimail/Controller/Message/Send.php(300): Felamimail_Controller_Message_Send->_addAttachments(Object(Tinebase_Mail), Object(Felamimail_Model_Message))
#9 /usr/share/tine20/Felamimail/Controller/Message/Send.php(104): Felamimail_Controller_Message_Send->createMailForSending(Object(Felamimail_Model_Message), Object(Felamimail_Model_Account), Array)
#10 /usr/share/tine20/Felamimail/Frontend/Json.php(245): Felamimail_Controller_Message_Send->sendMessage(Object(Felamimail_Model_Message))
#11 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(232): Felamimail_Frontend_Json->saveMessage(Array)
#12 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(590): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#13 /usr/share/tine20/vendor/zendframework/zendframework1/library/Zend/Json/Server.php(197): Zend_Json_Server->_handle()
#14 /usr/share/tine20/Tinebase/Server/Json.php(398): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#15 /usr/share/tine20/Tinebase/Server/Json.php(167): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#16 /usr/share/tine20/Tinebase/Core.php(267): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#17 /usr/share/tine20/index.php(24): Tinebase_Core::dispatchRequest()
#18 {main}
```

**Comment by j-a-n** [comment]
The error only occurs if the forwarded mail contains an attachment.

**Comment by pschuele** [comment]
yup, I can reproduce it. working on a fix!

thanks for reporting @j-a-n

**Comment by j-a-n** [comment]
Temporary workaround:
```
--- /usr/share/tine20/Felamimail/Controller/Message/Send.php.orig	2019-12-20 09:46:10.394533268 +0100
+++ /usr/share/tine20/Felamimail/Controller/Message/Send.php	2019-12-20 09:47:21.531014399 +0100
@@ -791,7 +791,11 @@
                 $this->_setDownloadLinkAttachment($attachment, $_message, /* protected */ true);
                 break;
             case 'filenode':
-                $part = $this->_getFileNodeAttachment($attachment);
+                try {
+                   $part = $this->_getFileNodeAttachment($attachment);
+                } catch (Exception $e) {
+                   $part = $this->_getRfc822Attachment($attachment, $_message);
+                }
                 break;
             case 'tempfile':
                 $part = $this->_getTempFileAttachment($attachment);
```

**Comment by pschuele** [comment]
thanks for the workaround. i just spotted the problem (in _getAttachmentType) and will commit a fix very soon.

**Comment by j-a-n** [comment]
Thank you for the quick fix @pschuele
