### ISSUE TITLE
Exception in Syncroton_Server causes high cpu load

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7139]
I'm not sure what causes this, but I assume an Outlook user is adding an appointment.
The error is repeated every 700ms. Outlook is not able to handle this and repeats its request almost instantly.

1. Bug should be fixed, since this causes high cpu load (denial of service)
2. Exceptions in Synchrontron should give the client some error to handle - or at least have an delay so they don't just rerequest (like buggy outlook)

```
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #11 {main}
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #10 /mnt/www/tine/index.php(24): Tinebase_Core::dispatchRequest()
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #9 /mnt/www/tine/Tinebase/Core.php(267): ActiveSync_Server_Http->handle(Object(Zend_Controller_Request_Http))
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #8 /mnt/www/tine/ActiveSync/Server/Http.php(92): Syncroton_Server->handle()
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #7 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server->_handlePost()
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #6 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_MeetingResponse->handle()
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #5 /mnt/www/tine/vendor/syncroton/syncroton/lib/Syncroton/Command/MeetingResponse.php(38): Calendar_Frontend_ActiveSync->setAttendeeStatus(Object(Syncroton_Model_MeetingResponse))
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #4 /mnt/www/tine/Calendar/Frontend/ActiveSync.php(224): Calendar_Controller_MSEventFacade->get('53e5ee7d00cefc4...')
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #3 /mnt/www/tine/Calendar/Controller/MSEventFacade.php(134): Calendar_Controller_Event->get('53e5ee7d00cefc4...')
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #2 /mnt/www/tine/Calendar/Controller/Event.php(1562): Tinebase_Controller_Record_Abstract->get('53e5ee7d00cefc4...', NULL, true, false)
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: #1 /mnt/www/tine/Tinebase/Controller/Record/Abstract.php(504): Tinebase_Backend_Sql_Abstract->get('53e5ee7d00cefc4...', false)
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: Syncroton_Server::_handlePost::168 #0 /mnt/www/tine/Tinebase/Backend/Sql/Abstract.php(251): Calendar_Backend_Sql->getByProperty('53e5ee7d00cefc4...', 'id', false)
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: Syncroton_Server::_handlePost::166 exception message: Calendar_Model_Event record with id 53e5ee7d00cefc4f381b23ccf9d96b25099d63a5 not found!
Jan 24 09:21:23 julius php-fpm[7017]: Tine 2.0[7017]: Syncroton_Server::_handlePost::164 unexpected exception occured: Tinebase_Exception_NotFound

```

**Comment by pschuele** [comment]
I'll have a look at this. maybe it helps to convert the exception to a Syncroton_Exception_NotFound.
