### ISSUE TITLE
Can´t update from 2019.08.1 to 2019.08.4 failed to create hash file

### ISSUE THREAD

**Issue by JPRuehmann** [tine20/tine20#7185]
I had a working 2019.08.1 installation.
By overwriting it with the following Command I get the error below.

`sudo -u www-data unzip -q /home/ruehmann/Downloads/tine20-allinone_2019.08.4.zip -d /var/www/html/Tine20
`
```
setup.php --update                                                                                                                                   
Tinebase_Exception_UnexpectedValue: failed to create hash file in /var/www/html/Tine20/Tinebase/FileSystem.php:2196
Stack trace:
#0 /var/www/html/Tine20/Tinebase/FileSystem.php(617): Tinebase_FileSystem->createFileBlob(Resource id #948)
#1 /var/www/html/Tine20/Setup/Controller.php(2291): Tinebase_FileSystem->fclose(Resource id #948)
#2 /var/www/html/Tine20/Setup/Controller.php(2316): Setup_Controller->{closure}(Object(DirectoryIterator), Object(Tinebase_FileSystem), Object(Tinebase_Model_Tree_Node_Path))
#3 /var/www/html/Tine20/Setup/Controller.php(670): Setup_Controller->createImportExportDefinitions(Object(Tinebase_Model_Application), false)
#4 /var/www/html/Tine20/Setup/Controller.php(655): Setup_Controller->updateAllImportExportDefinitions()
#5 /var/www/html/Tine20/Setup/Controller.php(522): Setup_Controller->_legacyUpdateApplications(Object(Tinebase_Record_RecordSetFast))
#6 /var/www/html/Tine20/Setup/Frontend/Cli.php(467): Setup_Controller->updateApplications()
#7 /var/www/html/Tine20/Setup/Frontend/Cli.php(451): Setup_Frontend_Cli->_updateApplications()
#8 /var/www/html/Tine20/Setup/Frontend/Cli.php(81): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#9 /var/www/html/Tine20/Setup/Server/Cli.php(141): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#10 /var/www/html/Tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#11 /var/www/html/Tine20/setup.php(14): Setup_Core::dispatchRequest()
#12 {main}

```
Is there a Way to make it work?
The Updates before since 2017.02.1 work normaly.

**Comment by JPRuehmann** [comment]
Hello
using `sudo -u www-data php setup.php --config config.inc.php --update` instead of `setup.php --update` did the Trick.
Thanks,
