### ISSUE TITLE
Unable to sync confirmed calendar appointment in Outlook

### ISSUE THREAD

**Issue by Mic-net** [tine20/tine20#7187]
Hello,
unable to sync confirmed calendar appointment in Outlook (MS Outlook for Microsoft 365 MSO (16.0.12827.20236) 64bit) that was sent by a user from Gmail. The meeting in "Felamimail" can be confirmed and correctly sync. (An appointment created in Outlook is synchronized properly.)

In Outlook, the meeting is saved to the calendar and Outlook is "Waiting for server".

I use ActiveSync version 12.1

In the log on the server I see:

`e42961 - ****@****.eu - 2020-06-18T08:23:02+00:00 CRIT (2): Syncroton_Server::_handlePost::164 unexpected exception occured: Tinebase_Exception_NotFound
e42961 - ****@****.eu - 2020-06-18T08:23:02+00:00 CRIT (2): Syncroton_Server::_handlePost::166 exception message: Calendar_Model_Event record with id 87e129a5c3d3006959dc1ad879cfd852e3b96d11 not found!
e42961 - ****@****.eu - 2020-06-18T08:23:02+00:00 CRIT (2): Syncroton_Server::_handlePost::168 #0 /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php(251): Calendar_Backend_Sql->getByProperty('87e129a5c3d3006...', 'id', false)
#1 /usr/share/tine20/Tinebase/Controller/Record/Abstract.php(525): Tinebase_Backend_Sql_Abstract->get('87e129a5c3d3006...', false)
#2 /usr/share/tine20/Calendar/Controller/Event.php(1583): Tinebase_Controller_Record_Abstract->get('87e129a5c3d3006...', NULL, true, false)
#3 /usr/share/tine20/Calendar/Controller/MSEventFacade.php(134): Calendar_Controller_Event->get('87e129a5c3d3006...')
#4 /usr/share/tine20/Calendar/Frontend/ActiveSync.php(224): Calendar_Controller_MSEventFacade->get('87e129a5c3d3006...')
#5 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Command/MeetingResponse.php(38): Calendar_Frontend_ActiveSync->setAttendeeStatus(Object(Syncroton_Model_MeetingResponse))
#6 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(144): Syncroton_Command_MeetingResponse->handle()
#7 /usr/share/tine20/vendor/syncroton/syncroton/lib/Syncroton/Server.php(70): Syncroton_Server->_handlePost()
#8 /usr/share/tine20/ActiveSync/Server/Http.php(96): Syncroton_Server->handle()
#9 /usr/share/tine20/Tinebase/Core.php(267): ActiveSync_Server_Http->handle(Object(Zend_Controller_Request_Http))
#10 /usr/share/tine20/index.php(24): Tinebase_Core::dispatchRequest()
#11 {main}
`

Is it my fault or application?

**Comment by pschuele** [comment]
looks like an application (maybe tine, maybe outlook does strange stuff) problem. could you please switch the logger to DEBUG and send the complete request (Syncroton_Command_MeetingResponse) log?

**Comment by Mic-net** [comment]
I'm attaching a debug log, due to the large size I compressed the file. Is it allright like this?

[tine20.zip](https://github.com/tine20/tine20/files/4799508/tine20.zip)

**Comment by lab-at-nohl** [comment]
I do not have a solution. But in your log-File the same event id (=requestId) is searched for about 2000 times. And the id is different than the one above. Do you have ids like
- 87e129a5c3d3006959dc1ad879cfd852e3b96d11
- fe22e5e0d4539a253df3a6848f5bf9652293b15a

in the MySQL table `tine20_cal_events`? While no proper response to the client occurs, I guess the client will retry even 2000 times...

````
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE AirSync PUBLIC "-//AIRSYNC//DTD AirSync//EN" "http://www.microsoft.com/">
<MeetingResponse xmlns="uri:MeetingResponse">
  <Result>
    <CalendarId>9218213bb757319be01b0a9b62d02a4f5f5a9dd7</CalendarId>
    <Status>4</Status>
    <RequestId>fe22e5e0d4539a253df3a6848f5bf9652293b15a</RequestId>
  </Result>
</MeetingResponse>
````

Status 4 means *ErrorOccurredOnExchangeServer*, which includes "the meeting may have been canceled" (see [documentation](https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-interoperability-guidance/hh428685(v%3Dexchg.140))). 

Just my two cents.

**Comment by lab-at-nohl** [comment]
Hello @Mic-net, 

I could not fully reproduce your problem because I do not have Outlook (other clients seems to be less strict). But I might have found the cause for the retries of Outlook, Due to a missing response that the client advises not to retry again in case an error occures, the client tries to set attendee status over and over again... I assume you have deleted the event before Outlooks request was processed (that happens easily whenever the queue takes some time). 

Do you have little experience in editing program files (for testing purposes you would have to replace one line by five new lines in a php file)? If so, see my [patch](https://github.com/tine20/tine20/commit/6053a94595b0fd93a4de44d952106ce4adaa6644) and please report any problems. 

The patch basically triggers the above mentioned result that the client expects. It was already implemented in Syncroton library but the trigger in Tine 2.0 was missing. I added this for cases of "not found". 

Regards
Johannes

**Comment by Mic-net** [comment]
Hello,
after applying the patch, Outlook will now finish syncing the received appointment from Gmail. This event will show up in me phone calendar (Android), but not show up in Outlook on another computer, nor will it show up in Felamimail calendar.

If you want, I could prepare a computer with remote access with Outlook in an isolated network.

Best regards,
Mic

**Comment by lab-at-nohl** [comment]
Thank you for the qualified feedback. The SQL results show that the event does not exist anymore. Thus, neither Tine 2.0 Calendar nor Outlook shows it. I cannot say why it remains on Android, maybe you just have to wait some time (but it should not be there)... 

I would recommend to test once more with a **new event** from Gmail. The following pattern may reproduce:  

1. Close Outlook, create an event with Gmail and invite the Tine 2.0 user
2. Confirm the event in Tine 2.0 Felamimail 
3. Delete the event in Tine 2.0 Calendar
4. Open Outlook...

Regards
Johannes

**Comment by Mic-net** [comment]
The above test scenario will run fine, except for one detail, I still see this deleted event on my phone (Android calendar).

And second:
If I look at the table:
SELECT * FROM tine20_cal_events ORDER BY creation_time DESC;

Thus, an event created in the Gmail calendar and confirmed in Outlook will not create a new record in this table.

Maybe there is a problem with the slow server because I am using a server built on the Raspberry Pi 4B (4GB RAM). And can there be any timeout?

**Comment by lab-at-nohl** [comment]
Ah ok, I got it now. You try to confirm an event **that has not been processed by Tine 2.0** before because it was not confirmed by Felamimail yet (I assumed you deleted the event manually). Hence, Outlook's response referes to a non existing database entry. 

I know this behaviour from Outlook/Exchange, it adds the event on arrival automatically. In consequence it can set a status, too. Tine 2.0 does not do that. This is a bigger task to implement... @tine20 have to go for that. 

Nevertheless, my PR is important to not hang the client! Please merge.

**Comment by Mic-net** [comment]
Okay, thanks for the help, I'm glad the cause was found. (Hopefully will be able to find developers time for the new function.)

**Comment by pschuele** [comment]
hey there, thanks for the hotfix @lab-at-nohl and thanks for the logs + info @Mic-net .
we'll merge the PR asap.
I'll assign this issue to "feature requests".

**Comment by Mic-net** [comment]
Hello,
it's been a few months and nothing is still happening. Is when plan when it comes to implementation? I was surprised that this is not a high priority. Do you have few users with Outlook?

**Comment by pschuele** [comment]
hi, the hotfix PR has been merged and is part of the release https://github.com/tine20/tine20/releases/tag/2020.08.1
does it work for you?
the "feature request" part isn't on our immediate road map, so this might take a while.

**Comment by Mic-net** [comment]
Even after 4 months is the repair plan unknown? (This is not a new feature, but a bug fix.)

Nobody dealt with the ticket, so it could not be included in the latest version. The problem is not solved.

**Comment by Mic-net** [comment]
To be sure, this error message has two parts. Part 1 is resolved, the second is not.

**Comment by lab-at-nohl** [comment]
l think the second part has been understood. Because the issue is a feature request now.

However, the missing feature may be Outlook specific. The bigger picture here would be to review ActiveSync clients in general. Like iPhones or Android. Can they handle invitations (that have not been imported yet)?

**Comment by Mic-net** [comment]
Do I understand correctly that the base of Outlook users is small?

Incoming invitations in Outlook can be accepted, the sender will receive the correct acceptance. Only this invitation will remain "Local Only". Ie. stays in my Outlook but doesn't sync anywhere. there is no mention of the invitation in the DB.

**Comment by lab-at-nohl** [comment]
Just to bring some light into it: I sent a google calendar event to my Tine 2.0 account and opened the invitation mail in the Gmail App (the default ActiveSync client under Android); there is no possibility to confirm (and import) the event into calendar, I can only download it (I do not know how the behavior under iOS is). However, google‘s invite includes http-links to confirm but those do not affect Tine 2.0. Hence, it does not seem to be the default to import events on arrival (I guess specification seconds that). It seems reasonable to avoid „invite spam“, i.e. unwanted invites that would be imported unintentionally.  

Conclusion: The missing feature is NOT relevant to all ActiveSync clients (especially on mobile devices). I cannot say anything on Outlook nor its user base. Anyhow it is just an ActiveSync client to Tine 2.0. But it would be no harm to import an event once the confirmation is given (like the Tine 2.0 client handles it). In the end this is a new feature that someone would have to develop. 

Best regards
Johannes
