### ISSUE TITLE
PHP Fatal error in ./Timetracker/Model/Timeaccount.php

### ISSUE THREAD

**Issue by mzch** [tine20/tine20#7194]
When updating to 2020.03.4, PHP Fatal error occurred:
```
[Thu Jul 16 07:42:13.226774 2020] [proxy_fcgi:error] [pid 9087:tid 139865274349312] [client 118.243.18.144:65483] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'HumanResources_Config' not found in /srv/tine_2020034/Tinebase/Record/Abstract.php:269\nStack trace:\n#0 /srv/tine_2020034/Tinebase/Server/Abstract.php(172): Tinebase_Record_Abstract::getConfiguration()\n#1 /srv/tine_2020034/Tinebase/Server/Json.php(349): Tinebase_Server_Abstract::_getModelConfigMethods('Tinebase_Server...')\n#2 /srv/tine_2020034/Tinebase/Server/Json.php(448): Tinebase_Server_Json::_getServer()\n#3 /srv/tine_2020034/Setup/Server/Json.php(93): Tinebase_Server_Json->_handleException(Object(Zend_Json_Server_Request_Http), Object(Error))\n#4 /srv/tine_2020034/Setup/Core.php(117): Setup_Server_Json->handle()\n#5 /srv/tine_2020034/setup.php(14): Setup_Core::dispatchRequest()\n#6 {main}\n  thrown in /srv/tine_2020034/Tinebase/Record/Abstract.php on line 269', referer: https://mailanyplace.com/setup.php
```

I found `HumanResources_Config` only in ./Timetracker/Model/Timeaccount.php`. Because of this issue, I can't update plugins.

OS: Debian 10.4
PHP: 7.3.14

**Comment by pschuele** [comment]
does this solve the problem?

```diff
diff --git a/tine20/Timetracker/Model/Timeaccount.php b/tine20/Timetracker/Model/Timeaccount.php
index ba7c040ee7..a1b052a6ba 100644
--- a/tine20/Timetracker/Model/Timeaccount.php
+++ b/tine20/Timetracker/Model/Timeaccount.php
@@ -294,8 +294,8 @@ class Timetracker_Model_Timeaccount extends Sales_Model_Accountable_Abstract
                     self::TYPE                  => self::TYPE_RELATION,
                     self::LABEL                 => 'Stream', // _('Stream')
                     self::CONFIG                => [
-                        self::APP_NAME              => HumanResources_Config::APP_NAME,
-                        self::MODEL_NAME            => HumanResources_Model_Stream::MODEL_NAME_PART,
+                        self::APP_NAME              => 'HumanResources',
+                        self::MODEL_NAME            => 'Stream',
                         self::TYPE                  => Timetracker_Model_Timeaccount::MODEL_NAME_PART
                     ]
                 ]
```
i think, we can't use the constants here, because HumanResources code might not be loaded as it is in a different package.

**Comment by mzch** [comment]
I applied it, but the following error occurred:
```
[Mon Jul 20 02:26:48.359551 2020] [proxy_fcgi:error] [pid 1589:tid 139865207207680] [client 118.243.18.144:52112] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'HumanResources_Config' not found in /srv/tine_2020034/Tinebase/Record/Abstract.php:269\nStack trace:\n#0 /srv/tine_2020034/Tinebase/Server/Abstract.php(172): Tinebase_Record_Abstract::getConfiguration()\n#1 /srv/tine_2020034/Tinebase/Server/Json.php(349): Tinebase_Server_Abstract::_getModelConfigMethods('Tinebase_Server...')\n#2 /srv/tine_2020034/Tinebase/Server/Json.php(448): Tinebase_Server_Json::_getServer()\n#3 /srv/tine_2020034/Setup/Server/Json.php(93): Tinebase_Server_Json->_handleException(Object(Zend_Json_Server_Request_Http), Object(Error))\n#4 /srv/tine_2020034/Setup/Core.php(117): Setup_Server_Json->handle()\n#5 /srv/tine_2020034/setup.php(14): Setup_Core::dispatchRequest()\n#6 {main}\n  thrown in /srv/tine_2020034/Tinebase/Record/Abstract.php on line 269', referer: https://mailanyplace.com/setup.php
```

**Comment by pschuele** [comment]
oops, sorry. found another occurrence in the same file:

```diff
@@ -318,10 +318,9 @@ class Timetracker_Model_Timeaccount extends Sales_Model_Accountable_Abstract
         array('relatedApp' => 'Sales', 'relatedModel' => 'Contract', 'config' => array(
             array('type' => 'TIME_ACCOUNT', 'degree' => 'sibling', 'text' => 'Time Account', 'max' => '1:0'), // _('Time Account')
         )
-        ),
-        [
-            'relatedApp' => HumanResources_Config::APP_NAME,
-            'relatedModel' => HumanResources_Model_Stream::MODEL_NAME_PART,
+        ), [
+            'relatedApp' => 'HumanResources',
+            'relatedModel' => 'Stream',
             'config' => [
                 ['type' => self::MODEL_NAME_PART, 'degree' => Tinebase_Model_Relation::DEGREE_SIBLING, 'max' => '1:0'],
             ],

**Comment by mzch** [comment]
Great! It works well. Thanks! :)

**Comment by pschuele** [comment]
thanks for your help :)
