### ISSUE TITLE
update 2020.08.3 to 2020.08.4, weird versions for Calendar module

### ISSUE THREAD

**Issue by ravermeister** [tine20/tine20#7225]
Hi, 
I tried to upgrade from `2020.08.3` to `2020.08.4` via the `cli` command `php setup.php --update`.
but I got SQL Errors as shown below :
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `tine20_tree_nodes::object_id--tree_fileobjects::id`; check that it exists in /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('ALTER TABLE `ti...')
#1 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('ALTER TABLE `ti...')
#2 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#3 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /var/www/virtual/raver7/mail.rimkus.it.cur/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#5 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#8 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#9 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/virtual/raver7/mail.rimkus.it.cur/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `tine20_tree_nodes::object_id--tree_fileobjects::id`; check that it exists in /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
Stack trace:
#0 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('ALTER TABLE `ti...')
#1 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#2 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#3 /var/www/virtual/raver7/mail.rimkus.it.cur/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#4 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#5 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#6 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#7 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#8 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Core.php(117): Setup_Server_Cli->handle()
#9 /var/www/virtual/raver7/mail.rimkus.it.cur/setup.php(14): Setup_Core::dispatchRequest()
#10 {main}

Next Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `tine20_tree_nodes` DROP FOREIGN KEY `tine20_tree_nodes::object_id--tree_fileobjects::id`':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `tine20_tree_nodes::object_id--tree_fileobjects::id`; check that it exists in /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Stack trace:
#0 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'ALTER TABLE `ti...', Array)
#2 /var/www/virtual/raver7/mail.rimkus.it.cur/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#3 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /var/www/virtual/raver7/mail.rimkus.it.cur/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#5 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#8 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#9 /var/www/virtual/raver7/mail.rimkus.it.cur/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/virtual/raver7/mail.rimkus.it.cur/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}
```

after that I went to the web admin interface and I could successfully upgrade `Tinebase` module. 
Doing an `php setup.php --update` afterards in the console gave me `Updated 0 application(s).`, so 
I think the Update was successfull. But now I noticed that I've got a weird Calendar Version number. how can I have a newer Version than available? See screenshot: ![tine20_modules](https://user-images.githubusercontent.com/6666963/97627105-2add6380-1a2b-11eb-81f4-72b740cdb516.png)

What should I do?
thanks in advance and kind regards
Jonny

**Comment by markuspachali** [comment]
I can confirm the issue. Just updated from 2020.08.01 to 2020.08.04, got the SQL errors, updates Tinebase via WebUI and now having the wired version for Calendar. 

My system is running on 
CentOS 7.8.2003
PHP 7.2.34
MariaDB 10.3
Selinux is enabled

**Comment by pschuele** [comment]
I can confirm the bug and I'm working on a fix.

**Comment by pschuele** [comment]
the (available) Calendar version is no real problem -> we just forgot to update Calendar/setup.xml. there is a fix coming for that, too.
