### ISSUE TITLE
update von 2020.08.2 auf 2020.08.5 schlägt fehl

### ISSUE THREAD

**Issue by Matze0811** [tine20/tine20#7232]
Beim update (via cli) werden folgende Module nicht aktualisiert:
Felamimail
Tinebase

der Vorgang bricht mit einer Datenbankfehlermeldung ab:
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-454_2aaf3`, CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)) in /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query()
#1 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query()
#2 /var/www/elektrohd/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/elektrohd/tine20/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
#4 /var/www/elektrohd/tine20/Tinebase/Setup/Update/14.php(41): Setup_SchemaTool::updateSchema()
#5 /var/www/elektrohd/tine20/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#8 /var/www/elektrohd/tine20/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle()
#9 /var/www/elektrohd/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/elektrohd/tine20/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-454_2aaf3`, CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)) in /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
Stack trace:
#0 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query()
#1 /var/www/elektrohd/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
#2 /var/www/elektrohd/tine20/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
#3 /var/www/elektrohd/tine20/Tinebase/Setup/Update/14.php(41): Setup_SchemaTool::updateSchema()
#4 /var/www/elektrohd/tine20/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#5 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#6 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#7 /var/www/elektrohd/tine20/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle()
#8 /var/www/elektrohd/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#9 /var/www/elektrohd/tine20/setup.php(14): Setup_Core::dispatchRequest()
#10 {main}

Next Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'ALTER TABLE `tine20_tree_nodes` ADD CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)':

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-454_2aaf3`, CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)) in /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
Stack trace:
#0 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
#1 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
#2 /var/www/elektrohd/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/elektrohd/tine20/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
#4 /var/www/elektrohd/tine20/Tinebase/Setup/Update/14.php(41): Setup_SchemaTool::updateSchema()
#5 /var/www/elektrohd/tine20/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#8 /var/www/elektrohd/tine20/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle()
#9 /var/www/elektrohd/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/elektrohd/tine20/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}`

Gibts irgendwas was ich tun könnte?
Danke schonmal im Vorraus!

**Comment by lab-at-nohl** [comment]
Kannst du in die DB schauen, welche Indizes `tine20_tree_nodes` hat. Die letzten beiden Versionen hatten das Problem schon, offenbar fruchtet der fix nicht. 

https://github.com/tine20/tine20/issues/7227#issuecomment-727208432 - so sieht es bei mir aus.

**Comment by pschuele** [comment]
@Matze0811 funktioniert es denn, wenn man den update-prozess ein zweites mal startet?

**Comment by Matze0811** [comment]
Tut mir leid für die extrem späte Rückmeldung, ich hatte wahnsinnig viel um die Ohren!

@pschuele:
Nein, leider nicht. auch wenn man den update-prozess 3mal startet wird das nichts.
Ich hab es grade mal mit dem aktuellen build versucht (2020.08.07)
die CLI spuckt dann das hier aus:

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-41e_57b23`, CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)) in /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query()
#1 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query()
#2 /var/www/elektrohd/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/elektrohd/tine20/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
#4 /var/www/elektrohd/tine20/Tinebase/Setup/Update/14.php(41): Setup_SchemaTool::updateSchema()
#5 /var/www/elektrohd/tine20/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#8 /var/www/elektrohd/tine20/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle()
#9 /var/www/elektrohd/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/elektrohd/tine20/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-41e_57b23`, CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)) in /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
Stack trace:
#0 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query()
#1 /var/www/elektrohd/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
#2 /var/www/elektrohd/tine20/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
#3 /var/www/elektrohd/tine20/Tinebase/Setup/Update/14.php(41): Setup_SchemaTool::updateSchema()
#4 /var/www/elektrohd/tine20/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#5 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#6 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#7 /var/www/elektrohd/tine20/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle()
#8 /var/www/elektrohd/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#9 /var/www/elektrohd/tine20/setup.php(14): Setup_Core::dispatchRequest()
#10 {main}

Next Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: An exception occurred while executing 'ALTER TABLE `tine20_tree_nodes` ADD CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)':

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`tine20`.`#sql-41e_57b23`, CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)) in /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
Stack trace:
#0 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
#1 /var/www/elektrohd/tine20/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
#2 /var/www/elektrohd/tine20/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/elektrohd/tine20/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema()
#4 /var/www/elektrohd/tine20/Tinebase/Setup/Update/14.php(41): Setup_SchemaTool::updateSchema()
#5 /var/www/elektrohd/tine20/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/elektrohd/tine20/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#8 /var/www/elektrohd/tine20/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle()
#9 /var/www/elektrohd/tine20/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/elektrohd/tine20/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}

könnt Ihr damit was anfangen?

**Comment by Matze0811** [comment]
Noch eine Frage, ist die Version 2008.08.02 noch irgendwo verfügbar? Habe vor dem update natürlich ein Backup gemacht, jedoch mit der in Tine20 integrierten Funktion. Nun bin ich mir nicht sicher ob die files der allinone dort mit inkludiert sind???

**Comment by Matze0811** [comment]
![Unbenannt](https://user-images.githubusercontent.com/45242431/103969751-ebd43880-5166-11eb-9751-a918e008a2b4.jpg)

Zur Ergänzung...

**Comment by lab-at-nohl** [comment]
Offenbar fehlt da einiges. Wir sprechen von `Table: tine20_tree_nodes`? So sieht es bei mir aus: 

![image](https://user-images.githubusercontent.com/15079498/104107566-6616d100-52bd-11eb-8856-93817ce1a216.png)

However, this does not show the foreign keys. 

Try SQL `SHOW CREATE TABLE tine20_tree_nodes`. For me:

```sql
CREATE TABLE `tine20_tree_nodes` (
 `id` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
 `parent_id` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
 `object_id` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,
 `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
 `islink` tinyint(1) NOT NULL DEFAULT 0,
 `indexed_hash` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
 `acl_node` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
 `linkto` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
 `revisionProps` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
 `notificationProps` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
 `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
 `quota` bigint(20) unsigned DEFAULT NULL,
 `pin_protected_node` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
 `deleted_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
 PRIMARY KEY (`id`),
 UNIQUE KEY `object_id` (`object_id`,`parent_id`),
 UNIQUE KEY `parent_id_name` (`parent_id`,`name`,`deleted_time`),
 KEY `IDX_43A52BE7727ACA70` (`parent_id`),
 KEY `IDX_43A52BE7232D562B` (`object_id`),
 CONSTRAINT `FK_43A52BE7232D562B` FOREIGN KEY (`object_id`) REFERENCES `tine20_tree_fileobjects` (`id`) ON DELETE CASCADE,
 CONSTRAINT `FK_43A52BE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `tine20_tree_nodes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC
```

**Comment by Matze0811** [comment]
Die Unterschiede sind schon bezeichnend! Ich sollte dazuschreiben, das diese Tine20 Version ursprünglich seeehhhr alt ist (mindestens Elena 2015). Da ich leider kein Entwickler bin sondern Autodidakt bräuchte ich noch etwas Hilfe. Beim Versuch eine Kopie der Datenbank per Alter Table anzupassen warf mir phpmyadmin mehrere Fehler um die Ohren
![screen](https://user-images.githubusercontent.com/45242431/104569884-8cd45f00-5651-11eb-8028-aedceec95028.jpg)

**Comment by lab-at-nohl** [comment]
Ok, wir arbeiten mit einer KOPIE können also rumprobieren?

Leider kann ich nicht sehen, was bei dir fehlt. Ich würde das auch nicht manuell machen. Sondern versuchen alle Updates zu "erzwingen", dann dürfte das meiste (wieder) da sein...

**Comment by Matze0811** [comment]
Ich kann jederzeit mit der DB rumspielen, komme jedoch mit dem updaten nicht mehr weiter, da mir das Paket von 2020.08.2 und alle fortführenden bis zur 2020.08.5 fehlen. erst letztgenannte ist ja zum Download verfügbar und meine letzte DB-Version ist 2020.08.2. Wie könnte ich denn ein update auf die 2020.08.5 erzwingen? Per CLI (php setup.php --update) funktionierts ja auch nicht.

**Comment by lab-at-nohl** [comment]
Nur, dass ich es verstehe: Du brauchst die 2020.08.2 warum? Wenn du die 2020.08.7 nimmst, beinhaltet die doch alle Zwischenschritte...

**Comment by Matze0811** [comment]
Weil es mir unmöglich ist auf eine aktuelle Version zu updaten und das Produktivsystem mit der DB von 2020.08.2 aber den Files von 2020.08.1 läuft. Das kann eigentlich nicht gut sein, oder? Das Update auf die 08.2 lief damals problemlos durch und nun läuft ich da gegen die Wand und komme nicht weiter. Ich würde gern erstmal das Produktivsystem wieder konsistent haben und dann weitersehen ;)Vielen Dank übrigens für Deine Mühe! Ich finde es Spitze, das Du versuchst eine Lösung mit zu erarbeiten. Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Johannes Nohl <notifications@github.com> Datum: 14.01.21  18:24  (GMT+01:00) An: tine20/tine20 <tine20@noreply.github.com> Cc: Matze0811 <matze0811@gmail.com>, Mention <mention@noreply.github.com> Betreff: Re: [tine20/tine20] update von 2020.08.2 auf 2020.08.5 schlägt fehl (#7232) 
Nur, dass ich es verstehe: Du brauchst die 2020.08.2 warum? Wenn du die 2020.08.7 nimmst, beinhaltet die doch alle Zwischenschritte...

**Comment by pschuele** [comment]
hm, ist wohl doch keine dublette, da hatte ich falsch geschaut.
leider heben wir die alten versionen nicht alle auf. aber man kann sich das noch aus dem git auschecken und dann selbst bauen (siehe https://github.com/tine20/tine20/wiki/EN%3Abuild-from-git).
was genau das problem mit der tabelle ist, kann ich auf die schnelle auch nicht sagen. evtl hilft es ja, die keys der tabelle (z.b. via phpmyadmin) zu entfernen und dann über das tine20-update (direkt version 2020.08.7 am besten) neu anlegen lassen...

**Comment by Matze0811** [comment]
Kann ich auch aus einem asset heraus einen build starten? Asset für 08.2 ist ja noch vorhanden. Weis nur nicht wie dabei dann der Ablauf ist. Ach ja, Du ist natürlich vollkommen in Ordnung ;)

**Comment by lab-at-nohl** [comment]
> aus dem git auschecken und dann selbst bauen

Kann man eigentlich das `./vendor/bin/phing` weglassen, wenn man nur das Update über CLI `php setup-php --update` machen will? Baut das nur Javascript oder auch andere Teile?

**Comment by pschuele** [comment]
> Kann ich auch aus einem asset heraus einen build starten? Asset für 08.2 ist ja noch vorhanden. Weis nur nicht wie dabei dann der Ablauf ist. Ach ja, Du ist natürlich vollkommen in Ordnung ;)

> Kann man eigentlich das ./vendor/bin/phing weglassen, wenn man nur das Update über CLI php setup-php --update machen will? Baut das nur Javascript oder auch andere Teile?

für das `setup.php --update` braucht man keinen build. da wird ja nur das JS (+Translations) gebaut. auch mit den "assets" sollte man einfach ein update machen können.

> Welche key sollten da entfernt werden? Primary, Foreign Keys?

kann man ja testen. ich würde erstmal die FKs entfernen.
