### ISSUE TITLE
Upgrade von 2020.08.3 auf 2020.08.5

### ISSUE THREAD

**Issue by Mike-Sbg** [tine20/tine20#7234]
Habe auf meiner Testinstallation beim Setup.php -update folgende Fehler erhalten:

PDOException: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. in /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('ALTER TABLE `ti...')
#1 /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('ALTER TABLE `ti...')
#2 /var/www/html/dreamland/tine2020_5/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#3 /var/www/html/dreamland/tine2020_5/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /var/www/html/dreamland/tine2020_5/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#5 /var/www/html/dreamland/tine2020_5/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/html/dreamland/tine2020_5/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/html/dreamland/tine2020_5/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#8 /var/www/html/dreamland/tine2020_5/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#9 /var/www/html/dreamland/tine2020_5/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/html/dreamland/tine2020_5/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. in /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
Stack trace:
#0 /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('ALTER TABLE `ti...')
#1 /var/www/html/dreamland/tine2020_5/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#2 /var/www/html/dreamland/tine2020_5/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#3 /var/www/html/dreamland/tine2020_5/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#4 /var/www/html/dreamland/tine2020_5/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#5 /var/www/html/dreamland/tine2020_5/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#6 /var/www/html/dreamland/tine2020_5/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#7 /var/www/html/dreamland/tine2020_5/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#8 /var/www/html/dreamland/tine2020_5/Setup/Core.php(117): Setup_Server_Cli->handle()
#9 /var/www/html/dreamland/tine2020_5/setup.php(14): Setup_Core::dispatchRequest()
#10 {main}

Next Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `tine20_tree_nodes` ADD `linkto` VARCHAR(40) DEFAULT NULL, CHANGE `name` `name` VARCHAR(255) NOT NULL COLLATE utf8mb4_bin':

SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. in /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Stack trace:
#0 /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/dreamland/tine2020_5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'ALTER TABLE `ti...', Array)
#2 /var/www/html/dreamland/tine2020_5/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(843): Doctrine\DBAL\Connection->executeQuery('ALTER TABLE `ti...')
#3 /var/www/html/dreamland/tine2020_5/Setup/SchemaTool.php(146): Doctrine\ORM\Tools\SchemaTool->updateSchema(Array, true)
#4 /var/www/html/dreamland/tine2020_5/Tinebase/Setup/Update/14.php(29): Setup_SchemaTool::updateSchema(Array)
#5 /var/www/html/dreamland/tine2020_5/Setup/Controller.php(556): Tinebase_Setup_Update_14->update001()
#6 /var/www/html/dreamland/tine2020_5/Setup/Frontend/Cli.php(479): Setup_Controller->updateApplications()
#7 /var/www/html/dreamland/tine2020_5/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#8 /var/www/html/dreamland/tine2020_5/Setup/Server/Cli.php(149): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#9 /var/www/html/dreamland/tine2020_5/Setup/Core.php(117): Setup_Server_Cli->handle()
#10 /var/www/html/dreamland/tine2020_5/setup.php(14): Setup_Core::dispatchRequest()
#11 {main}

Bin kein Spezialist, aber ist da ein Setting in der MARIADB nicht in Ordnung?

**Comment by Mike-Sbg** [comment]
Lösung gefunden:

Ich habe in der /etc/my.cnf folgende Zeilen ergänzt:

innodb_file_format=barracuda
innodb_file_per_table=true
innodb_large_prefix=true

Jetzt ist das Update durchgelaufen
