### ISSUE TITLE
assets json not found

### ISSUE THREAD

**Issue by MpunktMpunkt** [tine20/tine20#7308]
Bei einer frischen Installation von 2021.11 erhalte ich nach dem Anlegen der DB und Aufruf der setup.php

assets json not found

im Browser.

composer install ist vorher mit
```
Generating autoload files
> git submodule update --init
fatal: not a git repository (or any of the parent directories): .git
Script git submodule update --init handling the post-install-cmd event returned with error code 128`
```
ausgestiegen.

**Comment by MpunktMpunkt** [comment]
Jedoch bleibt der Fehler "assets json not found" beim Aufruf von /setup.php

`fb09fe - -- none -- - 2021-06-17T08:50:07+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Translate_Exception -> Error opening translation file '/var/www/vhosts/tine20-allinone_2021.11/tine20/Tinebase/../Tinebase/translations/de.mo'.
fb09fe - -- none -- - 2021-06-17T08:50:07+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Translate/Adapter.php(651): Zend_Translate_Adapter_Gettext->_loadTranslationData()

#1 .../vendor/zendframework/zendframework1/library/Zend/Translate/Adapter.php(332): Zend_Translate_Adapter->_addTranslationData()
#2 .../Tinebase/Translation.php(287): Zend_Translate_Adapter->addTranslation()
#3 .../Tinebase/Frontend/Http/SinglePageApplication.php(23): Tinebase_Translation::getTranslation()
#4 .../Setup/Frontend/Http.php(66): Tinebase_Frontend_Http_SinglePageApplication::getClientHTML()
#5 [internal function]: Setup_Frontend_Http->mainScreen()
#6 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs()
#7 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call()
#8 .../Setup/Server/Http.php(46): Tinebase_Http_Server->handle()
#9 .../Setup/Core.php(117): Setup_Server_Http->handle()
#10 .../setup.php(14): Setup_Core::dispatchRequest()
#11 {main}
fb09fe - -- none -- - 2021-06-17T08:50:07+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::133 Tinebase_Exception_NotFound -> assets json not found
fb09fe - -- none -- - 2021-06-17T08:50:07+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::155 #0 .../Tinebase/Frontend/Http/SinglePageApplication.php(157): Tinebase_Frontend_Http_SinglePageApplication::getAssetsMap()
#1 .../Tinebase/Frontend/Http/SinglePageApplication.php(47): Tinebase_Frontend_Http_SinglePageApplication::getAssetHash()
#2 .../Setup/Frontend/Http.php(66): Tinebase_Frontend_Http_SinglePageApplication::getClientHTML()
#3 [internal function]: Setup_Frontend_Http->mainScreen()
#4 .../vendor/zendframework/zendframework1/library/Zend/Server/Reflection/Function/Abstract.php(380): ReflectionMethod->invokeArgs()
#5 .../Tinebase/Http/Server.php(138): Zend_Server_Reflection_Function_Abstract->__call()
#6 .../Setup/Server/Http.php(46): Tinebase_Http_Server->handle()
#7 .../Setup/Core.php(117): Setup_Server_Http->handle()
#8 .../setup.php(14): Setup_Core::dispatchRequest()
#9 {main}
`

**Comment by MpunktMpunkt** [comment]
Nach einem
```
git init
composer install
.
.
Generating autoload files
> git submodule update --init
```

wird das nun ohne Fehler beendet. Behoben hat es nichts.

P.S.: Der gestern generierte Token wird heute abgelehnt. Ich habe die /root/.composer/auth-json daher vorerst umbenannt.

```
In BaseIO.php line 104:
Your github oauth token for github.com contains invalid characters: "<Token>"
```

**Comment by MpunktMpunkt** [comment]
Niemand?
