### ISSUE TITLE
changing mail account raises exception

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7371]
Tried to edit an already set mail account gives the following stacktrace:
```
 2022-03-22T09:39:54+00:00 ERR (3): Tinebase_Server_Json::_handleException::434 TypeError -> fputs(): Argument #1 ($stream) must be of type resource, null given
2022-03-22T09:39:54+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 TypeError -> fputs(): Argument #1 ($stream) must be of type resource, null given
2022-03-22T09:39:54+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Sieve.php(194): fputs(NULL, 'AUTHENTICATE "P...')
#1 .../vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Sieve.php(385): Zend_Mail_Protocol_Sieve->sendRequest('AUTHENTICATE', Array)
#2 .../vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Sieve.php(613): Zend_Mail_Protocol_Sieve->requestAndResponse('AUTHENTICATE', Array)
#3 .../Felamimail/Backend/Sieve.php(39): Zend_Mail_Protocol_Sieve->authenticate('user.name', '********')
#4 .../Felamimail/Backend/SieveFactory.php(46): Felamimail_Backend_Sieve->__construct(Array)
#5 .../Felamimail/Controller/Sieve.php(221): Felamimail_Backend_SieveFactory::factory('c28ece2ab4e5bb3...')
#6 .../Felamimail/Controller/Sieve.php(164): Felamimail_Controller_Sieve->_setSieveBackendAndAuthenticate('c28ece2ab4e5bb3...')
#7 .../Felamimail/Controller/Sieve.php(149): Felamimail_Controller_Sieve->_getServerSieveScript('c28ece2ab4e5bb3...')
#8 .../Felamimail/Controller/Sieve.php(116): Felamimail_Controller_Sieve->getSieveScript('c28ece2ab4e5bb3...')
#9 .../Felamimail/Frontend/Json.php(625): Felamimail_Controller_Sieve->getVacation('c28ece2ab4e5bb3...')
#10 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(231): Felamimail_Frontend_Json->getVacation('c28ece2ab4e5bb3...')
#11 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(603): Zend_Server_Abstract->_dispatch(Object(Zend_Server_Method_Definition), Array)
#12 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(206): Zend_Json_Server->_handle()
#13 .../Tinebase/Server/Json.php(401): Zend_Json_Server->handle(Object(Zend_Json_Server_Request))
#14 .../Tinebase/Server/Json.php(169): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))
#15 .../Tinebase/Core.php(271): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))
#16 .../index.php(24): Tinebase_Core::dispatchRequest()
#17 {main}
```
changing the mail account is not possible. If needed, the execption should be caught - but I think some condition is not handled correct (if no connection to the server is possible, an authentication attemp does not make sense)

**Comment by lab-at-nohl** [comment]
Do you have sieve set up properly? E.g. correct port (do not know why but for me it was never the default port).

**Comment by mokraemer** [comment]
I don't have a sieve set-up. Since the dialog crashes, I'm unable to check what the setting is.

**Comment by lab-at-nohl** [comment]
I meant in setup.php, what are your mail settings? 

To me it looks like you are changing the account in Admin app.

**Comment by mokraemer** [comment]
No. I logged-in as a user, right clicked in email-app on an existing mail-account and I get an error-dialog. I found the corresponding stacktrace in the log.
