### ISSUE TITLE
setup.php failing with "Table tine.tine20_path doesn't exist"

### ISSUE THREAD

**Issue by zud222** [tine20/tine20#7440]
I tried to update from **tine-2022.12.17-31937f9-nightly** to **tine-2023.02.04-0594f68-nightly**. After unpacking and copying config.inc.php I started the upgrade by calling 

`php setup.php --update`

After a few seconds, this failed with the message

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine.tine20_path' doesn't exist, query was: TRUNCATE TABLE tine20_path`

This error message now persists even if I call setup.php in the directory of the old tine version. Could anyone please help me? It appears that I'm stuck with this version.

**Comment by lab-at-nohl** [comment]
Do you have a table `tine20_path` in DB `tine`? How does it look like?

Please provide a log file, level `DEBUG`, that shows the run of `php setup.php --update`. You can turn logging in config.inc.php on, which will be respected also during setup. 

@paulmhh introduced the TRUNCATE in Table Version 15.24 of Tinebase, maybe he can help (this obviously implies that the table had existed before).

**Comment by zud222** [comment]
The table 'tine20_path' does not exist:
```
MariaDB [tine]> SHOW TABLES LIKE 'tine20_path';
Empty set (0,000 sec)
```

Here's the tail of the debug log output:
```
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 INFO (6): Tinebase_Controller_Record_Abstract::update::1347 Update Tinebase_Model_ImportExportDefinition (duplicate check: 1)
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_updateACLCheck::1434 Doing ACL check ...
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::_concurrencyManagement::1463 Doing concurrency check ...
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::increaseRecordSequence::1257 Increasing seq of Tinebase_Model_ImportExportDefinition with id 7f2d997929e96d09a7e875a4101ca40b4c08afec from 22 to 23
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::87 Writing modlog for Tinebase_Model_ImportExportDefinition
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 INFO (6): Tinebase_Notes::addSystemNote::440 Nothing changed -> do not add "changed" note.
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Container::increaseContentSequence::1948 Increased content seq of container 7090be30147d40b6dbf9b6f1d4bbb014bb2b276c to 1033
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Container::increaseContentSequence::1962 Creating "update" action content history record for record id 7f2d997929e96d09a7e875a4101ca40b4c08afec
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Backend_Sql_Abstract::create::1066 Created new record in container_content with id 0fc1de330ddfbc7b20731d878406bc255c64dfc9
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 INFO (6): Setup_Controller::updateApplications::603 Updating Tinebase_Setup_Update_15::update024
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 INFO (6): Tinebase_TransactionManager::rollBack::225  rollBack request, rollBack all transactionables
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Setup_Backend_Abstract::truncateTable::131 Truncate table path
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 INFO (6): Tinebase_TransactionManager::rollBack::225  rollBack request, rollBack all transactionables
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 ERR (3): Setup_Controller::updateApplications::627 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine.tine20_path' doesn't exist, query was: TRUNCATE TABLE `tine20_path`
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 ERR (3): Setup_Controller::updateApplications::628 #0 /srv/www/tine-2023.02.04-0594f68-nightly/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
#1 /srv/www/tine-2023.02.04-0594f68-nightly/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#2 /srv/www/tine-2023.02.04-0594f68-nightly/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /srv/www/tine-2023.02.04-0594f68-nightly/Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /srv/www/tine-2023.02.04-0594f68-nightly/Setup/Backend/Abstract.php(133): Setup_Backend_Abstract->execQueryVoid()
#5 /srv/www/tine-2023.02.04-0594f68-nightly/Tinebase/Setup/Update/15.php(721): Setup_Backend_Abstract->truncateTable()
#6 /srv/www/tine-2023.02.04-0594f68-nightly/Setup/Controller.php(607): Tinebase_Setup_Update_15->update024()
#7 /srv/www/tine-2023.02.04-0594f68-nightly/Setup/Frontend/Cli.php(505): Setup_Controller->updateApplications()
#8 /srv/www/tine-2023.02.04-0594f68-nightly/Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#9 /srv/www/tine-2023.02.04-0594f68-nightly/Setup/Server/Cli.php(169): Setup_Frontend_Cli->handle()
#10 /srv/www/tine-2023.02.04-0594f68-nightly/Setup/Core.php(117): Setup_Server_Cli->handle()
#11 /srv/www/tine-2023.02.04-0594f68-nightly/setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 INFO (6): Setup_Controller::_cleanUpUpdate::847 Removing superuser role superUser52883a052b345c3867b7b5adbf207535a02d2f5d
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 INFO (6): Tinebase_Controller_Record_Abstract::delete::2138 Deleting 1 of Tinebase_Model_Role records ...
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::increaseRecordSequence::1257 Increasing seq of Tinebase_Model_Role with id 0aa4afd63dd75f4bc1a102b333bf55a8d838cccc from 84 to 85
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Db_Statement_Exception -> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tine.tine20_path' doesn't exist, query was: TRUNCATE TABLE `tine20_path`
c670b9 - setupuser - 2023-02-13T16:29:28+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute()
#1 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()
#2 .../vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 .../Setup/Backend/Abstract.php(207): Zend_Db_Adapter_Pdo_Abstract->query()
#4 .../Setup/Backend/Abstract.php(133): Setup_Backend_Abstract->execQueryVoid()
#5 .../Tinebase/Setup/Update/15.php(721): Setup_Backend_Abstract->truncateTable()
#6 .../Setup/Controller.php(607): Tinebase_Setup_Update_15->update024()
#7 .../Setup/Frontend/Cli.php(505): Setup_Controller->updateApplications()
#8 .../Setup/Frontend/Cli.php(96): Setup_Frontend_Cli->_update()
#9 .../Setup/Server/Cli.php(169): Setup_Frontend_Cli->handle()
#10 .../Setup/Core.php(117): Setup_Server_Cli->handle()
#11 .../setup.php(14): Setup_Core::dispatchRequest()
#12 {main}
```

**Comment by lab-at-nohl** [comment]
Are you still on this? I do have a table `path` although it is empty and not used. 

I guess because the feature is turned off. See from the console: `# php setup.php --getconfig configkey="features" app=Tinebase` returns (beside others) `"featureSearchPath":false`. **Please check yourself**.

If you have a backup and if you can return to the point where you are though, you could try to create the table by yourself. For your information:

```sql
CREATE TABLE IF NOT EXISTS `tine20_path` (
  `id` varchar(40) NOT NULL,
  `path` mediumtext NOT NULL,
  `shadow_path` mediumtext NOT NULL,
  `creation_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;

ALTER TABLE `tine20_path`
  ADD PRIMARY KEY (`id`),
  ADD FULLTEXT KEY `path` (`path`);
ALTER TABLE `tine20_path`
  ADD FULLTEXT KEY `shadow_path` (`shadow_path`);
```

**Comment by zud222** [comment]
I just created the table as you suggested and now the update process finishes successfully. It's still a mystery why the table wasn't there in the first place... Thanks a lot for your help!
