### ISSUE TITLE
Problem with Fedora38 (PHP 8.2.6)

### ISSUE THREAD

**Issue by hkueller** [tine20/tine20#7465]
whenever i try to update my web server to Fedora38 (PHP 8.2.6), and try to load the tine login page i get the error:

`Fatal error: Uncaught Error: The DateTime object has not been correctly initialized by its constructor in [no active file]:0 Stack trace: #0 [internal function]: DateTime->__serialize() #1 {main} thrown in [no active file] on line 0`

**Comment by lab-at-nohl** [comment]
I just had a very similar one after upgrading to **php 8.2**, see below.  For me, clearing the cache was sufficient. Use `php setup.php --clear_cache` or remove all files from cache directory). That solved my issue completely.

```
#0 [internal function]: DateTime->__unserialize()
#1 .../vendor/zendframework/zendframework1/library/Zend/Cache/Core.php(313): unserialize()
#2 .../Tinebase/Cache/PerRequest.php(204): Zend_Cache_Core->load()
#3 .../Tinebase/Backend/Sql/Abstract.php(1798): Tinebase_Cache_PerRequest->load()
#4 .../Tinebase/Container.php(594): Tinebase_Backend_Sql_Abstract->loadFromClassCache()
#5 .../Tinebase/Container.php(932): Tinebase_Container->getContainerById()
#6 .../Addressbook/Controller/Contact.php(171): Tinebase_Container->getDefaultContainer()
#7 .../Addressbook/Frontend/Json.php(488): Addressbook_Controller_Contact->getDefaultAddressbook()
#8 .../Addressbook/Frontend/Json.php(563): Addressbook_Frontend_Json->getDefaultAddressbook()
#9 .../Tinebase/Frontend/Json.php(1134): Addressbook_Frontend_Json->getRegistryData()
#10 .../Tinebase/Frontend/Json.php(1064): Tinebase_Frontend_Json->_getCustomAppRegistry()
#11 .../Tinebase/Frontend/Json.php(990): Tinebase_Frontend_Json->_getAppRegistry()
#12 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(231): Tinebase_Frontend_Json->getAllRegistryData()
#13 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(603): Zend_Server_Abstract->_dispatch()
#14 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(206): Zend_Json_Server->_handle()
#15 .../Tinebase/Server/Json.php(410): Zend_Json_Server->handle()
#16 .../Tinebase/Server/Json.php(177): Tinebase_Server_Json->_handle()
#17 .../Tinebase/Core.php(271): Tinebase_Server_Json->handle()
#18 .../index.php(24): Tinebase_Core::dispatchRequest()
#19 {main}
```

**Comment by kuellerh** [comment]
With [2023.07.15.40](https://github.com/tine20/tine20/releases/tag/2023.07.15.40) everything is working fine again.
i belive you can close this issue

**Comment by pschuele** [comment]
thanks for the update. but note: php 8.2 is not officially supported yet.
