### ISSUE TITLE
Remote CalDAV (BETA) Sync

### ISSUE THREAD

**Issue by Nachtlichtermeer** [tine20/tine20#7475]
i want to try the CalDAV-sync between 2 tine-servers.
after setup all with username and so on nothing happens.
i found a scheduler-job for that at the admin-tab 'scheduler' and saw 'next run' is far in the past.
is there a linux-cronjob or something else to trigger the scheduler? i can not found a docu for the scheduler

**Comment by lab-at-nohl** [comment]
Actually there are two mechanisms for background tasks:

1. Cli command [triggerAsyncEvents](https://github.com/tine20/tine20/wiki/EN%3ACli#tinebasetriggerasyncevents) which is usually called by cronjob like every other minute

2. The worker.php daemon. As it is a real background server process, it is to be implemented by the OS. Are you using Linux and do you have access to the Cli?

Best
Johannes

**Comment by Nachtlichtermeer** [comment]
ahhh, that's what i'm looking for. tanks!

tine runs on Ubuntu 22.04 (root-server) so yes, i have full access

**Comment by lab-at-nohl** [comment]
Then I would recommend to start the worker.php by a systemd unit... As I said it is a real daemon. It sends mails and stuff independently of the main process. Very nice thing (in combination with redis-server).

**Comment by Nachtlichtermeer** [comment]
thanks a lot! :)

**Comment by Nachtlichtermeer** [comment]
first i tested this per cronjob.
After adding a remote calender i get the following when executing
```
php tine20.php --method Tinebase.triggerAsyncEvents
```
:
```
Error: Undefined constant "Sabre\DAV\CURLOPT_RETURNTRANSFER" in /var/www/dmzsrv-groupware/htdocs/tine20/vendor/sabre/dav/lib/Sabre/DAV/Client.php:314
Stack trace:
#0 /var/www/dmzsrv-groupware/htdocs/tine20/Tinebase/Import/CalDav/Client.php(241): Sabre\DAV\Client->request()
#1 /var/www/dmzsrv-groupware/htdocs/tine20/Calendar/Import/CalDav/Client.php(173): Tinebase_Import_CalDav_Client->calDavRequest()
#2 /var/www/dmzsrv-groupware/htdocs/tine20/Calendar/Import/CalDav/Client.php(395): Calendar_Import_CalDav_Client->findAllCalendarICSs()
#3 /var/www/dmzsrv-groupware/htdocs/tine20/Calendar/Import/CalDAV.php(74): Calendar_Import_CalDav_Client->updateAllCalendarData()
#4 /var/www/dmzsrv-groupware/htdocs/tine20/Admin/Model/SchedulerTask/Import.php(59): Calendar_Import_CalDAV->import()
#5 /var/www/dmzsrv-groupware/htdocs/tine20/Admin/Controller/SchedulerTask.php(37): Admin_Model_SchedulerTask_Import->run()
#6 /var/www/dmzsrv-groupware/htdocs/tine20/Tinebase/Scheduler/Task.php(209): Admin_Controller_SchedulerTask->runCustomScheduledTask()
#7 /var/www/dmzsrv-groupware/htdocs/tine20/Tinebase/Scheduler.php(169): Tinebase_Scheduler_Task->run()
#8 /var/www/dmzsrv-groupware/htdocs/tine20/Tinebase/Frontend/Cli.php(395): Tinebase_Scheduler->run()
#9 /var/www/dmzsrv-groupware/htdocs/tine20/Tinebase/Frontend/Cli.php(344): Tinebase_Frontend_Cli->triggerAsyncEvents()
#10 /var/www/dmzsrv-groupware/htdocs/tine20/Tinebase/Server/Cli.php(111): Tinebase_Frontend_Cli->handle()
#11 /var/www/dmzsrv-groupware/htdocs/tine20/Tinebase/Core.php(271): Tinebase_Server_Cli->handle()
#12 /var/www/dmzsrv-groupware/htdocs/tine20/tine20.php(73): Tinebase_Core::dispatchRequest()
#13 {main}
```

**Comment by lab-at-nohl** [comment]
Wild guess, is curl'S PHP module installed - see `php -m | grep curl`? What version is PHP, lesser than 7.4 or alike?

**Comment by Nachtlichtermeer** [comment]
the command
`php tine20.php --method Tinebase.triggerAsyncEvents`
works as expected until i add an remote calendar and the scheduler for this is added

`sudo apt-get install php-curl`
fixes the problem. thank you!

**Comment by Nachtlichtermeer** [comment]
Sync now works, but for this a new calendar is created ("foo bar persönlicher Kalender1")
instead using the existing one.

second problem is when i delete the scheduler-task it is not deleted in the database

**Comment by lab-at-nohl** [comment]
You use Calendar > Import -> CalDAV (BETA), right?

1. Do you have appropriate permissions in the Container (Calendar) that you wanted to use (right click, permissions)? Can you provide a log file snippet, level DEBUG?

2. For the Database: Does the table has a field `is_deleted`? Modlog utilizes this field, if `1` equals to deleted; by Cron job it will be purged...

**Comment by Nachtlichtermeer** [comment]
1.
i use my personal calendar for the tests and i've checked the permissions: all granted

Log will follow until tomorrow. At the moment tine syncs many mails so the debug-log is very full with useless entries

2.
yes the table has the field is_deleted. I didn't know that it will be purged later; my mistake

**Comment by Nachtlichtermeer** [comment]
Debuglog after creating import-task while executing "sudo -u www-data php /var/www/*/htdocs/tine20/tine20.php --method Tinebase.triggerAsyncEvents"

```
429beb - -- none -- - 2023-08-21T12:57:04+00:00 INFO (6): Tinebase_Core::setupLogger::892 Logger initialized.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1232 DB connection id: 14763
429beb - -- none -- - 2023-08-21T12:57:04+00:00 INFO (6): Tinebase_Core::initFramework::480 initializing framework (PID: 2710901)
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Translation::getLocale::201 given localeString 'en_US'
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Translation::getLocale::214 'en_US' is not supported, checking fallback
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Translation::getLocale::240 selected locale: 'en'
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1353 given localeString 'auto'
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1380 Try to detect the locale of the user (browser, environment, default)
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Translation::getLocale::201 given localeString 'auto'
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Translation::getLocale::214 'en' is not supported, checking fallback
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Translation::getLocale::240 selected locale: 'en'
429beb - -- none -- - 2023-08-21T12:57:04+00:00 INFO (6): Tinebase_Core::setupUserLocale::1404 Setting user locale: en
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Server_Cli::handle::89 Is cli request. method: Tinebase.triggerAsyncEvents
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Frontend_Cli::triggerAsyncEvents::377 Triggering async events from CLI.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User::setBackendType::324 Setting backend type to Ldap
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Addressbook_Controller_Contact::__construct::68 Geolocation service disabled with config option.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::127 Registering Addressbook_Controller_Contact plugin.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User_Sql::registerPlugin::116 Registering Addressbook_Controller_Contact SQL plugin.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::127 Registering Tinebase_EmailUser_Imap_Standard plugin.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User_Sql::registerPlugin::116 Registering Tinebase_EmailUser_Imap_Standard SQL plugin.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::127 Registering Tinebase_EmailUser_Smtp_Standard plugin.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User_Sql::registerPlugin::116 Registering Tinebase_EmailUser_Smtp_Standard SQL plugin.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User::factory::285 Created user backend of type Tinebase_User_Ldap
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Frontend_Cli_Abstract::_getCronuserFromConfigOrCreateOnTheFly::697 Setting user with id 2071 as cronuser.
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to Path
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to MFA_UserConfig
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to FullUser
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Group::getInstance::83 groups backend: Ldap
429beb - -- none -- - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Group_Sql::getGroupMemberships::128 fetch group memberships from db
429beb - -- none -- - 2023-08-21T12:57:04+00:00 INFO (6): Tinebase_Core::setUser::1752 Setting user Admin, Tine20
429beb - tineadmin - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Acl_Roles::getRoleMemberships::520 fetch role memberships from db
429beb - tineadmin - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to MFA_UserConfig
429beb - tineadmin - 2023-08-21T12:57:04+00:00 INFO (6): Tinebase_Scheduler::run::86 Scheduler started
429beb - tineadmin - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Lock_Mysql::tryAcquire::64 Aquired lock: 4c4751347a7707dd6d3cc275f8be18c00cf5d3c7
429beb - tineadmin - 2023-08-21T12:57:04+00:00 INFO (6): Tinebase_Scheduler::run::156 run task import remote events for foo foo from https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11
429beb - tineadmin - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to FullUser
429beb - tineadmin - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_User_Ldap::_getLdapEntry::699 filter (&(objectclass=posixaccount)(uidnumber=2072))
429beb - tineadmin - 2023-08-21T12:57:04+00:00 INFO (6): Tinebase_Core::setUser::1752 Setting user foo foo
429beb - foo - 2023-08-21T12:57:04+00:00 DEBUG (7): Tinebase_Scheduler_Task::run::172 starting .... 
429beb - foo - 2023-08-21T12:57:05+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::110 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
429beb - foo - 2023-08-21T12:57:05+00:00 NOTICE (5): Tinebase_Auth_CredentialCache_Adapter_Shared::getKey::85 credentialCacheSharedKey is longer than 24 chars
429beb - foo - 2023-08-21T12:57:05+00:00 DEBUG (7): Calendar_Import_CalDAV::import 68 Trigger CalDAV client with URI https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11
429beb - foo - 2023-08-21T12:57:05+00:00 DEBUG (7): Tinebase_Acl_Roles::getRoleMemberships::520 fetch role memberships from db
429beb - foo - 2023-08-21T12:57:05+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
429beb - foo - 2023-08-21T12:57:05+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
429beb - foo - 2023-08-21T12:57:05+00:00 DEBUG (7): Tinebase_Server_Json::_getServer::328 Get server from cache
429beb - foo - 2023-08-21T12:57:05+00:00 DEBUG (7): Tinebase_Server_Json::_getServer::342 setting up json server ...
429beb - foo - 2023-08-21T12:57:05+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
429beb - foo - 2023-08-21T12:57:05+00:00 INFO (6): Tinebase_Core::isFilesystemAvailable::2232 Filesystem available: yes
429beb - foo - 2023-08-21T12:57:05+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
429beb - foo - 2023-08-21T12:57:05+00:00 DEBUG (7): Tinebase_Import_CalDav_Client::calDavRequest::237 Sending PROPFIND request for uri /calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 ...
429beb - foo - 2023-08-21T12:57:06+00:00 INFO (6): Calendar_Import_CalDav_Client::updateAllCalendarData::415 Looking for updates in 1 calendars ...
429beb - foo - 2023-08-21T12:57:06+00:00 DEBUG (7): Tinebase_Import_CalDav_Client::calDavRequest::237 Sending REPORT request for uri /calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 ...
429beb - foo - 2023-08-21T12:57:07+00:00 DEBUG (7): Calendar_Import_CalDav_Client::findContainerForCalendar 209 $calendarUri = /calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 / $displayname = foo foos persönlicher Kalender / $defaultCalendarsName = foo foos persönlicher Kalender / $uuid = 85910585889742309765d61a6d8ec3b55cf5f491
429beb - foo - 2023-08-21T12:57:07+00:00 DEBUG (7): Calendar_Import_CalDav_Client::findContainerForCalendar 238 Found existing calendar with the same name
429beb - foo - 2023-08-21T12:57:07+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::474  Got 11 server etags for container foo foos persönlicher Kalender
429beb - foo - 2023-08-21T12:57:07+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::549  Record has been added in tine: 003c3345a789f092dc77a14399073b842a106e11
429beb - foo - 2023-08-21T12:57:07+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::549  Record has been added in tine: 005a71c53d8351fac4765183f05e9eb4f6c4608e

...

429beb - foo - 2023-08-21T12:57:07+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::549  Record has been added in tine: ffa2e28653206f7eff226b0385d80dc8ed6cbc38
429beb - foo - 2023-08-21T12:57:07+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::549  Record has been added in tine: ffff9209dd3378565d615cd7e3ff335d12903348
429beb - foo - 2023-08-21T12:57:07+00:00 INFO (6): Calendar_Import_CalDav_Client::updateAllCalendarData::437 0 calendar(s) changed for: foo (0/0/0 records add/update/delete): Array
(
)

429beb - foo - 2023-08-21T12:57:07+00:00 INFO (6): Tinebase_Scheduler::run::173 task import remote events for foo foo from https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 succeeded
429beb - foo - 2023-08-21T12:57:07+00:00 INFO (6): Tinebase_Core::setUser::1752 Setting user Admin, Tine20
429beb - tineadmin - 2023-08-21T12:57:07+00:00 INFO (6): Tinebase_Scheduler::run::196 running task import remote events for foo foo from https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 finished
429beb - tineadmin - 2023-08-21T12:57:07+00:00 INFO (6): Tinebase_Scheduler::run::98 no due task found, stopping...
429beb - tineadmin - 2023-08-21T12:57:07+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::298 {"file":"tine20.php","method":"Tinebase.triggerAsyncEvents","time":"2.8s","memory":" Memory usage: 28 MB","cache":" Real patch cache size: 200647","pid":2710901}
```

and then i have a second calendar 'foo foos persönlicher Kalender1' with the synced appointments.
sometimes i can see this calendar in the GUI, sometimes i cannot see it but when i edit the appointment i can see it is stored in 'foo foos persönlicher Kalender1'. if second, the synced appointments are only visible after page refresh on calendar tab but not after direct clicking on 'foo foos persönlicher Kalender'

**Comment by lab-at-nohl** [comment]
Ok, missing refreshing might be a bug. But how should ui know that background job has just finished... I know there is a mechanism but it may take some time.

For the calendar name: I am under the impression that it is a feature not a bug. If you provide a URL that is (potentially) more than a single calendar it uses the name(s) of the originating calendar. To avoid duplicates it adds '1'. See the [Source](https://github.com/tine20/tine20/blob/df9e5636a14ce1a8af38c6dc23e26f5a22e16262/tine20/Calendar/Import/CalDav/Client.php#L247). Try to give a specific calender with a different name than "xy personals calendar".

**Comment by Nachtlichtermeer** [comment]
i've tried a new clean calendar called 'foo test' and adds the sync...

```
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Core::setupLogger::892 Logger initialized.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Core::createAndConfigureDbAdapter::1232 DB connection id: 17429
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Core::initFramework::480 initializing framework (PID: 3206129)
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Translation::getLocale::201 given localeString 'en_US'
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Translation::getLocale::214 'en_US' is not supported, checking fallback
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Translation::getLocale::240 selected locale: 'en'
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1353 given localeString 'auto'
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Core::setupUserLocale::1380 Try to detect the locale of the user (browser, environment, default)
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Translation::getLocale::201 given localeString 'auto'
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Translation::getLocale::214 'en' is not supported, checking fallback
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Translation::getLocale::240 selected locale: 'en'
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Core::setupUserLocale::1404 Setting user locale: en
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Server_Cli::handle::89 Is cli request. method: Tinebase.triggerAsyncEvents
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Frontend_Cli::triggerAsyncEvents::377 Triggering async events from CLI.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User::setBackendType::324 Setting backend type to Ldap
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Addressbook_Controller_Contact::__construct::68 Geolocation service disabled with config option.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::127 Registering Addressbook_Controller_Contact plugin.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User_Sql::registerPlugin::116 Registering Addressbook_Controller_Contact SQL plugin.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::127 Registering Tinebase_EmailUser_Imap_Standard plugin.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User_Sql::registerPlugin::116 Registering Tinebase_EmailUser_Imap_Standard SQL plugin.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User_Abstract::registerPlugin::127 Registering Tinebase_EmailUser_Smtp_Standard plugin.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User_Sql::registerPlugin::116 Registering Tinebase_EmailUser_Smtp_Standard SQL plugin.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User::factory::285 Created user backend of type Tinebase_User_Ldap
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Frontend_Cli_Abstract::_getCronuserFromConfigOrCreateOnTheFly::697 Setting user with id 2071 as cronuser.
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to Path
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to MFA_UserConfig
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to FullUser
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Group::getInstance::83 groups backend: Ldap
bec4af - -- none -- - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Core::setUser::1752 Setting user Admin, Tine20
bec4af - tineadmin - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to MFA_UserConfig
bec4af - tineadmin - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Scheduler::run::86 Scheduler started
bec4af - tineadmin - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Lock_Mysql::tryAcquire::64 Aquired lock: 2c482e033ad657971297b7974ef6421ceb7c4e7b
bec4af - tineadmin - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Scheduler::run::156 run task import remote events for foo foo from https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11
bec4af - tineadmin - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to FullUser
bec4af - tineadmin - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_User_Ldap::_getLdapEntry::699 filter (&(objectclass=posixaccount)(uidnumber=2072))
bec4af - tineadmin - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Core::setUser::1752 Setting user foo foo
bec4af - foo - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Scheduler_Task::run::172 starting .... 
bec4af - foo - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Auth_CredentialCache::setCacheAdapter::110 Using credential cache adapter: Tinebase_Auth_CredentialCache_Adapter_Cookie
bec4af - foo - 2023-08-22T08:39:26+00:00 NOTICE (5): Tinebase_Auth_CredentialCache_Adapter_Shared::getKey::85 credentialCacheSharedKey is longer than 24 chars
bec4af - foo - 2023-08-22T08:39:26+00:00 DEBUG (7): Calendar_Import_CalDAV::import 68 Trigger CalDAV client with URI https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11
bec4af - foo - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Acl_Roles::getRoleMemberships::520 fetch role memberships from db
bec4af - foo - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
bec4af - foo - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
bec4af - foo - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Server_Json::_getServer::328 Get server from cache
bec4af - foo - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Server_Json::_getServer::342 setting up json server ...
bec4af - foo - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
bec4af - foo - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_Core::isFilesystemAvailable::2232 Filesystem available: yes
bec4af - foo - 2023-08-22T08:39:26+00:00 INFO (6): Tinebase_AreaLock_Session::hasValidAuth::62 No session started to check auth in session
bec4af - foo - 2023-08-22T08:39:26+00:00 DEBUG (7): Tinebase_Import_CalDav_Client::calDavRequest::237 Sending PROPFIND request for uri /calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 ...
bec4af - foo - 2023-08-22T08:39:27+00:00 INFO (6): Calendar_Import_CalDav_Client::updateAllCalendarData::415 Looking for updates in 1 calendars ...
bec4af - foo - 2023-08-22T08:39:27+00:00 DEBUG (7): Tinebase_Import_CalDav_Client::calDavRequest::237 Sending REPORT request for uri /calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 ...
bec4af - foo - 2023-08-22T08:39:28+00:00 DEBUG (7): Calendar_Import_CalDav_Client::findContainerForCalendar 209 $calendarUri = /calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 / $displayname = foo test / $defaultCalendarsName = foo test / $uuid = 85910585889742309765d61a6d8ec3b55cf5f491
bec4af - foo - 2023-08-22T08:39:28+00:00 DEBUG (7): Calendar_Import_CalDav_Client::findContainerForCalendar 238 Found existing calendar with the same name
bec4af - foo - 2023-08-22T08:39:28+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::474  Got 11 server etags for container foo foos persönlicher Kalender
bec4af - foo - 2023-08-22T08:39:28+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::549  Record has been added in tine: 003c3345a789f092dc77a14399073b842a106e11

...

bec4af - foo - 2023-08-22T08:39:28+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::549  Record has been added in tine: ffa2e28653206f7eff226b0385d80dc8ed6cbc38
bec4af - foo - 2023-08-22T08:39:28+00:00 DEBUG (7): Calendar_Import_CalDav_Client::updateCalendar::549  Record has been added in tine: ffff9209dd3378565d615cd7e3ff335d12903348
bec4af - foo - 2023-08-22T08:39:28+00:00 INFO (6): Calendar_Import_CalDav_Client::updateAllCalendarData::437 0 calendar(s) changed for: foo (0/0/0 records add/update/delete): Array
(
)

bec4af - foo - 2023-08-22T08:39:28+00:00 INFO (6): Tinebase_Scheduler::run::173 task import remote events for foo foo from https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 succeeded
bec4af - foo - 2023-08-22T08:39:28+00:00 INFO (6): Tinebase_Core::setUser::1752 Setting user Admin, Tine20
bec4af - tineadmin - 2023-08-22T08:39:28+00:00 INFO (6): Tinebase_Scheduler::run::196 running task import remote events for foo foo from https://mail.foo.de/calendars/6ae564b8e54702784e106a24a10c0f409faee0ae/11 finished
bec4af - tineadmin - 2023-08-22T08:39:28+00:00 INFO (6): Tinebase_Scheduler::run::98 no due task found, stopping...
bec4af - tineadmin - 2023-08-22T08:39:28+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::298 {"file":"tine20.php","method":"Tinebase.triggerAsyncEvents","time":"2.13s","memory":" Memory usage: 28 MB","cache":" Real patch cache size: 198701","pid":3206129}
```

but in the GUI i cannot see that entries and the calendar 'foo test' is still empty.

What i try is to sync the personal calendars of any users between 2 tine installations

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
