### ISSUE TITLE
Tinebase.triggerAsyncEvents reactivate disabled users

### ISSUE THREAD

**Issue by Nachtlichtermeer** [tine20/tine20#7476]
since activating Tinebase.triggerAsyncEvents disabled users are reactived through task
Tinebase_User/Group::syncUsers/Groups

user-backend is ldap

**Comment by lab-at-nohl** [comment]
It reminds me a little of #7426. What version do you use and does it include the mentioned patch?

**Comment by Nachtlichtermeer** [comment]
yes, me too
but problem now cames back after activating Tinebase.triggerAsyncEvents
when i delete the task Tinebase_User/Group::syncUsers/Groups in the database, problem is gone away
but this was only a test in a test-copy

version is 2023.07.01.47

since patch-commit i do updates normaly - isn't the patch in code?

**Comment by lab-at-nohl** [comment]
The patch is merged, see line 690 in Tinebase/User.php

Does the attribute accountStatus exist?

**Comment by Nachtlichtermeer** [comment]
where should i find the attribute 'accountStatus'?

Logfile would be provided after clarify this

**Comment by lab-at-nohl** [comment]
I ment the LDAP entry. Does it includes the attribute accountStatus?

Also can you paste from your Tinebase/User.php the lines around 690?

What PHP version does the cronjob use? Same like the Webserver (yes, many hosted offer a choice for web but not Cli).

**Comment by Nachtlichtermeer** [comment]
no our LDAP dosn't have this field
sounds like it is needed for tine?

PHP of Cron is the same of tine. It is a ubuntu 22.04 and i have full access
PHP in detail:
```
PHP 8.1.2-1ubuntu2.13 (cli) (built: Jun 28 2023 14:01:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.13, Copyright (c), by Zend Technologies
```

Tinebase/User.php:
```
    protected static function _checkAndUpdateCurrentUser(Tinebase_Model_FullUser $currentUser, Tinebase_Model_FullUser $user, array $options = [])
    {
       $fieldsToSync = [
            // true = REQUIRED, may be empty; false = OPTIONAL, omit if empty/missing; null IGNORE always
            'accountLoginName' => true, 
            'accountLastPasswordChange' => false, 
            'accountExpires' => false, 
            'accountPrimaryGroup' => true,
            'accountDisplayName' => false, 
            'accountLastName' => true, 
            'accountFirstName' => true, 
            'accountFullName' => false, 
            'accountEmailAddress' => true,
            'accountHomeDirectory' => false, 
            'accountLoginShell' => false, 
            'visibility' => false, 
            'accountStatus' => call_user_func(function() use ($options) {
                if (isset($options['syncAccountStatus'])) {
                    return (bool) $options['syncAccountStatus'];
                }
                return null;
            }),
        ];

        if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()->debug(__METHOD__ . '::' . __LINE__
            . ' Fields to sync (bool: sync empty?): ' . print_r($fieldsToSync, true));

        $recordNeedsUpdate = false;
        foreach ($fieldsToSync as $field => $syncRequired) {
            // IGNORE field even if not empty
            if ($syncRequired === null) {
                continue;
            }
            // Ignore OPTIONAL fields if empty or missing
            else if (($syncRequired === false) && empty($user->{$field})) {
                continue;
            }
            // ldap might not have time information on datetime fields, so we ignore these, if the date matches
            else if ($user->{$field} instanceof Tinebase_DateTime && $currentUser->{$field} instanceof Tinebase_DateTime
                    && $user->{$field}->hasSameDate($currentUser->{$field})
            ) {
                continue;
            }
```

**Comment by lab-at-nohl** [comment]
Thank you, Your code looks like expected.  

I wonder why `syncAccountStatus` is set. Could you temporarily change the source like the part below (two additional lines for log output) and provide a log level DEBUG?

```php
            'accountStatus' => call_user_func(function() use ($options) {
                if (isset($options['syncAccountStatus'])) {
                    if (Tinebase_Core::isLogLevel(Zend_Log::DEBUG)) Tinebase_Core::getLogger()->debug(__METHOD__ . '::' . __LINE__
                        . 'Account status requested: ' . print_r($options['syncAccountStatus'], true));
                    return (bool) $options['syncAccountStatus'];
                }
                return null;
            }),
```

**Comment by Nachtlichtermeer** [comment]
i've changed the code and update next_run for this scheduler in database but it creates a log with 49763 line
and all user-data that i cannot provide public.
Is there something that i ca grep for or something around xyz in log?

**Comment by lab-at-nohl** [comment]
I see. How often does "Account status requested" appear in the log? If it is in every request then look for the string "syncUsers/Groups" and give me all lines with that request id (first column).

**Comment by Nachtlichtermeer** [comment]
i can found this 183 times and looks like it's logged for every user

```
foo@bar:/var/www/bar/htdocs/tine20-log$ grep 'syncUsers/Groups' log_cp  -a -A 5 -B 5
b3b9f8 - -- none -- - 2023-08-25T09:37:55+00:00 DEBUG (7): Tinebase_Group::getInstance::83 groups backend: Ldap
b3b9f8 - -- none -- - 2023-08-25T09:37:55+00:00 INFO (6): Tinebase_Core::setUser::1752 Setting user Admin, Tine20
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 DEBUG (7): Tinebase_ModelConfiguration::_getQueryFilter::1665 Adding title prop as default query filter to MFA_UserConfig
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 INFO (6): Tinebase_Scheduler::run::86 Scheduler started
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 DEBUG (7): Tinebase_Lock_Mysql::tryAcquire::64 Aquired lock: 5bd791c76b26f19805c160ea7b59f24b19aa4b5a
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 INFO (6): Tinebase_Scheduler::run::156 run task Tinebase_User/Group::syncUsers/Groups
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 DEBUG (7): Tinebase_Scheduler_Task::run::172 starting .... 
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 INFO (6): Tinebase_User::syncUsers::903 Start synchronizing users with options Array
(
    [sync_with_config_options] => 1
    [deleteUsers] => 1
--
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 DEBUG (7): Addressbook_Model_ContactHiddenFilter::appendFilterSql::52 Query account contacts (hide if status = disabled)
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 DEBUG (7): Tinebase_Controller_Record_Abstract::search::314 Got 4 search results of Addressbook_Model_Contact
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::increaseRecordSequence::1257 Increasing seq of Tinebase_Model_Group with id 1128 from 0 to 1
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 DEBUG (7): Tinebase_Timemachine_ModificationLog::increaseRecordSequence::1257 Increasing seq of Tinebase_Model_Group with id 1128 from 42265 to 42266
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 DEBUG (7): Tinebase_Controller_Record_ModlogTrait::_writeModLog::96 Writing modlog for Tinebase_Model_Group
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 WARN (4): Tinebase_Scheduler::run::179 task Tinebase_User/Group::syncUsers/Groups failed gracefully
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 INFO (6): Tinebase_Scheduler::run::196 running task Tinebase_User/Group::syncUsers/Groups finished
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 INFO (6): Tinebase_Scheduler::run::98 no due task found, stopping...
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::298 {"file":"tine20.php","method":"Tinebase.triggerAsyncEvents","time":"17.76s","memory":" Memory usage: 44 MB","cache":" Real patch cache size: 4703","pid":637033}
```

**Comment by lab-at-nohl** [comment]
Anything special about group 1148? The snippet shown is about syncing groups. But the problem was that deactivated users get reactivated, right?

Can you find the string "`Account status requested`" anywhere in the log?

I am little confused about this:
`WARN (4): Tinebase_Scheduler::run::179 task Tinebase_User/Group::syncUsers/Groups failed gracefully`

Do you have this failure also in context of user sync?

**Comment by Nachtlichtermeer** [comment]
yes, deactivated users are reactivated after this job

"Account status requeste" are 183 times in the log; example:

```
b3b9f8 - tineadmin - 2023-08-25T09:38:07+00:00 DEBUG (7): Tinebase_User_Ldap::_getLdapEntry::699 filter (&(objectclass=posixaccount)(uidnumber=3056))
b3b9f8 - tineadmin - 2023-08-25T09:38:07+00:00 DEBUG (7): {closure}::692Account status requested: 
b3b9f8 - tineadmin - 2023-08-25T09:38:07+00:00 DEBUG (7): Tinebase_User::_checkAndUpdateCurrentUser::700 Fields to sync (bool: sync empty?): Array
(
    [accountLoginName] => 1
    [accountLastPasswordChange] => 
    [accountExpires] => 
    [accountPrimaryGroup] => 1
    [accountDisplayName] => 
    [accountLastName] => 1
    [accountFirstName] => 1
    [accountFullName] =>
...
```
```
# grep syncUsers log_cp -a
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 INFO (6): Tinebase_Scheduler::run::156 run task Tinebase_User/Group::syncUsers/Groups
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 INFO (6): Tinebase_User::syncUsers::903 Start synchronizing users with options Array
b3b9f8 - tineadmin - 2023-08-25T09:37:55+00:00 DEBUG (7): Tinebase_User::syncUsers::919 About to sync 193 users from sync backend ...
#4 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#4 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#4 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#4 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#3 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
b3b9f8 - tineadmin - 2023-08-25T09:38:07+00:00 DEBUG (7): Tinebase_User::syncUsers::940 Finished synchronizing users.
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 WARN (4): Tinebase_Scheduler::run::179 task Tinebase_User/Group::syncUsers/Groups failed gracefully
b3b9f8 - tineadmin - 2023-08-25T09:38:12+00:00 INFO (6): Tinebase_Scheduler::run::196 running task Tinebase_User/Group::syncUsers/Groups finished
```

**Comment by lab-at-nohl** [comment]
Can you post one of the stack traces? Beginning with "#0", "#1" etc.

**Comment by Nachtlichtermeer** [comment]
```
b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 NOTICE (5): Tinebase_Exception::logExceptionToLogger::155 #0 .../Tinebase/Group/Ldap.php(1008): Tinebase_Group_Ldap->_getUserMetaData()
#1 .../Tinebase/Group.php(168): Tinebase_Group_Ldap->getGroupMembershipsFromSyncBackend()
#2 .../Tinebase/User.php(619): Tinebase_Group::syncMemberships()
#3 .../Tinebase/User.php(925): Tinebase_User::syncUser()
#4 .../Tinebase/Scheduler/Task.php(209): Tinebase_User::syncUsers()
#5 .../Tinebase/Scheduler.php(169): Tinebase_Scheduler_Task->run()
#6 .../Tinebase/Frontend/Cli.php(395): Tinebase_Scheduler->run()
#7 .../Tinebase/Frontend/Cli.php(344): Tinebase_Frontend_Cli->triggerAsyncEvents()
#8 .../Tinebase/Server/Cli.php(111): Tinebase_Frontend_Cli->handle()
#9 .../Tinebase/Core.php(271): Tinebase_Server_Cli->handle()
#10 .../tine20.php(73): Tinebase_Core::dispatchRequest()
#11 {main}
b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 DEBUG (7): Tinebase_User::syncUser::497 Sync options: Array
(
    [sync_with_config_options] => 1
    [deleteUsers] => 1
    [syncContactPhoto] => 1
    [syncContactData] => 1
    [syncAccountStatus] => 
)

b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 INFO (6): Tinebase_User::syncUser::501 Sync user data for: mkn
b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 DEBUG (7): Tinebase_User_Ldap::_getLdapEntry::699 filter (&(objectclass=posixaccount)(uid=mkn))
b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 DEBUG (7): Tinebase_User::syncUser::517 Sync User: Array
(
    [accountFullName] => foo foo
    [accountDisplayName] => foo foo
    [accountPrimaryGroup] => 2083
    [accountFirstName] => foo
    [accountHomeDirectory] => /home/foo
    [accountLoginShell] => /bin/bash
    [accountLastName] => foo
    [accountLoginName] => foo
    [accountId] => 2083
    [accountStatus] => enabled
)

b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 DEBUG (7): Tinebase_User_Ldap::_getLdapEntry::699 filter (&(objectclass=posixaccount)(uidnumber=2083))
b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 DEBUG (7): {closure}::692Account status requested: 
b3b9f8 - tineadmin - 2023-08-25T09:37:58+00:00 DEBUG (7): Tinebase_User::_checkAndUpdateCurrentUser::700 Fields to sync (bool: sync empty?): Array
(
    [accountLoginName] => 1
    [accountLastPasswordChange] => 
    [accountExpires] => 
    [accountPrimaryGroup] => 1
    [accountDisplayName] => 
    [accountLastName] => 1
    [accountFirstName] => 1
    [accountFullName] => 
    [accountEmailAddress] => 1
    [accountHomeDirectory] => 
    [accountLoginShell] => 
    [visibility] => 
    [accountStatus] => 
)
```

do you mean this?
this one is an old user. he is still in ldap but not in use (has no password and so on)

**Comment by Nachtlichtermeer** [comment]
damn, maybe it is a problem with parallel use of both:
- setup.php --sync_accounts_from_ldap
- tine20.php --method Tinebase.triggerAsyncEvents

the first one we used the last years and the second one is new

**Comment by Nachtlichtermeer** [comment]
Syncing ldap accounts runs every 15 minutes so once per hour both jobs run parallel.
But the problem exists without `setup.php --sync_accounts_from_ldap` too.

no, we only use groups syncing from ldap and we never delete groups (even in ldap)

but how is it possible that a group error is reactivating all disabled users?

i could try `accountStatus` as attribute in ldap; maybe problems then gone away
but now i'm away for 2 weeks in holidays

**Comment by lab-at-nohl** [comment]
> but how is it possible that a group error is reactivating all disabled users?

I cannot say for sure and it is hard to understand without the full log file. Following the stack trace the program execution goes like this `Tinebase_User::syncUser()` -> `Tinebase_Group::syncMemberships()` -> `Tinebase_Group_Ldap->_getUserMetaData()`. Eventually it brakes. 

In my understanding `public function getGroupMembershipsFromSyncBackend($_userId)` is invoked by the sync of a user to fetch its memberships. I GUESS that an exception in this function returns an unclear state, so the user is not synced fully and rendered active for that reason. 

What can you tell me about group memberships of the deactivated users - in Tine 2.0 and in LDAP?

**Comment by Nachtlichtermeer** [comment]
old users are moved to sub-OU "old" and the password-entry will be removed
the users are removed from all groups except it's own personal user group.

can i send you a full log directly (non-public)?

i've tested again with 2023.09.23.42: error persists

**Comment by Nachtlichtermeer** [comment]
> In my understanding `public function getGroupMembershipsFromSyncBackend($_userId)` is invoked by the sync of a user to fetch its memberships. I GUESS that an exception in this function returns an unclear state, so the user is not synced fully and rendered active for that reason.

I've updated the title so it's clear: all disabled users are reactivated - not only one specific

**Comment by lab-at-nohl** [comment]
> old users are moved to sub-OU "old" and the password-entry will be removed
> the users are removed from all groups except it's own personal user group.

Can you post a screenshot from your Authentication settings in setup.php (to check ldap details)?

> can i send you a full log directly (non-public)?

You can do so. My username is a mail address excluding the tld .eu. However, I am not with the company behind Tine 2.0. I am just a user...

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
