### ISSUE TITLE
Admin / Users shows error

### ISSUE THREAD

**Issue by crosenbe** [tine20/tine20#7479]
With release 2022.12.1 the user tab has no entries, instead an error messages appears.

```
e7d2a3 cdad2 admin - 2023-08-25T06:27:27+00:00 ERR (3): Tinebase_Server_Json::_handleException::443 TypeError -> Return value of Tinebase_User_Plugin_Abstract::getEmailUserName() must be of the type string, null returned
e7d2a3 cdad2 admin - 2023-08-25T06:27:27+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 TypeError -> Return value of Tinebase_User_Plugin_Abstract::getEmailUserName() must be of the type string, null returned
e7d2a3 cdad2 admin - 2023-08-25T06:27:27+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../Tinebase/EmailUser/Imap/Standard.php(64): Tinebase_User_Plugin_Abstract->getEmailUserName()
#1 .../Admin/Controller/User.php(104): Tinebase_EmailUser_Imap_Standard->inspectGetUserByProperty()
#2 .../Admin/Frontend/Json.php(266): Admin_Controller_User->searchFullUsers()
#3 .../Admin/Frontend/Json.php(310): Admin_Frontend_Json->getUsers()
#4 .../vendor/zendframework/zendframework1/library/Zend/Server/Abstract.php(231): Admin_Frontend_Json->searchUsers()
#5 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(603): Zend_Server_Abstract->_dispatch()
#6 .../vendor/zendframework/zendframework1/library/Zend/Json/Server.php(206): Zend_Json_Server->_handle()
#7 .../Tinebase/Server/Json.php(410): Zend_Json_Server->handle()
#8 .../Tinebase/Server/Json.php(177): Tinebase_Server_Json->_handle()
#9 .../Tinebase/Core.php(271): Tinebase_Server_Json->handle()
#10 .../index.php(24): Tinebase_Core::dispatchRequest()
#11 {main}
```

The reason is probably wrong values in field email of the accounts table.

```
+-------------------+------------------------------+
| login_name        | email                        |
+-------------------+------------------------------+
| admin             |                              |
| replicationuser   | NULL                         |
| anonymoususer     | NULL                         |
| usera             | usera@foo.bar                |
| sys-tine20-foobar |                              |
| setupuser         | NULL                         |
| userb             | userb@foo.bar                |
+-------------------+------------------------------+
```

i don't know how these values came in but what values are allowed, not every user need to get an mail address.

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
